### ISSUE TITLE
Artifact representation in Pipeline

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/pipelines#1003]
Are there any thoughts on how to define custom artifacts in pipelines which different steps can consume? For e.g. if we need to bring in a model as a typed artifact object, which a pipeline can consume, and it can be defined in DSL

**Comment by Ark-kun** [comment]
A good way that also follows Argo would be to add the `input_artifact_paths` and `output_artifact_paths` parameters to the `ContainerOp` constructor, so that it's possible to specify the artifact names and file locations where the system should place or collect them.
`output_artifact_paths={"out_art1": "/outputs/out_art1/data", ...}`
`input_artifact_paths={"in_art1": "/inputs/in_art1/data", ...}`

Adding the artifact production support to the DSL compiler is easy.
Adding the artifact consumption support to the DSL compiler is more complicated as the compiler code is quite convoluted.

**Comment by hongye-sun** [comment]
@animeshsingh would you mind giving us more context of your use cases about typed artifact object?

We are in an effort to support artifact metadata (including location, type and runtime data) tracking in a metadata store. For consuming artifact inside a pipeline, we are still open to advice.

**Comment by Ark-kun** [comment]
Specifying output artifacts is now possible since 
https://github.com/kubeflow/pipelines/pull/998
Input artifacts are waiting for https://github.com/kubeflow/pipelines/pull/791 to be merged .
Then we'll need to update the compiler to support passing output artifacts to artifact inputs.

**Comment by gaoning777** [comment]
@animeshsingh same as hongye, more context is welcome. Is this issue about defining custom artifact types or artifact passing, or both? Thanks

**Comment by Ark-kun** [comment]
Fixed by #791, #998 , https://github.com/kubeflow/pipelines/pull/2173
