### ISSUE TITLE
continuous delivery and gitops

### ISSUE THREAD

**Issue by ryandawsonuk** [kubeflow/pipelines#1352]
At seldon we're keen on doing continuous delivery with gitops. As others [have pointed out](https://github.com/kubeflow/pipelines/issues/604), it's currently not easy to see how to do this with pipelines so I wanted to propose an approach to see what people think. 

The purpose of the approach would be to achieve all of:

1) Have a pipeline that could be hooked up to watch a bucket and run on an event trigger.
2) Run experiments for that pipeline in development - here it need not respond to events and could just be manually triggered but ideally both would be options.
3) Promote the whole pipeline through to staging, where it would need to be able to respond to events.
4) Promote that to prod. There it would be monitoring a different bucket/resource.

Re-running the pipeline on an event is one concern - that is the pipeline responding to new data (or on a business-defined schedule) and is part of what the pipeline needs to do. Re-running it when its code changes seems to me to be another kind of concern - that is a code change that needs to be validated. For that pipelines need to fit into a CI/CD setup. 

All of the above should be achieved with an awareness that there may be other resources in the same namespace. Perhaps the end result is a model that serves predictions and the system calling it to consume the predictions could also be in that namespace and be getting promoted via gitops.

It would be good to use a tool such as ArgoCD to do gitops but it won't natively understand the pipeline .py files. So the first step to doing gitops could be to set up a jenkins (or other CI) job to watch a repo where a pipeline .py file would live. It would automatically run dsl-compile and generate a .tar.gz file. It would then also extract that out to yaml and push the yaml to a different git repo (to avoid causing an infinite loop of build triggering). ArgoCD would be set up to watch that second repo, which would be where the yaml is. 

ArgoCD can do gitops on k8s resources, syncing them to the cluster/namespace but this would need a bit of nuanced handling for argo yaml. For this we would need to run the job every time a pipeline code change is detected and only when the change in the repo is to the pipeline, not to an unrelated resource, if there are any in the repo - I think we could limit the scope of the pipeline-specific syncing in ArgoCD by making the pipeline its own app. When ArgoCD detects a change I expect it to automatically do a `kubectl apply`. Doing a `kubectl apply` [on an argo resource](https://github.com/argoproj/argo/blob/master/examples/README.md#argo-cli) should run the job, which is what we want. ArgoCD would have to be setup not to [auto-prune](https://argoproj.github.io/argo-cd/user-guide/auto_sync/#automatic-pruning) resources not coming directly from the git repo as the pipeline itself might need to create resources (e.g. for serving). 

ArgoCD could be setup with one app configuration for staging and another for prod. These could actually point at the same repo and have staging on [automated sync](https://argoproj.github.io/argo-cd/user-guide/auto_sync/#automated-sync-policy) and prod on manual sync initiation. If the same repo then[ parameter overrides](https://argoproj.github.io/argo-cd/user-guide/parameters/) might be needed to point at different buckets. Otherwise different repos would be needed and promotion could be via pull request.

The job may also be triggered to run when there's an event such as a change to the data and that should be ok too. The point of the setup would be have controlled handling of changes to pipeline code.

**Comment by vicaire** [comment]
Adding a couple folks that are interested in the topic of CI/CD: 
/cc @ucdmkt 
/cc @ksalama

**Comment by ryandawsonuk** [comment]
There’s a great new CI/CD example in https://github.com/aronchick/kubeflow-and-mlops. That shows a training pipeline that promotes a packaged model to a serving stage. What is importantly different there from the proposal above is that there isn’t an intention to automatically handle regularly arriving new data. This means it is possible to have a single build/train workflow and promotion then is of the packaged model. This is easier as you can then do gitops on the serving stage, which means gitops on plain k8s yaml and not argo. One might be tempted to use the same setup but with automatic promotion to handle newly-arriving data. In that scenario if you make code changes that break the build pipeline then you lose the ability to get new data into prod. So to handle a regular feed automatically and still facilitate safe experimentation requires more than one pipeline running. 

I’d suggest this means the variety of CI/CD use-cases is becoming clearer as well as how they could be handled.

**Comment by cbreuel** [comment]
I implemented a [similar solution for a customer](https://cloud.google.com/blog/products/ai-machine-learning/itau-unibanco-how-we-built-a-cicd-pipeline-for-machine-learning-with-online-training-in-kubeflow), using Jenkins. I think the right approach is to use traditional CI/CD to deploy the training pipeline and components, since they only depend on code. Model training depends on data, which has a different lifecycle. I wrote [this article](https://towardsdatascience.com/ml-ops-machine-learning-as-an-engineering-discipline-b86ca4874a3f) to explain this line of reasoning in more detail.

What this would mean for a gitops model in Kubeflow would be to use a traditional system like Jenkins to build, test and deploy the pipeline, potentially triggering a training right after, then establishing a separate training triggering mechanism, which could be e.g. based on availability of new data, a fixed schedule, triggered by monitored metrics, or manual.

What do you think of this approach?

**Comment by midhun1998** [comment]
I really like the approach taken by @ryandawsonuk  and @cbreuel . But a thought why can't we have a Kubeflow pipeline itself to do the CI/CD for us as it's a workflow kind. One way to achieve it would be expanding the trigger part of Kubeflow pipeline to support other triggers apart from Cron and Periodic. And the other way would be to use something like Argo Events which would trigger a simple Argo workflow through GitHub webhook events. ([https://argoproj.github.io/argo-events/](https://argoproj.github.io/argo-events/)) I had tried partially what @ryandawsonuk suggests where we apply pipeline manifest using `kubectl apply -f` but that didn't work out well as Kubeflow pipeline UI won't recognize it until it is persisted in the storage AFAIK.

**Comment by ashrafgt** [comment]
/reopen

Please consider revisiting this topic. It would be very useful to be able to create pipelines and pipeline versions using GitOps. 

I also expected that pipelines could be created by doing `kubectl apply -f complied-pipeline.yaml`, but I guess that's not possible at the moment.

**Comment by thesuperzapper** [comment]
As part of [deployKF](https://github.com/deployKF/deployKF), I have produced a reference implementation for using GitOps to manage Kubeflow Pipeline definitions & schedules, you can find it in the [`deployKF/kubeflow-pipelines-gitops`](https://github.com/deployKF/kubeflow-pipelines-gitops) repo.

Due to Kubeflow Pipeline's limitations around updating scheduled runs described in https://github.com/kubeflow/pipelines/issues/3789, the reference implementation uses clever tricks to manage the "updating" of already scheduled runs. Because of this, if you need to ensure only a single run happens during updates, you will need to put a step at the beginning of your pipeline to skip the run if its already running (or you can set `keep_history` to `0`, but this will also result in the immediate termination of any current runs during updates).

/reopen
