### ISSUE TITLE
[Feedback] Kubeflow and pipelines in general

### ISSUE THREAD

**Issue by wzrdtales** [kubeflow/pipelines#1396]
Since I am digging through the whole kubeflow project as the documentation is just ultimately scarce. I am stumbling over more and more issues. I want to use this issue as a thorough feedback to you.

So first thing is of course the documentation. Every part of the documentation needs definitely work, and you probably know this very well already. But it made me wonder that especially the parts that seem to be the core of the whole project, lack so much documentation. For example the pipelines section has no structure at all, misses a ton of information, is already outdated and for an user newly joining, harshly stating would be more useful with no doc at all and send him directly off to the code behind the dsl to get the information from there. Which was the only possibility to figure out things like configuring s3 + regions/endpoints.

The next things are components, which are being used in examples. I transferred today https://github.com/kubeflow/examples/tree/master/pipelines/mnist-pipelines from gcp to aws. While here most stuff is outdated (outdated examples maybe really should be removed if not updated) the last thing I stumbled over after finally fixing all of the components, was that the https://github.com/kubeflow/pipelines/tree/master/components/kubeflow/deployer component which seems to be ment to be served as a general reusable component (correct me if i am wrong) is actually only working with the gcp assumption. So in short most stuff looks, feels and in this case in fact was only build for google as a platform and nothing else.

Nevertheless I think the project has potential, but there definitely needs  a lot of attention and love being put into the docs (may be raise money to do it, or let someone do it), b/c otherwise you loose people that are not like me, in the first 5 minutes already - forever. Since documents make to many assumptions of knowledge being already there (including knowledge that can't be there yet - kubeflow itself), don't have any structure to it or a red line through them at all and every section just stops somewhere in the middle not quite covering the topic.

Apart from that, while creating and professionalising the machine learning setups (especially  enhancing the data scientists work flows which can learn a lot from the development world) on this side. There is some questions that arised to me. What exactly is the benefit of having kubeflow pipelines instead of utilizing a mature and grown ci like gitlab ci, which can do the same thing, but is actually already stable. Where exactly we do benefit from a pipeline like kubeflow or dvc offers. Only when the structure of execution gets so complicated that a ci can't handle it anymore? I would be deeply interested from you the creators about your thoughts about that topic.

All in all I think that kubeflow and others like dvc are pushing in the right direction, but there are questions on the table and there will be a lot of change in the coming years (for example finally getting rid of jupyter notebooks), that is certain. I again want to point out that I think you do a great job here and this is realy only some feedback and thoughts from my side, that came up while evaluating kubeflow and other frameworks.

**Comment by Ark-kun** [comment]
>is actually only working with the gcp assumption.

Apart from the GCP components (that are obviously tied to GCP), the biggest issue is data storage and passing. The current crop of components should support any S3 storage (not just GCS), so they can be portable. If it isn't then it's a bug. But I agree that portability needs to be much better.

>What exactly is the benefit of having kubeflow pipelines instead of utilizing a mature and grown ci like gitlab ci, which can do the same thing, but is actually already stable. Where exactly we do benefit from a pipeline like kubeflow or dvc offers. Only when the structure of execution gets so complicated that a ci can't handle it anymore? I would be deeply interested from you the creators about your thoughts about that topic.

Pipelines is intended to be a glue that makes it much easier to combine together existing code to build something bigger. Of course you can always replicate it with hand-written scripts, but the value should be in reducing boilerplate and making things easier. Can you replace Makefile with a Shell script? Of course. But people still use Makefiles, because they automate some of the boilerplate. Can you use Makefile or a shell script which calls kubectl instead of KF Pipelines? You can, but there is a value in stepping up and letting the system do boilerplate for you.

I'd say that the biggest benefit of systems like Pipelines (and Argo) is automatic data management (we're not fully there yet). Most CI's do not have concept of data passing. They just orchestrate task dependencies (not data dependencies). What we can provide is a system that stores the data for you, guarantee that you never overwrite any data and that you can always understand where did the particular piece of data come from.
Some other benefits are componentization, encapsulation, reproducibility, versioning. At some point when writing code you start incapsulating parts of it, creating reusable functions with well-defined signatures. That's what components should be. A versioned implementation with a well-defined signature. A component that you can connect with other components to build something bigger (and incapsulate it again into something reusable).
Imagine running 10 slightly different versions of a long pipeline with all the identical processing steps reused.
**Imagine stumbling upon a 3-years old model  and being able to open the run that produced it 3 years ago, clone it and run again exactly as it was executed. And then doing a small fixes and re-running.**

Sure, there is always some cognitive overhead when going to a higher-level solution. But this overhead can be reduced to the point where your first instinct (as a person that wants to experiment with data) will not to run things locally, but rather to use an orchestration system.

**Comment by wzrdtales** [comment]
> Of course you can always replicate it with hand-written scripts, but the value should be in reducing boilerplate and making things easier.

Yah but that is actually my point: In the end, the DSL for the pipeline ends up being hand-written scripts. And currently the DSL has more boilerplate, than a good and modern CI (especially referring to the previously mentioned gitlab ci and not outdated dinosaurs like jenkins). 

> I'd say that the biggest benefit of systems like Pipelines (and Argo) is automatic data management (we're not fully there yet). Most CI's do not have concept of data passing. They just orchestrate task dependencies (not data dependencies). What we can provide is a system that stores the data for you, guarantee that you never overwrite any data and that you can always understand where did the particular piece of data come from.

Is there an outline how this will look like? Or not even planned yet, if there is anything, I would be highly interested. It is true, that most CI's don't do that, also modern ones have artifact support, but surely, those are intended for the next task only, so they kind of miss the point and of course this data would be most often way to big for such artifacts. And are there also plans to integrate into data version management when we talk about automatic data management?

> Imagine stumbling upon a 3-years old model and being able to open the run that produced it 3 years ago, clone it and run again exactly as it was executed. And then doing a small fixes and re-running.

Given you've unlimited amount of storage capacity. 3 Years old stuff will very probable be needed to be cleaned up way before that. But that is where the ci comes in rebuilding them from the versioned code base. And I highly doubt that anyone will just make small fixes to a 3 year old model without investing a serious amount of time, understanding the work behind it before doing this.

> That's what components should be. A versioned implementation with a well-defined signature. A component that you can connect with other components to build something bigger (and incapsulate it again into something reusable).

Agreeing, also that is not really unique.

> Sure, there is always some cognitive overhead when going to a higher-level solution. But this overhead can be reduced to the point where your first instinct (as a person that wants to experiment with data) will not to run things locally, but rather to use an orchestration system.

There will always be times to experiment locally, with a small dataset (for example in the tram with bad internet connection, but electricity available), but I never seen anyone testing with the real deal on their local machines yet (not that they're not there, just haven't seen any :joy: )

For me the most important thing is, also reach reproducibility, versioning and even more important efficient collaboration (and also authentication since not everyone should be able to just replace a production model...). One thing that still bothers me are jupyter notebooks (which I see being dropped a lot as soon as projects get professional and big), if I remember right I was reading you guys also plan to drop it? If so, may I ask if there is any target of interest for replacement yet? B/c the only really valuable thing of `jupyter` is to run it on a powerful machine remote and have that power at hand. But the same thing can be achieved with a proper remote development setup.

Thank you for your answer so far and the insights!
