### ISSUE TITLE
Logs are effectively impossible to copy when the log window has scroll-bar

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#1508]
There is something wrong with log line selection. You cannot select more lines than fits in the window and when you scroll, some weird things happens with the selection.
This is probably caused by the line numbering UX component.
I'd prefer working selection over line numbering (whih might not add much value to the logs).

**Comment by Bobgy** [comment]
@Ark-kun Do you mean selecting log of a pipeline run step? I tried this and it selects with no issues when log has more than one screen with chrome on a macbook.

Is this issue already fixed? or it only reproduces on a different device?

**Comment by Bobgy** [comment]
My attempt video: https://drive.google.com/file/d/1flmz7jiM84nZ8DgPTBMNiM-T8oUJWEVq/view

**Comment by martin-laurent** [comment]
I'm not sure this video is testing the right thing. For example, given your video, the faulty behavior is that, if you were to copy/paste the text selected you would get only lines from 12 to 41 instead of 7 to 41 as you would expect. This is terrible for long logs.

**Comment by mattnworb** [comment]
The problem is especially pronounced (in my experience) when the component is still running and therefore producing new logs.

**Comment by Bobgy** [comment]
Thanks for the explanation. Now I understand the problem. Will think about a fix.

**Comment by Bobgy** [comment]
Sorry for not replying for a while, because I've got some other stuff on my priority list. I just tried to investigate the issue today.

The problem is with our own implementation of LogViewer component. It uses react-virtualized under the hood to deal with large size of logs. react-virtualized only renders visible and a few more hidden lines on the screen. Therefore, it doesn't work with selection + scrolling well.

If selection is an important feature, then my proposed workaround is to only render like last 1000 lines of log in UI and stop using react-virtualized.

Reasoning:
* Selection works natively without virtualization
* UI won't crash when log size is huge. It just provides limited content (last 1000 lines), which I think is enough. If more is needed, user can choose another alternative to view logs.

**Comment by Bobgy** [comment]
@Ark-kun what do you think about the solution?

**Comment by Bobgy** [comment]
A demo about the fix: https://drive.google.com/file/d/1GAvGwGYLHPfkAu8idTTJ1yf9xALDUMxR/view

**Comment by Bobgy** [comment]
I also researched npm libraries that we can use out of box.

I found this one, but I worry the amount of maintenance it gets: https://github.com/mozilla-frontend-infra/react-lazylog

**Comment by martin-laurent** [comment]
Personally I think that keeping only 1000 lines of code would NOT be a good idea as that would hide logs of things happening at startup (before a really long tensorflow stacktrace for example).

If anything, there is a related bug where there is either links to stackdriver logs OR the logs in the UI but never both. Having them both always visible (or at least the stackdriver logs) always visible would be better.

Also when the component is running (before it is fully done) the it's impossible to scroll, because the viewing component seems to force the position at the bottom y every few seconds which is really annoying.

If these two things can be fixed, personally I'd be in a much happier place.

**Comment by Bobgy** [comment]
@martin-laurent thanks for the valuable feedback.

What about top 1000 lines + bottom 1000 lines? that will be trickier to implement, but still doable.

> If anything, there is a related bug where there is either links to stackdriver logs OR the logs in the UI but never both. Having them both always visible (or at least the stackdriver logs) always visible would be better.

Can you point me to the issue? I think that should be fixed for sure.

> Also when the component is running (before it is fully done) the it's impossible to scroll, because the viewing component seems to force the position at the bottom y every few seconds which is really annoying.

This is our bug, I can easily fix it.

**Comment by Bobgy** [comment]
I made a PR: https://github.com/kubeflow/pipelines/pull/2370 that can fix:
* this issue, logs cannot be copied when scrolling
* > Also when the component is running (before it is fully done) the it's impossible to scroll, because the viewing component seems to force the position at the bottom y every few seconds which is really annoying.

**Comment by martin-laurent** [comment]
@Bobgy Looks perfect IMO

**Comment by Bobgy** [comment]
@martin-laurent Great, I will continue with the approach.
