### ISSUE TITLE
returned type validation inconsistent between lightweight component and container build

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#1580]
Returned type validation for build_python_component is defined as [_component_builder.py#L313](https://github.com/kubeflow/pipelines/blob/2d0d8619507743ec4ff1e213735a8f82d3913281/sdk/python/kfp/compiler/_component_builder.py#L313 )

```
    if 'return' in  annotations and annotations['return'] not in [int, float, str, bool]:
      raise Exception('Output type not supported and supported types are [int, float, str, bool]')
```

Which does not support NamedTuples,  however func_to_container_op  supports NamedTuple with logic defined @ [_python_op.py#L136](https://github.com/kubeflow/pipelines/blob/3aeab312f204d0fd978585f13c2b1dc47e26c349/sdk/python/kfp/components/_python_op.py#L136)

**Comment by Ark-kun** [comment]
Lightweight components are more advanced in multiple aspects. They support multiple outputs and allow specifying arbitrary types. Python container components will be soon be merged with lightweight components an use the lightweight components' code generator, so this issue will be fixed by that effort.

**Comment by Ark-kun** [comment]
Will be fixed by https://github.com/kubeflow/pipelines/issues/1687
