### ISSUE TITLE
Update the test infrastructure to use kustomize

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#1639]
Currently the test infra deploys a cluster with pipeline code from HEAD
https://github.com/kubeflow/pipelines/blob/master/test/deploy-kubeflow.sh#L35
https://github.com/kubeflow/pipelines/blob/master/test/deploy-pipeline.sh#L50
relying on ksonnet.

We need to update these script to use kustomize as kubeflow is deprecating ksonnet in favor of kustomize.

**Comment by Bobgy** [comment]
Depends on https://github.com/kubeflow/pipelines/issues/1638

**Comment by Bobgy** [comment]
General plan:
* (p0) presubmit/postsubmit tests should run on [kfp lightweight deployment](https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize).
* (p1) the same tests should run continuously for master branch on kubeflow 0.6 deployment.

My plan
1. https://github.com/kubeflow/pipelines/pull/1732 that let me run tests on my own gcp project
2. change presubmit-tests-with-pipeline-deployment.sh to run tests on kfp lightweight deployment
3. change postsubmit-tests-with-pipeline-deployment.sh to run tests on kfp lightweight deployment
4. add an additional flag on presubmit and postsubmit tests to run on kubeflow 0.6 and configure it to run continuously (instead of presubmit/postsubmit)

**Comment by Bobgy** [comment]
@jessiezcc all p0 issues are resolved, can we change the tag to p1 now?

**Comment by Bobgy** [comment]
Actually, I think it's better creating a new issue for
> add an additional flag on presubmit and postsubmit tests to run on kubeflow 0.6+ and configure it to run continuously (or maybe postsubmit?

**Comment by Bobgy** [comment]
/close

Created new issue for step 4.
