### ISSUE TITLE
Allow for Tensorboard flags

### ISSUE THREAD

**Issue by zanedurante** [kubeflow/pipelines#1641]
In my project I want to run tensorboard with the `--samples_per_plugin=images=100` flag.  Is there no way to do this from within KFP?

**Comment by neuromage** [comment]
@jingzhang36 it would be nice to be able to specify pod template parameters when launching TB. This will also let users do things like mount volumes for TB to read from, as requested in #699. Would you be willing to look into how feasible doing this from the UI would be? 

/assign @jingzhang36

**Comment by jingzhang36** [comment]
I am thinking about a possible approach without FE change (need to double check with @neuromage to see if it is actually feasible). 

We can allow users to set the flag as a new field in metadata json. Currently Tensorboard type only support "source" fields in metadata json file. We can have more there.  These flags/fields will be written to viewer crd yaml and thus reconciler.go will use these flags to start tensorboard instance.

This possible approach is relatively easy since no FE change is needed. The downside is users can adjust those values via UI....

**Comment by neuromage** [comment]
@jingzhang36 I think what you suggest is feasible, but I think the downside you mentioned should also be taken into account. Ideally, we want users not to have to encode everything they need to later view their tensorboard logs during the training phase itself. It should be customizable at the time we're launching the viewer. Hence, I recommend we allow users to specify these flags in the UI instead. What do you think?

**Comment by Bobgy** [comment]
This looks still a valid feature request

**Comment by Bobgy** [comment]
This is already supported by https://github.com/kubeflow/pipelines/pull/5515,
the args can also be overridden by the patch
