### ISSUE TITLE
feature request: restore the client method for creating a pipeline

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#175]
In addition to `run_pipeline` (which doesn't actually create a pipeline object in the UI), bring back the client method for actually creating the pipeline. 
People might want to share pipelines, later run other experiments based on that pipeline definition but don't have the original notebook to hand, etc.
(Bradley has the context on this).

**Comment by yebrahim** [comment]
Currently, starting a run out of a notebook embeds the pipeline spec in that run, so users can clone it, modify parameters, and start a new run.

I think what we actually want here is embedding the Python source code instead of the compiler output in the run, so that users can go from a run to a notebook, and continue working.

**Comment by vicaire** [comment]
Resolving as cloning pipelines is supported (whether they are created/run from notebooks or from the UI). Please re-open if there is any outstanding issues.
