### ISSUE TITLE
unexpected parameter name conversion by DSL 

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#205]
Here is snippet of the pipeline definition
```
@dsl.pipeline(
  name='training',
  description='Example training pipeline'
)
def foo(project, working_dir):
....
```

And when I submit a run I need to do
```
run = client.run_pipeline(exp.id, 'training', 'training.tar.gz',
                          params={'project': PROJECT, 'working-dir': WORKING_DIR})
````

Here **working_dir** is converted to **working-dir** which is somewhat unexpected. I have to look into the generated yaml to find out what it actual converted to.

**Comment by Ark-kun** [comment]
>Here is snippet of the pipeline definition

Do we really have a snippet like that? AFAIK, right now all pipeline parameters look like this: `predict_mode: dsl.PipelineParam=dsl.PipelineParam(name='predict-mode', value='local')`

I wonder what happens with the parameter names in  https://github.com/kubeflow/pipelines/pull/110/files

I agree that this needs to be handled in a way that's easy for the user. Quite a good chunk of my python component support code deals with naming.

**Comment by Ark-kun** [comment]
I confirm that this issue still exists. @gaoning777 , can you look at the pipeline parameter sanitization? Argo now allows underscores in parameter names.

**Comment by gaoning777** [comment]
The naming sanitization is necessary to convert the python names to argo compatible names. 
The next argo release should support underscores and we do not need the underscore to dash conversion.

**Comment by gaoning777** [comment]
@Ark-kun is argo supporting the underscore in 2.3, the current version pipeline deploys?

**Comment by gaoning777** [comment]
@Ark-kun gently tap.

**Comment by Ark-kun** [comment]
> @Ark-kun is argo supporting the underscore in 2.3, the current version pipeline deploys?

/cc @gaoning777 
Yes. We're deploying Argo 2.3 since June 1 
https://github.com/kubeflow/kubeflow/pull/3349 https://github.com/kubeflow/kubeflow/pull/3374 https://github.com/kubeflow/kubeflow/commits/pipelines/kubeflow

Unfortunately, many of our customers probably have older versions. Their experience will be broken if they try to run pipelines with inputs/outputs containing underscores.
Do you think it's best to make the change right now or should we wait more, so that the users can upgrade?

**Comment by Ark-kun** [comment]
Fixed by https://github.com/kubeflow/pipelines/pull/466
