### ISSUE TITLE
Update UI to display step duration

### ISSUE THREAD

**Issue by hlu09** [kubeflow/pipelines#2159]
It is nice to know how long individual step took.

**Comment by rmgogogo** [comment]
@hlu09 Thanks for feedback. 
Would you help provide more info so that we can handle it better?

Any reason why you prefer display the step duration? For debugging purpose?

**Comment by hlu09** [comment]
Current UI has "start" and "end" time of each step. It'd be nice to show a duration too to save users from  doing mental math to figure out how long it ran.

**Comment by Bobgy** [comment]
I think this looks like a small change, and it is useful in many cases (understanding pipeline performance e.t.c).

**Comment by elikatsis** [comment]
Hi there,

Does the current UI show the start & end time of each step?
If yes (as mentioned in a previous comment), I can't find it :sweat_smile: could you guide me a bit where to look for it?
If not, and since this information is persisted in the workflow's status which is already parsed by the UI (`Workflow.Status.Nodes`), is there any design for the desired UX and an estimation for its implementation?

Thanks!

**Comment by Bobgy** [comment]
Hi @elikatsis, I checked and looks like KFP UI doesn't show step level start and end time, it only shows workflow start and end time.
But the data is available anyway in https://github.com/kubeflow/pipelines/blob/f8a452187673da80ff90fc98dcdf4b348cf8034f/frontend/src/lib/WorkflowParser.ts#L90, the nodeStatus type has startedAt and finishedAt fields recording this.

**Comment by Bobgy** [comment]
we plan to do this

**Comment by zijianjoy** [comment]
We now have a tab to show all the task details, including duration: https://github.com/kubeflow/pipelines/pull/5023
