### ISSUE TITLE
Could not connect to the metadata of TFX on the notebook environment

### ISSUE THREAD

**Issue by mesaverde0207** [kubeflow/pipelines#2169]
I'm just a beginner at kubeflow and  also tfx, so this may be an elementary question.
I deployed kubeflow v0.6.2  to GCP by the UI deployment tool 
and tried "TFX on KubeFlow Pipelines Example".
(https://github.com/kubeflow/pipelines/blob/master/samples/core/tfx-oss/TFX%20Example.ipynb) in its notebook server.

All pipeline executions ran well, but I could not connect to the ML metadata store:

```python
connection_config = metadata_store_pb2.ConnectionConfig()
connection_config.mysql.host = os.getenv('MYSQL_SERVICE_HOST')
connection_config.mysql.port = int(os.getenv('MYSQL_SERVICE_PORT'))
connection_config.mysql.database = 'mlmetadata'
connection_config.mysql.user = 'root'
store = metadata_store.MetadataStore(connection_config)

store.get_artifacts()
```

Anyway neither environment variables ```MYSQL_SERVICE_HOST``` nor ```METADATA_DB_SERVICE_HOST``` were defined in the notebook environment.

What is the good practice for connecting the metadata database?

**Comment by jessiezcc** [comment]
@gaoning777, can you provide instructions and identify what doc update needs to be done as well?

**Comment by SinaChavoshi** [comment]
@mesaverde0207 sorry for the delayed response. This is an issue resulting from the KF 6.2 names space feature release. 

Jupyter notebook development environment is running under your user namespace  (ex. kubeflow-yfukuda) which does not have access to the mysql service that is running under Kubeflow namespace. 

a quick work around for this issue is to run the metadata artifact retrieval code as a pipeline step, which will execute in the same namespace. 

Ex: 
`import kfp
from kfp.components import InputPath, InputTextFile, InputBinaryFile, OutputPath, OutputTextFile, OutputBinaryFile
from kfp.components import func_to_container_op

@func_to_container_op
def print_mysql_env_var():
    import subprocess
    subprocess.call(['pip', 'install', '--upgrade', 'ml_metadata'])
    from ml_metadata.metadata_store import metadata_store
    from ml_metadata.proto import metadata_store_pb2
    import os
    connection_config = metadata_store_pb2.ConnectionConfig()
    connection_config.mysql.host = os.getenv('MYSQL_SERVICE_HOST')
    connection_config.mysql.port = int(os.getenv('MYSQL_SERVICE_PORT'))
    connection_config.mysql.database = 'mlmetadata'
    connection_config.mysql.user = 'root'
    store = metadata_store.MetadataStore(connection_config)
    store.get_artifacts()
    store.get_artifacts_by_type('ExamplesPath')
    

def constant_to_consumer_pipeline():
    consume_task = print_mysql_env_var() # Passing constant as argument to consumer

kfp.Client().create_run_from_pipeline_func(constant_to_consumer_pipeline, arguments={},)`

**Comment by jlewi** [comment]
@SinaChavoshi the metadata service should be accessible from the Kubeflow user namespace. If you look at the demo notebook
https://github.com/kubeflow/examples/blob/master/xgboost_synthetic/build-train-deploy.ipynb

That is using the metadata client library to successfully log metrics in the database. It looks like this code is trying to contact the metadata store API directly that should work.

It looks like the problem is that the code in the notebook is relying on the environment variables for the metadata service to be set on the pod.

This is brittle because there's any number of reasons why K8s might not correctly set environment variables corresponding to pod.

I believe the correct solution here is to use the proper DNS name for the service and not rely on the environment variables to be set.

See: 
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

**Comment by gaoning777** [comment]
Agreed with Jeremy's point. Relying on the environment variables for the metadata DNS is not good practice. I suggest configuring the proper DNS name and give it another try.
Thanks.

**Comment by gaoning777** [comment]
Feel free to reopen this issue if configuring the proper DNS does not solve the problem.
