### ISSUE TITLE
Back-button not working when creating a run from a notebook

### ISSUE THREAD

**Issue by vicaire** [kubeflow/pipelines#221]
![screenshot from 2018-11-12 15-44-33](https://user-images.githubusercontent.com/25757005/48381676-f29fb780-e691-11e8-99a8-e504a2233536.png)

**Comment by vicaire** [comment]
On the screen shot above, I press the back button and nothing happens. 

This run was created from a notebook.

**Comment by rileyjbauer** [comment]
No console errors. The issue is that we're landing directly on that page, with no history.

In this case, the back arrow should either not exist, or take the user back to the `ExperimentDetails` page. Both will result in behavior that is not quite the same as what one would encounter if working solely through the UI

**Comment by yebrahim** [comment]
Yes, this is why we have this comment here: https://github.com/kubeflow/pipelines/blob/4550513ed0684137ad538302e8ec26b7c907e8ed/frontend/src/components/Toolbar.tsx#L139.

I've noticed GCP console disables the button in this case. I don't like this but I guess it makes most sense if the button is just browser back.

**Comment by vicaire** [comment]
My expectation for this one would be for the back arrow (which I am used to) to be present and to take me back to the experiment. WDYT?

**Comment by yebrahim** [comment]
After debating this for a while, we thought the best course of action is browser back, which is least controversial/confusing, and used by GCP console. We just need to workaround this corner case.

**Comment by ajayalfred** [comment]
Can you default to whatever is the last link in the breadcrumb? Anytime browser history is absent and you have to display a back button, make it link to the last link in the breadcrumb above.

**Comment by rileyjbauer** [comment]
We could do that, but note that would lead to a weird situation in the case described by you and Pascal where you start on the run page, go back up to the experiment page, and then go back to the run page, and just bounce back and forth between them if you keep clicking the back arrow.

**Comment by ajayalfred** [comment]
Oh wow, yeah that's a good catch. So this hack would work from the experiment details page but not the run details page.
I guess the best course of action is to display the button but disable it. That way a user can still use breadcrumbs to navigate around, and reenable the button when there's browser history.
Do you have any other solutions?

**Comment by yebrahim** [comment]
Yup, that's the reason GCP disables it.
The other solution is to take it out completely.

**Comment by vicaire** [comment]
As a user, my expectation is that the behavior of the back arrow (if wee keep it) is consistent and not the same as the browser back button. 

So if takes me once from the run page to the experiment page, I would expect it to always do this, no matter the history.

**Comment by ajayalfred** [comment]
In theory it sounds right that the back button take you up one level instead of browser back – however in our daily testing and usage, browser back is actually the most useful resolution for the need to go back. Because more than likely, a user is not always traversing the hierarchy to complete a task. When we add filtering, browser back becomes important to resubmit the filter string to see the same results again.

For this particular edge case (when no browser history is present), disabling the button sounds good.
