### ISSUE TITLE
library installed with VersionedDependency not accessible 

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#2252]
**What happened:**
Installed a dependency vi VersionedDependency
```
compiler.build_python_component(
component_func = test_comp,
staging_gcs_path = 'gs://chavsohi-dev-3-temp/pipelinestest/out',
base_image='gcr.io/deeplearning-platform-release/base-cpu',
target_component_file='component-test.yaml',
target_image = 'gcr.io/chavoshi-dev-3/component-test:latest',
dependency=[kfp.compiler.VersionedDependency(name='google-cloud-automl', version='0.5.0')],
namespace = None)
```
Image builds successfully, however when importing the library 
from google.cloud import automl_v1beta1

it errors out with 
ImportError: cannot import name 'automl_v1beta1' from 'google.cloud' (unknown location) 

running the docker image in interactive mode, confirmed the library google-cloud-automl==0.5.0
is installed however non of it's sub methods are accessible. 

verified in the docker image that the library has installed via:
root@5703ce77c688:/# pip3 freeze |grep automl
google-cloud-automl==0.5.0

**Comment by SinaChavoshi** [comment]
This issue seems to be limited to the deep learning containers ... it may be an issue with the way the deep learning docker images are constructed.

**Comment by jessiezcc** [comment]
@SinaChavoshi, do u suggest we add documentation for it? seems like there is not much we can do on pipeline to address the fundamental issue.

**Comment by ucdmkt** [comment]
Do we know if it is because of the way how PYTHONPATH is configured in the DL container? or is it because of the way how kfp.compiler.VersionedDependency(..) installs the package (e.g. .whl vs. pip vs. ...) ?

**Comment by Ark-kun** [comment]
I'm not sure this is related to VersionedDependency. It just adds pip install to the Dockerfile.

>from google.cloud import automl_v1beta1

Can you try `from google.cloud import automl` instead?

**Comment by Ark-kun** [comment]
@SinaChavoshi Let's investigate together. I'm pretty sure this issue is not related to KFP.

**Comment by Ark-kun** [comment]
We did an extensive investigation with @SinaChavoshi.
I found the root cause and it's pretty weird:
The DLVM container images use Miniconda python and the `python3` program uses the Miniconda environment. However the `pip3` program points to system's python environment.

So the packages installed using `pip3` are not available to `python3`.

We need to do the following:
1. Contact the DL VM team so that they can fix the issue with the image.
2. Work around the issue on our side.

The workaround for this problem would be to always use `python3 -m pip install` instead of `pip3 install`.

**Comment by Ark-kun** [comment]
Here is the PR which adds KFP-side workaround: https://github.com/kubeflow/pipelines/pull/2316
P.S. The new container-building API was not affected, since it used more robust commands by default:
https://github.com/kubeflow/pipelines/blob/ed285ce7683756a3962d4adbacb7801220565f90/sdk/python/kfp/containers/_build_image_api.py#L65
