### ISSUE TITLE
Increase pipeline input argument length/size

### ISSUE THREAD

**Issue by solovyevt** [kubeflow/pipelines#2286]
There is a limitation on backend server, which triggers when input argument reaches certain length:

`The pipeline spec is invalid.: Invalid input error: The input parameter length exceed maximum size of 10000."`

In some cases it might be necessary to provide large input arguments, when, for example, you got a highly configurable model or a very diversified dataset that requires detailed description.

Are there any practical limitations on input argument length and what's your opinion on increasing input argument length?

**Comment by Ark-kun** [comment]
There are size limitations imposed by Kubernetes. The workflow spec and state needs to be less than 512KiB (or maybe 1MiB). So while this limitation is artificial, there are some real limitations in the underlying platform.

There are now better ways to pass big data around. See this [Data passing tutorial](https://github.com/kubeflow/pipelines/blob/6a70faab12f91ad3eaf2398b9de2c5970d2aff92/samples/tutorials/Data%20passing%20in%20python%20components.ipynb) and tell me what you think.

**Comment by rmgogogo** [comment]
Feel free to reopen. We have ~300 issues, trying to close few for better management.

**Comment by Ark-kun** [comment]
>Feel free to reopen. We have ~300 issues, trying to close few for better management.

I feel that it makes it harder for me to track active issues and understand whether the issue is fixed or not.

**Comment by WalidMustapha** [comment]
We have a use-case affected by the size limitation. 

Essentially, we would like to be able to track input arguments to our model and data processing components when creating/reviewing pipeline runs. My understanding is that arguments to the component operators are only displayed in the Experiment UI if these are passed as pipeline arguments.

We have limited the individual arguments to the components to strings, small lists/dicts as suggested in  [Data passing tutorial](https://github.com/kubeflow/pipelines/blob/6a70faab12f91ad3eaf2398b9de2c5970d2aff92/samples/tutorials/Data%20passing%20in%20python%20components.ipynb) but the size of all arguments passed to `arguments` in `create_run_from_pipeline_func` exceeds the size limitation.

Passing files instead of arguments would defeat the purpose of the Experiment UI `Input Parameters` tracking.
