### ISSUE TITLE
namespace issue in v6.2

### ISSUE THREAD

**Issue by Katherinechenlove** [kubeflow/pipelines#2300]
**What happened:**
On Kubeflow UI page, pipelines are running under system namespace like while other modules are running under user namespace.

**Comment by SinaChavoshi** [comment]
Adding to details based on offline discussion with katherine, this is a side effect from 6.2 multi tenancy support 

Specifically when running the TFX pipeline example in a KF 6.2 in cluster notebook instance ( TFX example source -> https://github.com/kubeflow/pipelines/tree/master/samples/core/tfx-oss ) the user gets an error regarding access to mysql instance. This is since the Notebook executes under the user name space, the TFX sample assumes the name space for mysql is the same as current name space and is looking for the Mysql instance under user name space instead of Kubeflow name space. 

running the same pipeline for KFP UI works fine since it runs under Kubeflow name space.

**Comment by SinaChavoshi** [comment]
Duplicate of #2169

**Comment by Bobgy** [comment]
Please look at multi user namespace support issue.
