### ISSUE TITLE
Make run names unique

### ISSUE THREAD

**Issue by yebrahim** [kubeflow/pipelines#236]
@IronPan @rileyjbauer @vicaire @Ark-kun @ajayalfred 

Making run names unique is a better user experience, but it can complicate things when the user is trying to iterate on runs from a notebook, by changing code and rerunning the create run code cell. It would be good if the user doesn't have to change the run name every time.

To do this, we can add a "name-prefix" field in the new run API, in addition to the "name" field (only one must be specified). If the "name-prefix" field is specified, the backend will append some random string to the end of the name before creating the run. The UI can support this by adding a checkbox field to the create run flow (which won't show in the clone run flow, since that flow already adds a "clone(n)" suffix). This way, the backend can ensure the name is unique if a prefix is specified, and can throw an error if the name field is specified with a conflict.

Comments appreciated.

**Comment by ajayalfred** [comment]
Agree. Making run names unique will benefit the user experience in multiple ways:
1. In the 'All runs' list there will be no name collision when searching for a run by name. In the absence of user identity, unique names make it easier to identify individual user runs in a shared environment.
2. We can allow users to create runs without having to create an experiment (this feature must be assessed with users first)

With regard to the additional field, I understand the need for a 'name-prefix' when creating runs from NB (to allow quick consecutive submissions). Although we should test is assumption - this may actually not be a problem, users may in fact be comfortable with changing the name manually. So we should get feedback on this.

However, I don't understand the need to expose this field in the UI.
A user can create a run from the UI using the 'Start run' button at which time they will be asked to pick a unique name. For recurring runs, the same unique name constraint applies. For cloned runs, we'll add a '-clone(1)' suffix. What is the need for the checkbox then?

**Comment by yebrahim** [comment]
It can be frustrating to have an error saying the name already exists if this happens multiple times. Users can just check this box and have the name be guaranteed to be unique.

A separate point here: I think names should only be unique within a given experiment, since experiments are like folders basically.

**Comment by yebrahim** [comment]
The checkbox would be in the KFP UI, when creating a new run.

Runs can be differentiated using their experiment names, which show up in the run list, and which are unique.

If I'm working within my experiment in a shared cluster, I shouldn't have to worry about runs in someone else's experiment. This is one of the aspects of the "containment" relationship between experiments and runs.
After discussing with @IronPan, it seems it's as easy to implement both uniqueness constraints.

**Comment by Ark-kun** [comment]
> A separate point here: I think names should only be unique within a given experiment, since experiments are like folders basically.

I disagree with this. I'd like experiments to be a grouping subset of runs, with the ability to have a run in multiple experiments.

Example 1: I work on a new ranker set release inside an experiment/project. Once I'm done, I want to hand-off the final production runs to the person who's doing the next release, so that they can us those runs as a starting point.

Example 2: I work on a new ranker set release inside an experiment/project. I want to present a current state of several release candidates I currently have. I create a new experiments and add a small subset of runs to it.

**Comment by Ark-kun** [comment]
> If I'm working within my experiment in a shared cluster, I shouldn't have to worry about runs in someone else's experiment.

Totally agree with this.

And this is one of the reason I oppose the uniqueness constraints.

If there is no constraint and the user really wants the names to be unique the user can easily enforce this (e.g. in Notebook, the code can fetch the list of runs and generate a new name if the name is not unique).

But if there is a constraint and a problem arises, the user cannot work around it.

**Comment by Ark-kun** [comment]
The frustration when the user cannot do what they want almost always outweights a bit of confusion.

The unique names do not really prevent confusion. Just because `My run 6` and  `My run 7` are different strings does not mean they convey any useful information.

**Comment by ajayalfred** [comment]
@yebrahim – I still don't understand the need for a checkbox in KFP UI if a user is creating an experiment and starting runs from the Notebook. In this usecase, the user is never interacting with the 'Run create form' at all, unless I'm missing something? Let's chat about this in our weekly sync.

Regarding uniqueness of runs, I am certain users will not be concerned that there is a name collision with runs in other experiments and that they're expected to use a unique name. Avoiding name collision is a better user experience than allowing duplicate names. This is especially important BECAUSE we also show a view of all runs. Agree the user can disambiguate using experiment name – but if we can enforce unique run names (and it's technically simple) it'll reduce cognitive load on the user who has to disambiguate run names by experiment name. 

My recommendation for a simpler user experience with least cognitive load is to enforce unique run names across all experiments. This rule will give us flexibility to allow run creation without an experiment in the future, if it tests well with users.

**Comment by rileyjbauer** [comment]
For the record: #255

**Comment by ajayalfred** [comment]
I like the idea of auto-generating run names. Suppose we go down this road, what role does uniqueness play in auto-generated names? Does it feel like enforcing run name uniqueness will simplify other optimizations?

**Comment by yebrahim** [comment]
If a name is auto-generated, it should follow all rules such that it doesn't get rejected when the user submits the form. If we have uniqueness enforced, perhaps the name should end in a random string suffix.

**Comment by ajayalfred** [comment]
Ok. My recommendation is to enforce unique run names for 2 reasons:

1. Avoids name collisions in 'all runs' list. Reduces cognitive load as the user doesn't have to disambiguate by experiment name.
2. Unique run names will give us the flexibility to allow standalone run creation (without experiment)

To support this, we can add features to improve the experience of creating runs:
1. From UI start run form – auto-generate run names to avoid name collisions. Some combo of experiment/pipeline name.
2. For cloned runs – this is not an issue since we add '...clone (1)' at the end
3. From Notebooks – have some sort of name prefix. Add random string to run name when submitting the run. We can discuss why exposing this prefix in the UI is necessary in our weekly sync.

Sound good?

**Comment by yebrahim** [comment]
Let's discuss this in person, I don't think we can close on this here, and I don't understand the second reason.

**Comment by ajayalfred** [comment]
We discussed making run names unique and generally agree that it's valuable to keep them unique across the entire system (unique between experiments also). With auto-generated run names, this constraint will be satisfied. See #255

**Comment by vicaire** [comment]
Resolving since this discussion took place many months ago. Please re-open if needed.

**Comment by rileyjbauer** [comment]
Re-opening this because we agreed the names should be unique, but this has not yet been implemented. This issue should be the one to track that work

**Comment by neuromage** [comment]
Agreed, unique run names would be great. Also, wanted to quickly note that when we do enforce this, we need to figure out how to do this in a backward-compatible way now that pipelines data persists across upgrades.
