### ISSUE TITLE
[Frontend] upgrade node to 12 LTS

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#2386]
We are currently using node 9 in dockerfile, but 11 in travis CI. We should sync both to the same version.
Latest LTS node 12 should be the best option.

problem we met: https://github.com/kubeflow/pipelines/pull/2305#issuecomment-541890390

However, I don't think this is very urgent.

Our node server runtime is using node 9. We don't have unit tests for node server.
Client UI code run in the browser, so it doesn't matter. Client UI unit tests run in node 11, it's okay.

Having a single version of node will help clear some confusion, but doesn't solve any real problem. I think it's better to first write some basic unit test coverage for the node server before upgrading node.

Places with node version:
* [x] https://github.com/kubeflow/pipelines/blob/df41f3fb8b6cac66c7994f1fb56d87b8fba4cda7/frontend/Dockerfile#L1 https://github.com/kubeflow/pipelines/pull/2830
* [x] Unit test node version already changed to 12 when moving to prow. https://github.com/kubeflow/pipelines/pull/2637

**Comment by Bobgy** [comment]
/area front-end
[tech debt]

**Comment by Bobgy** [comment]
There's an error building frontend docker image related to grpc and node 9, but it goes away with node 12. I don't know why it builds normally during test and release. I think for this reason we should prioritize more on this.

/priority p1

**Comment by eterna2** [comment]
`There's an error building frontend docker image related to grpc and node 9, but it goes away with node 12. I don't know why it builds normally during test and release. I think for this reason we should prioritize more on this.`

Because the package-lock.json is not in sync with package.json.

None of the grpc packages are listed inside package-lock.json.

We should target to use `npm ci` for the Travis test as well as build steps to ensure the dependencies are frozen.

Cuz I noticed there are alot of implicit version dependencies that can fails anytime - i.e. if we use the versions specified in package-lock.json, the build will fail because there are quite a few bugs which are fixed in later versions of the dependencies. `npm install` default behavior is to install the latest semantic version (which fixed the bugs) rather than the ones specified in package-lock.json - hence we unknowingly fixed the bugs (implicit knowledge - aka. works but we don't know why)

**Comment by Bobgy** [comment]
@eterna2 thanks for the suggestions, I agree with we should use `npm ci` instead.
Created issue https://github.com/kubeflow/pipelines/issues/2452 to track this problem.

> None of the grpc packages are listed inside package-lock.json.
For this specific issue, I don't think that's the root cause. They are in https://github.com/kubeflow/pipelines/blob/master/frontend/src/generated/src/apis/metadata/package-lock.json#L203.
I'm not fully clear why it was put there. I guess the original intention was making that folder a separate package.

**Comment by Bobgy** [comment]
FYI, I found out the error when building docker image is caused by having node_modules in the working dir. If you delete all of them (like in CI environment), the build will pass.
