### ISSUE TITLE
displayed run name in UI sometimes toggles between two different runs

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#2590]
I've sometimes seen displayed pipeline run name switch between two different runs (the correct name and the name of another run) when the window is in focus.
Please don't ask me how to repro this :) but I thought I would record the evidence in case others hit this bug as well.
![gif_pl_run_names](https://user-images.githubusercontent.com/115093/68609191-83f26700-0469-11ea-97b4-a83872ff27ed.gif)

**Comment by wstian** [comment]
hit the same issue previously, and it's very dangerous when try to terminate the run, probably the other run is terminated.

As I remember, i guess maybe happen this way:

*   open the detail page of run A, waiting for the `get` request

*   then open the detail page of another run B, at this time the previous `get` request returned

**Comment by Bobgy** [comment]
I will investigate. Each run details page should be a separate instance. Let me double check.

/prority p0

**Comment by Bobgy** [comment]
Identified root cause.
Although each page is a separate instance, toolbar state isn't: https://github.com/kubeflow/pipelines/blob/e7c7c510b7663ad150dfa1c6d4a44d5a9ad424b0/frontend/src/components/Router.tsx#L135

Instead of fixing all potential dangling network requests, I want to first try if separating toolbar state to each page instance is appropriate. That will solve all future problems too.

**Comment by Bobgy** [comment]
Reproduction video: https://drive.google.com/file/d/1nRM5n6ZWRtHYu9LGBvmnt0C9qugeOfuo/view
