### ISSUE TITLE
BigQuery component doesn't allow empty GCSOutputPath 

### ISSUE THREAD

**Issue by parthmishra** [kubeflow/pipelines#2606]
**What happened:**
When attempting to run a query using the BigQuery component, omitting the `output_gcs_path` argument results in the query job working but the component fails due to reading an empty output file `bigquery/query-output-path.txt`.

**What did you expect to happen:**
`output_gcs_path` is listed as an optional argument and therefore not supplying it should be fine and the query results should simply go to the designation table and not be exported to GCS.

**Comment by Ark-kun** [comment]
Thank you for reporting the problem.
I've discovered and fixed this bug in the underlying Argo orchestrator: https://github.com/argoproj/argo/pull/1653 which is released as part of Argo v2.4.1.
Unfortunately we have not yet upgraded to that version.

As a short-term fix we should change the component so that it does not produce empty artifacts.

**Comment by Ark-kun** [comment]
Short-term fixed by https://github.com/kubeflow/pipelines/pull/3514
Properly fixed by https://github.com/kubeflow/pipelines/pull/3537
