### ISSUE TITLE
Check and fix visualizations

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#2670]
There are some reports that Visualizations do not show up at all.
We need to check and investigate that. that

P.S. There are also reports that people have hard time enabling custom visualizations.

**Comment by Bobgy** [comment]
Thanks for the report. I need some details to verify this.


> There are some reports that Visualizations do not show up at all.

Which deployment? Is there a repro pipeline?

> P.S. There are also reports that people have hard time enabling custom visualizations.

Any details? Where are they stuck at?

**Comment by Ark-kun** [comment]
@paveldournov has the details

**Comment by Bobgy** [comment]
I believe this should be
/priority p0

**Comment by Bobgy** [comment]
/assign @jingzhang36 
Can you update latest status on this issue?

**Comment by ConverJens** [comment]
@Bobgy @Ark-kun  I'm not sure what state this issue is in but I've been running a TFX pipeline on-prem  where the storage solution was to use the kfp.onprem.mount_pvc to mount a volume by specifying a PV and PVC. While this works well for executing the pipeline it also means that the visualization in the Artifacts tab under each pipeline component has the wrong storage path. I.e. the visualizations can't find the source data.

**Comment by Bobgy** [comment]
@ConverJens sorry, that's not supported yet.
