### ISSUE TITLE
Python visualization dev guide link is broken 

### ISSUE THREAD

**Issue by paveldournov** [kubeflow/pipelines#2675]
**What happened:**
Page: https://github.com/kubeflow/pipelines/blob/master/developer_guide.md#python-based-visualizations

<developer guide> link is broken and leads to a 404 error. The link is pointing to:
https://github.com/kubeflow/pipelines/blob/master/backend/src/apiserver/visualization/developer_guide.md

**What did you expect to happen:**
Link to the developer guide of the visualization components.

**Comment by rmgogogo** [comment]
correct link here:
https://github.com/kubeflow/pipelines/blob/master/backend/src/apiserver/visualization/README.md

**Comment by SuperKogito** [comment]
I think broken links are a common issue and a radical solution to this problem is automatically checking and reporting them. Luckily the new GitHub actions and  workflows help with that. I recently wrote an action that just does that. [URLs-checker](https://github.com/marketplace/actions/urls-checker) will check and report broken links, which is useful to spot similar issues to this one.

**Comment by rmgogogo** [comment]
Thanks SuperKogito!
I don't have permission to setup Action for this project. Let's wait after admin be back from vacation.
