### ISSUE TITLE
Warning: failed to retrieve pod logs. Possible reasons include cluster autoscaling or pod preemption

### ISSUE THREAD

**Issue by IreneGi** [kubeflow/pipelines#2705]
**What happened:**
Tried to renun taxi pipeline, clicked on Logs and got:
Warning: failed to retrieve pod logs. Possible reasons include cluster autoscaling or pod preemption
**What did you expect to happen:**
To see Logs
**What steps did you take:**
[A clear and concise description of what the bug is.]
Tried to renun taxi pipeline, clicked on Logs
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by neuromage** [comment]
@IreneGi would you mind attaching a screenshot as well? Thanks!

**Comment by numerology** [comment]
@IreneGi is this issue transient or persisting after several attempts? Thanks.

**Comment by IreneGi** [comment]
It is transient but frequent (I've hit it a few times in the last 24 hours)

**Comment by IreneGi** [comment]
![image](https://user-images.githubusercontent.com/6354284/70361747-75645900-1837-11ea-9619-f190142b20d9.png)

**Comment by rmgogogo** [comment]
as replied in b/145802412, here I close this one.

**Comment by mvk** [comment]
hi, @rmgogogo , what does `as replied in b/145802412` mean ?

**Comment by numerology** [comment]
> hi, @rmgogogo , what does `as replied in b/145802412` mean ?

Hi @mvk sorry it's a link to an internal doc. Anyway, this specific issue is supposed to be transient and GKE related.

**Comment by hsezhiyan** [comment]
@rmgogogo can you please post that reply in this thread so people can it directly?

**Comment by Bobgy** [comment]
The error message is expected, workflow's corresponding pods will be GCed after by default 1 day. Then you'll see this error message.

If on Google Cloud, you can still see the log in stackdriver.

**Comment by hsezhiyan** [comment]
@Bobgy make sense. However, sometimes I see the error `Failed to retrieve pod logs.` immediately after I create a run for only some pods in the pipeline (others are unaffected). Do you know what could be the error for this?

**Comment by numerology** [comment]
@hsezhiyan 

One thing might be helpful to confirm is to check the node status in the GKE node pool. If the pod is associated to an unhealthy node (e.g. undergoing maintenance/upgrading) then it'll be temporarily unavailable.

Do you see this symptom persisting or it's transient?

**Comment by hsezhiyan** [comment]
@numerology 

Thanks for your response! Actually, we don't use GKE, but we notice this symptom persists. For some reason, the affected pods are garbage collected but the healthy pods (which show healthy logs) are not. Any possible explanation for this behavior?

**Comment by numerology** [comment]
@hsezhiyan 

Ummmm... I think this is more of a K8S behavior which can be tricky to diagnose from a pipeline perspective. @Bobgy do you have some suggestion? Or did you configure the GC policy of your k8s? https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/

**Comment by hsezhiyan** [comment]
@neuromage 

Thanks again for the response. What I can say is that the `workflow` is not garbage collected, but certain `pods` within that workflow are...  I'll check our GC policy now

**Comment by hsezhiyan** [comment]
@neuromage 

I've noticed that in the `workflow`, the pods with failed logging are of `type: Retry` whereas the functioning pods are of `type: Pod`. It seems like the KFP UI is not getting the logs from the retried Pod.

**Comment by Bobgy** [comment]
https://github.com/kubeflow/pipelines/blob/22b7b99a8bff9278df4f7d051ffaca85837688e2/frontend/src/pages/RunDetails.tsx#L478

Yes, it might not be getting the correct retried pod.
PR welcomed

/Reopen

**Comment by eterna2** [comment]
@Bobgy 

I have investigated this and reported in #4425 

This is an UI bug. `Retry` nodes are not actual physical pods. Any ops with retry limits will always have a `Retry` node + one or more `Pod` nodes.

Hence `Retry` nodes will not have pod info and pod logs. It may or may not have additional metadata (like artifacts, input, outputs) but these will be exactly the same as the actual `Pod` node.

**Comment by lucinvitae** [comment]
Hello all,

Something like this issue (error: `Failed to retrieve pod logs.`) is frequently occurring for our cluster. We don't see `Possible reasons include cluster autoscaling or pod preemption` in the UI, but this typically happens for pipelines that depend on GPU nodes which are added to the cluster by our autoscaler.

We use S3 as a log backend, and can confirm that the logs are correctly populated in S3 despite the KFP UI error. So users of our KFP instance that don't know how to look up the log path directly in S3 will retry the run, since the user can't see the logs from the UI. Screenshots:

![Screen Shot 2021-06-16 at 2 49 14 PM](https://user-images.githubusercontent.com/61755432/122409513-31383580-cf51-11eb-91af-ccdc747a9b06.png)

This type of error occurs intermittently, and eventually affects all runs after the pods are cleaned up. It appears that the logs are correctly archived to S3 by Argo, and are accessible from the KFP UI before the Kubernetes pod is cleaned up, but after the Kubernetes pod is removed

We're using KFP (standalone) Version: 1.5.0

@Bobgy @eterna2 Do either of you know of a workaround so that we can have our KFP UI look up the logs in S3 even after the pod has been removed? Or, @Bobgy if you are looking for PRs to fix this, can you point me to the correct part of the codebase where we might be able to edit this logic and allow the KFP UI to use the S3 path that Argo archived the logs to?

cc @Jeffwan @PatrickXYS who [Bogby mentioned](https://github.com/kubeflow/pipelines/issues/4364#issuecomment-673245208) work for AWS and may be interested since this affects S3 integration.

Thanks in advance, all. 🙏

**Comment by speaknowpotato** [comment]
Hi @lucinvitae , 
our team also have the same issue, do you get it fixed?
thanks!

**Comment by lucinvitae** [comment]
> Hi @lucinvitae , our team also have the same issue, do you get it fixed? thanks!

@speaknowpotato I'm not sure, but I haven't seen this issue in a while.

**Comment by AlexandreBrown** [comment]
Hello, I got the same issue today running Kubeflow 1.4.1 on AWS.  
I fixed this issue by restarting the `ml-pipeline-ui` deployment in the `kubeflow` namespace.  
  
```shell  
kubectl rollout restart deployment/ml-pipeline-ui -n kubeflow
```  
  
Cheers!

**Comment by Luci1306** [comment]
> Hello, I got the same issue today running Kubeflow 1.4.1 on AWS. I fixed this issue by restarting the `ml-pipeline-ui` deployment in the `kubeflow` namespace.
> 
> ```shell
> kubectl rollout restart deployment/ml-pipeline-ui -n kubeflow
> ```
> 
> Cheers!

Perfectly worked, Thanks

**Comment by odovad** [comment]
> Hello, I got the same issue today running Kubeflow 1.4.1 on AWS. I fixed this issue by restarting the `ml-pipeline-ui` deployment in the `kubeflow` namespace.
> 
> ```shell
> kubectl rollout restart deployment/ml-pipeline-ui -n kubeflow
> ```
> 
> Cheers!

Same for me;  perfectly worked ! :)

**Comment by rimolive** [comment]
Closing this issue. No updates for a year.

/close
