### ISSUE TITLE
The frontend-integration-test is really flaky

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#272]
https://gubernator.k8s.io/builds/kubernetes-jenkins/pr-logs/directory/presubmit-e2e-test?

**Comment by Ark-kun** [comment]
The sample tests should not have any effect on the frontend tests, but there might be some relation.

**Comment by yebrahim** [comment]
They run in parallel, but this wasn't a consideration when building the frontend integration tests, that's why I think it's the culprit.

**Comment by gaoning777** [comment]
I checked all the failures and the majority of them failed due to two reasons:
1). cluster got deleted accidentally, it might've been accidentally deleted manually.
2). cannot create cluster due to computing/disk quota.
There is only one test failure due to "cannot connect to the docker daemon...".

I do not think it is related to the frontend integration tests.

**Comment by rileyjbauer** [comment]
Is this issue still affecting anyone?

**Comment by gaoning777** [comment]
Free feel to reopen if necessary.
