### ISSUE TITLE
extract string value of PipelineParam inside a pipeline

### ISSUE THREAD

**Issue by maggiemhanna** [kubeflow/pipelines#2725]
Hello, 

Extracting the string value of a PipelineParam (str(param.value)) always generates None. 

I would like to extract the string value of a PipelineParam inside a pipeline so that I can use it to rename my component.

Example:

@dsl.pipeline(name='my-pipeline')
def pipeline(loopidy_doop: dict = [{'a': "first", 'b': 2}, {'a': "second", 'b': 20}]):

    with dsl.ParallelFor(loopidy_doop) as item:
        op1 = dsl.ContainerOp(
            name="my-in-cop1",
            image="library/bash:4.4.23",
            command=["sh", "-c"],
            arguments=["echo no output global op1, item.b: %s" % item.b],
        ).set_display_name(str(item.a.value))

Is there a way kubeflow can support this kind of operations?

**Comment by numerology** [comment]
This is because at compile time the parameter itself does not have a value. Do you think it's a legit use case to support treating `item.a` as a string here @Ark-kun ?

**Comment by Ark-kun** [comment]
`PipelineParam` is a bit of an implementation detail. Users should treat it as opaque reference to some future data.

Nevertheless, even semantically the value cannot exist at the pipeline compilation time, since the value is only created during the pipeline execution.

P.S. `.set_display_name(str(item.a))` might actually work, although we are not supporting this.

**Comment by apeccaud** [comment]
Is there any other option to give a significant name to tasks in a loop?
