### ISSUE TITLE
No API interface found for python

### ISSUE THREAD

**Issue by liudonggang** [kubeflow/pipelines#2787]
Is it possible to provide a python version of the API interface?

**Comment by numerology** [comment]
Can you elaborate on what type(s) of the APIs you are looking for?

Currently we have the Python SDK client by which you can do some KFP operations [here](https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/_client.py)

**Comment by liudonggang** [comment]
I want to find a python API that describes kubeflow (the command is: kubectl describe wf -n kubelfow xxxx), is there an API for this?

**Comment by numerology** [comment]
KFP itself is not a workflow (rather I'll say it's a k8s app consisting of several components). Are you looking for a way to describe all the workflows running under kubeflow?

**Comment by liudonggang** [comment]
yes,Indeed as you said, I am looking for an API or tool that describes kubeflow

**Comment by numerology** [comment]
> yes,Indeed as you said, I am looking for an API or tool that describes kubeflow

Sorry I'm a bit of confused.

My point is that I don't think it's meaningful to describe kubeflow as a whole workflow because it's not monolithic.

Instead, if you're looking for a way to list all the running pipelines in your KFP deployment, there is indeed a Python API [here](https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/_client.py#L416)

**Comment by liudonggang** [comment]
I understand what you mean。

**Comment by liudonggang** [comment]
Thank you for taking the time to answer my doubts.

**Comment by numerology** [comment]
Happy to be helpful! @liudonggang
