### ISSUE TITLE
SDK: issue with pipeline arg static typing & default values

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#2825]
I'm creating a pipeline with a dict input parameter & am attempting to use the `Dict` type from `ksl.dsl.types`.

If I define the input like this (note double quotes): https://github.com/amygdala/pipelines/blob/automl_client_update/components/gcp/automl/create_dataset_for_tables/tables_pipeline.py#L49
```
  schema_info: Dict = {"end_station_id": "CATEGORY", "start_station_id": "CATEGORY", "loc_cross": "CATEGORY", "bike_id": "CATEGORY"},
```
...I see two problems.

First, when compiling the pipeline, I get this warning re: JsonObject: 
`UserWarning: Missing type name was inferred as "JsonObject" based on the value "{'end_station_id': 'CATEGORY', 'start_station_id': 'CATEGORY', 'loc_cross': 'CATEGORY', 'bike_id': 'CATEGORY'}".`

Am I using the wrong type?

Second, the default input param value has its **double quotes converted to single quotes** (as you can see in the error message above).
This is the way the default value is autofilled in the pipeline UI as well— single, not double quotes.
Unfortunately, the converted single-quote version causes an error when running the pipeline, I gather b/c the json is not valid:
`Automl set dataset schema: error: argument --schema-info: invalid loads value: "{'end_station_id': 'CATEGORY', 'start_station_id': 'CATEGORY', 'loc_cross': 'CATEGORY', 'bike_id': 'CATEGORY'}"`

In the UI, if I replace the generated single-quote default with my original double-quote version again (`{"end_station_id": "CATEGORY", "start_station_id":"CATEGORY", "loc_cross": "CATEGORY", "bike_id": "CATEGORY"}`) it all works fine.
Is there a way to prevent the conversion to single quotes/breakage?

**Comment by Ark-kun** [comment]
This is strange.

> the default input param value has its double quotes converted to single quotes 
At runtime, the quotes do not exist at all. As soon as python parses the test of your program, the quotes are forgotten and cannot be recovered.

I also believe that the serialization to "JsonObject" works correctly.

But the problem is most likely in the DSL compiler part that independently writes down the default values for pipeline inputs. AFAIK that part just uses `str` for "serialization", producing the single-quoted text you see. There is the same problem with passing arguments to the pipeline when creating a run.

As a short-term workaround, please use `json.dumps`to create the default value for your pipeline parameter.

**Comment by amygdala** [comment]
Just to note that the workaround (dumps --> string) works fine.
