### ISSUE TITLE
Why Python SDK is within pipelines repository? 

### ISSUE THREAD

**Issue by kelvins** [kubeflow/pipelines#2886]
Is there a reason for the Python SDK (`kfp`) be in the `pipelines` repository?
Wouldn't it be better to have it's own repository?

**Comment by numerology** [comment]
I think the reason is that, KFP SDK is coupled together with KFP deployment. KFP SDK is responsible to interpret the pipeline DSL into a pipeline spec that is understandable by the KFP deployment. That's why we bundle the release of SDK and pipeline system together. Typically, if the versions of KFP system and SDK mismatch with each other, it is very likely to hit some issues.

**Comment by kelvins** [comment]
Thanks for the answer @numerology, it makes sense.
I was just wondering if they could be splitted into two repositories and evolve independently (maybe it would be easier to contribute to the project), but I understand that changes in one "project" must be reflected in the other.

**Comment by numerology** [comment]
> I was just wondering if they could be splitted into two repositories and evolve independently.

Technically this is definitely feasible. However it requires a non-trivial addition to our current test-infra to make sure that the heads of two repos do not break each other. Meanwhile we'll need to update our releasing procedure to reflect the dependency b/w these two repos correctly.

I think putting them in one place makes things more manageable on our end during such fast iterations. Probably after it graduates and makes it to 1.0 era we can consider refactoring the project.

**Comment by rmgogogo** [comment]
question answered, here close
