### ISSUE TITLE
Failed saving large outputs when used with ParallelFor

### ISSUE THREAD

**Issue by yoni-taranis** [kubeflow/pipelines#2903]
**What happened:**
When trying to save large text files and using those outputs as an input for ParallelFor run the pod fails to save the with the error: **This step is in Error state with this message: failed to save outputs: Request entity too large: limit is ....**

**What did you expect to happen:**
Have the ParallelFor parse the text file as JSON array and iterate through it

**What steps did you take:**
I have tried several solutions, following some I have seen in other issues, including 
**https://nbviewer.jupyter.org/github/kubeflow/pipelines/blob/8dfa2d9/samples/tutorials/Data%20passing%20in%20python%20components.ipynb** all ended up with the same failed reason.

**Anything else you would like to add:**
Our main need is being able to receive chunks of data (right now: array of stringified objects), iterate them and run a pod(op) for each one of them using ParallelFor

Code example:
```
@dsl.pipeline(
    name='dummy-pipeline',
    description='Dummy',
)
def pipeline(url: str):
    array_of_data = DownloadFileToTextOp(url=url)
    with ParallelFor(array_of_data.outputs['text-artifact']) as item:
        op_1 = AnotherOp(...)
```

**will fail saving outputs**
**I have tried DownloadFileToTextOp using OutputFilePath, OutputFile and Artifacts.**

`array_of_data = DownloadFileToTextOp(url=images_data_url)`
**works just fine (I cannot see the actual outputs but there are no errors)**

**Comment by Ark-kun** [comment]
Unfortunately, this is currently impossible due to the way our underlying orchestrator (Argo) works.
Argo needs to get the data array, split it into items and then create a node for each item.
Argo cannot access the big artifact data that's uploaded to artifact storage, so it needs the pod to output the data as an "output parameter" and those are limited in size.

There is a hacky workaround where you use [recursive] loop to loop through data indices, then for each index you get the data element corresponding to the index and process that data. But I'm not sure this will make a difference in your case due to the Kubernetes limitations:

Generally, there is a Kubernetes-imposed limitation on the size of any object (including the Workflow object that contains the whole workflow and the status of all its nodes). I suspect you might hit this limit. If you have thousands of nodes, you'll probably hit it.

Can you give some more information on your scenarios, the number of data items and their sizes?

**Comment by yoni-taranis** [comment]
@Ark-kun Appreciate the reply!

Right now we have worked around this by limiting the data (ie. passing only the item ids without extra information) - of course I can think of several ways to hack this around but I would like our pipelines code be as straightforward as possible.

The main scenario I am trying to solve is - we have pipelines that should receive as input a set of item ids with some metadata about them (flags, etc), each item should go through a certain process (ie. inference), and when all of them are done, aggregate the results of all them to one pod, or call a certain callback url.

The number of items can go from 1000 to a few thousands (I don't think we will ever hit the 10k's), but if they carry a few metadata keys we hit the limit.

What would be a viable solution? Is there a plan to be able to execute any kind of code on the pipeline host machine? For example, I could have downloaded the data in one pod and zip it, etc...

**Comment by Ark-kun** [comment]
> The number of items can go from 1k to a few thousands (I don't think we will ever hit the 10k's in one pipeline, maybe for research purposes), but if they carry a few metadata keys we hit the limit.
> 
> What would be a good-practice solution for this?

Given the current state of Kubernets, a good option might be to batch the images and have less parallel tasks. This will also reduce the container starting overhead. Does this sound applicable to your scenario?

**Comment by yoni-taranis** [comment]
@Ark-kun Indeed that is what we have done right now to avoid this issue - Yes

If this if the current solution, and there is no way to deal with this limit without work arounds - you can close

Thanks!

**Comment by Ark-kun** [comment]
>If this if the current solution, and there is no way to deal with this limit without work arounds - you can close

Currently this is the best solution.

All workflow information including the workflow spec, execution node states, input and output artifact URIs, input and output parameter values etc needs to fit in <1MiB. Argo did some work to compress the workflow status, so when we upgrade to new version of Argo, it might fix your scenario. But for now, batching is the way to go.
