### ISSUE TITLE
example of string formatting PipelineParams?

### ISSUE THREAD

**Issue by JakeTheWise** [kubeflow/pipelines#2937]
The kubeflow pipelines documents (https://www.kubeflow.org/docs/pipelines/sdk/build-component/#create-a-python-function-to-wrap-your-component) states "Although the value of each dsl.PipelineParam is only available at run time, you can still use the parameters inline in the arguments by using %s variable substitution. At run time the argument contains the value of the parameter." But I can't seem to get this to work.

I'm trying to dynamically set my filepattern for training data inside a `ParallelFor`:
```python
@kfp.dsl.pipeline(name='...', description='Trains models for each well in parallel'
)
def parallel_trainer(
    utils_filepath: str,
    tfr_training_data_filepattern: str = 'gs://.../%s/*.tfr'
):
    with kfp.dsl.ParallelFor([{'a': 'a'}, {'a': 'b'}]) as items:
        my_op(tfr_training_data_filepattern % items.a)
```
and I get an error that `PipelineParam` is incompatible with `str`.

**Comment by Ark-kun** [comment]
At compile time, tfr_training_data_filepattern is PipelineParam. To be able to apply the `%` operator to it, it must be a string. You can convert it to string using `str`.

Please not that we're discouraging the conversion of PipelineParams to strings. It can lead to subtle issues like in this case.

This particular case won't work since `%` works at compile time (you're trying to make string substitution with two strings - the KFP SDK is not involved at all), but the value of `tfr_training_data_filepattern` will only be available at run time.
The solution is to make the substitution inside `my_op` or use concatenation instead of substitution.

**Comment by Ark-kun** [comment]
Generally, we like to think of components as boxes with input/output slots. Slots are connected with slots. All computations happen inside boxes.
So the substitution should be happening inside some component or not happening at all.
