### ISSUE TITLE
[Doc] Documentation about kfp generated api python sdk

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#3216]
There has been quite some pain for @jingzhang36 and me to figure out how to use generated sdk client. Also, many users clearly don't know how to use it either.

Related context
* https://github.com/kubeflow/pipelines/issues/2977#issuecomment-595011702
* https://github.com/kubeflow/pipelines/issues/3105
* https://github.com/kubeflow/pipelines/issues/3207

I wonder how we can improve it. Can we do the following?
* update https://kubeflow-pipelines.readthedocs.io/en/latest/index.html to include it
* add examples to kubeflow.org

**Comment by rmgogogo** [comment]
Joe, is https://kubeflow-pipelines.readthedocs.io/en/latest/index.html owned by us?
We had another thread on it, but no one replied it.

**Comment by Bobgy** [comment]
@rmgogogo I think it is generated from here https://github.com/kubeflow/pipelines/tree/master/docs.

@Ark-kun should know more about it.

**Comment by Bobgy** [comment]
@neuromage @Ark-kun I feel like this is a must have for KFP 1.0, also it would be the best if we can automate api spec doc generation and release regularly (in addition to some manually maintained examples).

What do you think? Can we add this into sdk/dsl group planning for Q2?

**Comment by neuromage** [comment]
@Bobgy Yes, this makes sense for Q2. Would you mind creating an issue and adding it to the KFP 1.0 planning Kanban? I'll sync up with @jessiezcc on resourcing this.
/cc @Ark-kun who may already know how to do this with existing tools.

**Comment by Bobgy** [comment]
Thanks @neuromage! I created https://github.com/kubeflow/pipelines/issues/3354 to track this.

**Comment by Ark-kun** [comment]
> Joe, is https://kubeflow-pipelines.readthedocs.io/en/latest/index.html owned by us?
> We had another thread on it, but no one replied it.

Sorry. I own that.

Without tweaks, sphinx does not know about the generated members of Client, because they do not exist on the Client class - only on objects. I can try to refactor the generation, so that it adds members to the class, not just the object. But that has some cons, since the generation will run during the import.

Maybe there is another way...

**Comment by Bobgy** [comment]
> Without tweaks, sphinx does not know about the generated members of Client, because they do not exist on the Client class - only on objects. I can try to refactor the generation, so that it adds members to the class, not just the object. But that has some cons, since the generation will run during the import.

I'm trying to understand, why is generation happening during import a con? When does it currently happen? at object init phase?

**Comment by Ark-kun** [comment]
> I'm trying to understand, why is generation happening during import a con? When does it currently happen? at object init phase?

Currently the generation happens during kfp.Client() init.
Usually the importing phase should be as small and fast as possible and have no complicated logic. Normally, if there is an error in some function, then only that function is broken. However if there is some error during the module level execution, then `import kfp` stops working which is significantly more serious. This could happen for example if some new version of `kfp-server-api` package is for some reason not compatible with older SDKs.

**Comment by Ark-kun** [comment]
I'm digging into sphinx. Maybe `autoattribute` or `autodata` can generate the documentation for a Client instance.

**Comment by Bobgy** [comment]
Thanks! makes sense to me. Would be great if doc can be supported with current approach.

**Comment by jnmclarty** [comment]
> Maybe there is another way...

I tried hacking on this a few different ways today.  Indeed, there would be draw-backs to call anything like the current implementation of `_add_generated_apis` on import.

I looked around the features, [events](https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx-core-events), [extensions](https://www.sphinx-doc.org/en/master/usage/extensions/index.html), autodoc directives of sphinx.  I even attempted [subclassing](https://www.sphinx-doc.org/en/stable/extdev/appapi.html?highlight=subclass#sphinx.application.Sphinx.add_autodocumenter) a `Documenter` (eg to create, for instance, `autoinstance:: kfp.client_instance`) to see what might be possible.

I think one approach worth considering would involve instantiating a `kfp.Client` during the build process for the docs and then telling sphinx explicitly, albeit dynamically, about the generated api.  

I have a solution which works, and generates an [expanded version of the docs](http://kfpdocs.jeffreymclarty.com/html/index.html).  Only snag, is I'm guessing my approach, isn't compatible with readthedocs.io.  

I'd send a PR tomorrow, or next weekend, if people are okay with instantiating a Client during the doc build. The doc builder would have to pass a host, I guess. (Or, there would need to be some refactoring of the constructor).

Since the kubeflow parent project has a registered domain and host, I'm guessing stuffing some extra static html somewhere, couldn't be too hard.

**Comment by Bobgy** [comment]
@jnmclarty Super thanks! This is a big step forward!

After reviewing the generated doc, there are still some usage frictions:
* Function description not very readable, it's hard to understand payload needs an ApiJob: http://kfpdocs.jeffreymclarty.com/html/source/kfp.client.html#kfp.Client.jobs.create_job
* Then looking at doc for ApiJob, it's hard to figure out what type each field is: http://kfpdocs.jeffreymclarty.com/html/source/kfp.client.html#kfp.Client.api_models.ApiJob

**Comment by Bobgy** [comment]
I've been searching if any solutions exist generating doc for swagger clients.

I tried https://github.com/swagger-api/swagger-codegen/issues/1387#issuecomment-347745959.

and got the following

**Comment by Ark-kun** [comment]
> I have a solution which works, and generates an [expanded version of the docs](http://kfpdocs.jeffreymclarty.com/html/index.html). Only snag, is I'm guessing my approach, isn't compatible with readthedocs.io.

>I'd send a PR tomorrow, or next weekend, if people are okay with instantiating a Client during the doc build. The doc builder would have to pass a host, I guess. (Or, there would need to be some refactoring of the constructor).

This looks great! Thanks for helping.
Did you eventually just generate the lists of methods using a script? (e.g. `  .. automethod:: kfp.Client.runs.list_runs`)

**Comment by Bobgy** [comment]
@Ark-kun Thanks! I can see new methods in the website now: https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.client.html#kfp-client-experiments

/reopen
to discuss further usability problems

Questions:
* Why does every method have a corresponding method with suffix `with_http_info`? Will users ever need it? e.g. delete_job_with_http_info(id, **kwargs)[source]
* Is there any way we can inject comment for each method so the long misleading comments can be removed?

**Comment by Ark-kun** [comment]
> * Why does every method have a corresponding method with suffix `with_http_info`? Will users ever need it? e.g. delete_job_with_http_info(id, **kwargs)[source]

That's how the API client in the generated `kfp-server-api`package looks like. Swagger codegen generates those methods.

> * Is there any way we can inject comment for each method so the long misleading comments can be removed?

The documentation reflects the generated `kfp-server-api` package. To change the documentation, the package needs to be changed.

P.S. The docs will look nicer once the swagger-codegen bug fix is merge https://github.com/swagger-api/swagger-codegen/pull/10259

**Comment by Bobgy** [comment]
/reopen
@Ark-kun Sorry, I'd want to keep this open until we have a usable end-to-end user journey for understanding how to use generated APIs.

e.g.
```
create_job(body, **kwargs)[source]
Create a new job. # noqa: E501

This method makes a synchronous HTTP request by default. To make an asynchronous HTTP request, please pass async_req=True >>> thread = api.create_job(body, async_req=True) >>> result = thread.get()

:param async_req bool :param ApiJob body: The job to be created (required) :return: ApiJob

If the method is called asynchronously, returns the request thread.
```
With current documentation, users can sort of find the body param should be of type ApiJob, but the documentation page doesn't have a reference to ApiJob.

`ApiJob` is also importable from users in the package, is it possible to include documentation for ApiJob there?

**Comment by Ark-kun** [comment]
>I'd want to keep this open until we have a usable end-to-end user journey for understanding how to use generated APIs.

I thought the main issue we were solving was discovery of the auto-generated API of the kfp-server-API package. I agree that we need better docs, but the documentation pages you're seeing just reflect the docstrings of the generated package. You can check that by using `help(kfp.Client().jobs.create_job)`

> With current documentation, users can sort of find the body param should be of type ApiJob, but the documentation page doesn't have a reference to ApiJob.

There would be a link if the parameter had a type annotation, but without the annotation it's not possible.

>ApiJob is also importable from users in the package, is it possible to include documentation for ApiJob there?

Yes, it's possible. Thank you for reminding. I forgot to include the models in the final version.
I'll include them.

I should probably add a separate page so that the kfp.Client page is not too long. 

In the future we can try upgrading from swagger-codegen to  https://github.com/OpenAPITools/openapi-generator which may generate nicer docstrings.

**Comment by Bobgy** [comment]
Thanks!
> There would be a link if the parameter had a type annotation, but without the annotation it's not possible.

No problem if we don't have the link now, just want to first make `ApiJob` searchable on that page.

**Comment by Bobgy** [comment]
Hi @Ark-kun, would you mind cherry picking your PR in https://github.com/OpenAPITools/openapi-generator/pull/6391 to our template folder here: https://github.com/kubeflow/pipelines/tree/master/backend/api/python_http_client_template

We can get the fix right away.
