### ISSUE TITLE
Post-submit standalone test fails since PR3209

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3244]
### What steps did you take:
Post-submit standalone test fails since PR3209

### What happened:
Post-submit standalone test fails since PR3209

### What did you expect to happen:
Back to normal

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 

KFP SDK version: 

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by numerology** [comment]
Took a look.

The cloud build failure right after PR3209 is due to "Connection broken". It seems like a transient issue. See https://pantheon.corp.google.com/cloud-build/builds/6125438b-e22f-44b7-8d29-4cc98924f5b4?project=ml-pipeline-test

However after that, cloud build complains 
`Your build failed to run: failed unmarshalling build config .cloudbuild.yaml: yaml: line 102: did not find expected key`

Investigating .cloudbuild.yaml

**Comment by numerology** [comment]
I see.... Wrong indentation in .cloudbuild.yaml.......

**Comment by rmgogogo** [comment]
oh, thanks Jiaxiao. Didn't expect you solve it so quick. I planned to solve it today.
