### ISSUE TITLE
Backend dependency cleanup - remove bazel

### ISSUE THREAD

**Issue by jingzhang36** [kubeflow/pipelines#3250]
Will help to reduce backend build time and easy dependency version bumping

**Comment by Bobgy** [comment]
All high priority tasks have been done.

Right now, bazel is only used to generate swagger json definitions from proto and that's a offline task.
Contributions welcomed on finishing the last step to remove bazel, but I believe it's not high priority because generated code are commited in the repo.

**Comment by Bobgy** [comment]
For the last issue, I just noticed we had a makefile for generating API swagger definitions from proto (before we used bazel):
https://github.com/kubeflow/pipelines/blob/2f3a686e545b671d3d1ce96bbcc07b18cb905a87/backend/api/Makefile

We may use it as a reference when migrating bazel based generation script back.

**Comment by Bobgy** [comment]
A quick recap of remaining issue:
* [ ] Remove bazel usage from https://github.com/kubeflow/pipelines/blob/master/backend/api/generate_api.sh

`jingzhang36` had an WIP PR for removing bazel from proto generation script: https://github.com/kubeflow/pipelines/pull/4393

but it went into the wrong direction, because we need the generated code checked in the repo, rather than during docker build step.

**Comment by Bobgy** [comment]
/cc @NikeNano 
this is the tracker issue for removing bazel, in case you didn't know it.

**Comment by NikeNano** [comment]
Since we have solved the last out standing point here I believe this can be removed. https://github.com/kubeflow/pipelines/issues/3250#issuecomment-744114178 @Bobgy

**Comment by Bobgy** [comment]
A long time headache is over : )

**Comment by NikeNano** [comment]
Succes :)
