### ISSUE TITLE
[Discussion] Backward compatibility promise?

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#3311]
In which areas should KFP officially promise backward compatibility since 1.0?

Listing a few areas we need to consider:
* KFP API spec: https://www.kubeflow.org/docs/pipelines/reference/api/kubeflow-pipeline-api-spec/
* SDK client (helper methods)
* DSL
* Component spec

**Comment by Ark-kun** [comment]
**ComponentSpec**
We definitely want to promise backwards compatibility for `ComponentSpec`.  https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/components/structures/components.json_schema.json

**DSL** 
DSL has some long-deprecated, but not yet removed parts. Nevertheless since the G.A. release in the fall of 2018 we did not have significant breaks, so the SDK API is pretty stable (although we my want to check fro any APIs that should not be public).
The only area I'm concerned about in SDK is ResourceOp, VolumeOp and the new PR that tries to add SuspendOp. Although the author of ResourceOp supports it, its a little bit more Argo or Kubernetes specific than the rest of the SDK.

**SDK client (helper methods)**
I think that some of them can be deprecated in favor of the generated APIs (kfp.Client().runs, kfp.Client().pipelines, etc).
I only ever use `create_run_from_pipeline_func` helper.

**Comment by Bobgy** [comment]
@jingzhang36 we need to figure out what we promise for KFP api

Shall we mark e.g. new features like versioning api as experimental and other parts are promised.
