### ISSUE TITLE
Support subdags for reusing pipelines

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#3345]
This will allow reusing a subset of the pipeline in other pipelines, similar to the function 
https://airflow.apache.org/docs/stable/concepts.html?highlight=subdag#subdags

**Comment by numerology** [comment]
This is very useful.

Also shall we consider how to make it sharable? For example we have component yaml spec today, should we have subdag yaml spec as well? @Ark-kun

**Comment by Ark-kun** [comment]
>@IronPan This will allow reusing a subset of the pipeline in other pipelines

>@numerology Also shall we consider how to make it sharable? For example we have component yaml spec today, should we have subdag yaml spec as well?

If I understood you correctly, the feature you ask for is already supported.
The feature is called "graph components".

Reuse has two aspects - creating and using.

The users can create a graph component from a [pipeline-like function](https://github.com/Ark-kun/pipelines/blob/master/sdk/python/tests/components/test_data/retail_product_stockout_prediction_pipeline.py) using [create_graph_component_from_pipeline_func](https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.components.html#kfp.components.create_graph_component_from_pipeline_func). This feature was added in v0.1.32: https://github.com/kubeflow/pipelines/pull/2273

The users can also write the spec manually. See [real e2e example](https://github.com/Ark-kun/pipelines/blob/master/sdk/python/tests/components/test_data/retail_product_stockout_prediction_pipeline.component.yaml). The specification and structures for the graph components have been present in KFP since the first G.A. release.

To use a graph component simply load it the same way as container components: using [load_component_from_url ](https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.components.html#kfp.components.load_component_from_url) or [load_component_from_file](https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.components.html#kfp.components.load_component_from_file). The user does not need to know whether the component is implemented as a single container or as a task graph.

Are there new clients that ask for this feature? (We can talk offline)
Are there any additional features that should be supported?
