### ISSUE TITLE
FUSE + GCS as K8s Volume to be used by KFP tasks

### ISSUE THREAD

**Issue by rmgogogo** [kubeflow/pipelines#3358]
### What did you expect to happen:
FUSE + GCS as K8s Volume to be used by KFP tasks.

Whether FUSE + GCS is suitable for production usage is to be investigated. Log a ticket as memo.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 

KFP SDK version: 

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Ark-kun** [comment]
This has been one of my KFP dreams and a target of research.
There are multiple strategies:
* Storage service pod exposing mounted GCS volume as NFS
* Mounting GCS bucket to all Kubernetes nodes using DaemonSet
* Mounting GCS bucket in an InitContainer and then sharing the mount point using the "Process Namespace Sharing" feature of Kubernetes (and Argo's pns executor).

Note that for this feature to be easy to use, the system should have a feature that provides help managing the data locations. Otherwise the user code might easily have data conflicts, overwrite each other's data etc. I've implemented this feature some time ago and now it's available as PR: https://github.com/kubeflow/pipelines/pull/3371. This feature will allow to easily (2 lines) switch an entire pipeline to use volume for artifact passing instead of Minio.

**Comment by Ark-kun** [comment]
I think the users will greatly benefit from this feature.

**Comment by rmgogogo** [comment]
"FUSE + GCS as K8s Volume": already be supported.
"used by KFP tasks": already be supported.

The concern is that other team mentioned FUSE is not suggested for production usage, although it can work.

Here close this ticket to treat it as done.

@Ark-kun SG?
