### ISSUE TITLE
Create a run of the newest pipeline version by default using Python SDK

### ISSUE THREAD

**Issue by jiyongjung0** [kubeflow/pipelines#3418]
### What steps did you take:
All actions were done using Python SDK (with TFX cli).
1. Created a pipeline 'A' with version name 'A' using `client.upload_pipeline()` API.
1. Created a pipeline version 'B' of pipeline 'A' using `client.pipeline_uploads.upload_pipeline_version()` API.
1. Created a run with `client.run_pipeline()` API. I used pipeline_id which was returned from 1 because pipeline_id is not changed even when a new version is uploaded.

### What happened:
1. A run of pipeline version 'A' of pipeline 'A' was created.

### What did you expect to happen:
1. A run of the most recent pipeline version('B') of pipeline 'A' is being created

### Environment:
GCP - Cloud AI Platform Pipelines. Installed from marketplace.

KFP version: 0.2.5
KFP SDK version: 0.3.0

### Anything else you would like to add:
When we select a pipeline from the web frontend UI, the most recent version is selected by default. So I thought that the most recent version of pipeline will be selected when I create a run using CLI.

/kind bug

**Comment by rmgogogo** [comment]
https://github.com/kubeflow/pipelines/pull/3339
Jing, would you review

**Comment by rmgogogo** [comment]
I thought it default should run latest version, in such case, Jiyong should not hit the issue, right?

**Comment by jiyongjung0** [comment]
Right. I expected that it will run latest version, but it didn't.

**Comment by rmgogogo** [comment]
I assume without the version_ID in the create_run, it should pick up latest version. Jing may didn't aware this ticket. Let me ping her via hangout.

Meanwhile, I think #3339 is OK to go as no conflict to allow execute a specific version.

**Comment by jingzhang36** [comment]
While creating run from pipeline version, we can use client.runs.create_run (instead of client.run_pipeline). The former is automatically synced to the backend api interface. 

When using client.runs.create_run, we use resource_references field to specify the pipeline version we want to use to create the run. Let me make an example for you and report back

**Comment by jingzhang36** [comment]
In addition to @pselden's PR of adding version support to run_pipeline method in SDK (https://github.com/kubeflow/pipelines/pull/3339) . We also make our backend more accommodating by translating the pipeline id to its default version if users still want to pipeline id to create run https://github.com/kubeflow/pipelines/pull/3437.

**Comment by Bobgy** [comment]
/close
looks like fixed by https://github.com/kubeflow/pipelines/pull/3437

**Comment by techjacker** [comment]
If  passing `pipeline_version` is the recommended way (rather than `pipeline_id`) to trigger pipeline runs then surely `pipeline_version` has to be unique? However, I do not see this documented anywhere.

I was planning on using the same `pipeline_version` for multiple pipelines so would be good to get clarification on this.

I was planning on setting `pipeline_version="${PIPELINE_NAME}-${GIT_SHA}"`. Good approach do you think?
