### ISSUE TITLE
Cache [MKP] - Switch the deployer to a Job for better behavior and cleanup

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3460]
We should switch the cache service deployer to a Job. Helm has explicit support for running pre-install hooks and will automatically wait for the job to complete and then delete the job and the deployer resources (job, service account, roles, rolebindings).
See https://helm.sh/docs/topics/charts_hooks/ and https://github.com/helm/charts/blob/edecc9842d1a63758c3bd0fc13a5d019e079f656/stable/prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml

**Comment by rmgogogo** [comment]
Do you mean change Cache-Deployer "kind" type to Job (it was on StatefulSet and then Deployment).

If the reason is more for HELM friendly, actually MKP didn't use HELM for installation but just use it as template engine.

For the pre-install hook, another better solution is to use K8s init continer.
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

I would leave it to Rui to decide whether change to init-container or not. I'm OK with both option as long it can work.

**Comment by Bobgy** [comment]
No matter what choice, I think standalone and MKP should use the same approach, otherwise maintenance and slightly different behaviors will be a disaster for future maintenance.

Can you clarify on `better behavior and cleanup`?

**Comment by Ark-kun** [comment]
No container (including the init containers) are started until all volumes are mounted.
In Kubernetes, Secret is a type of volume.
The cache service uses secrets.
The cache deployer creates secrets.

It might be problematic to use init containers for the deployer job.

**Comment by Ark-kun** [comment]
> Can you clarify on `better behavior and cleanup`?

In Kubernetes, some resources need to be deployed before other resources. For example, RoleBinding can only be deployed after the Role and ServiceAccount objects are deployed.
More importantly, RoleBinding objects must be fully deployed before any workload (Pod, Job, Deployment, StetefulSet) is deployed. Otherwise the deployed pods do not have the correct permissions. Kubernetes does not seem to handle this on its own (since Deployment/Pod does not specify any links to RoleBindings - only links to ServiceAccount).

>cleanup

There was a small upgrade issue previously - the deployer job object was not cleaned up after success, so the upgrade was failing when it tried to deploy the same job again.
Helm has explicit support for auto-deleting the pre-install jobs - https://github.com/helm/charts/blob/edecc9842d1a63758c3bd0fc13a5d019e079f656/stable/prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml#L9

**Comment by Ark-kun** [comment]
> If the reason is more for HELM friendly, actually MKP didn't use HELM for installation but just use it as template engine.

This is pretty important information. Can you please point me to the documentation about the installation method?

**Comment by Bobgy** [comment]
> > Can you clarify on `better behavior and cleanup`?
> 
> In Kubernetes, some resources need to be deployed before other resources. For example, RoleBinding can only be deployed after the Role and ServiceAccount objects are deployed.
> More importantly, RoleBinding objects must be fully deployed before any workload (Pod, Job, Deployment, StetefulSet) is deployed. Otherwise the deployed pods do not have the correct permissions. Kubernetes does not seem to handle this on its own (since Deployment/Pod does not specify any links to RoleBindings - only links to ServiceAccount).

When a deployment fails for the first time, it will automatically retry and all related sa, role, rolebinding should be ready after a few retries. Then it will run successfully. I think that's Kubernetes way for dealing with this.

This is expected behavior, many of our deployments may fail a few times before all other systems are running. I don't see a problem with it.

What is going wrong currently? Did something prevent above self-healing mechanism from taking effect?

> cleanup

So I believe there's no problem with using a deployment based on your explanation. Is that right?

**Comment by rui5i** [comment]
Job itself seems a good fit for cache deployer. But I still have some questions here:
1) Cache-deployer job may be deleted or generated a random name by helm hook in mkp to prevent upgrade issue. But I tried the helm hook before it didn't work. I am not sure if that is because in mkp we are not using helm? 
2) If helm hook works, I think we should go for the deletion option other than generate a random name because in standalone generateName does not work for kubectl apply. 
3) To make alignment of mkp and standalone, maybe another alternative way is in cache-deployer script, deleting the cache deployer Job after it finishes(self deletion). A small concern here is that it will lose all log info and it's hard to debug.

**Comment by Bobgy** [comment]
@Ark-kun @rui5i do you want to continue efforts on this? TBH, I'm not very convinced on benefits of a Job.

> To make alignment of mkp and standalone, maybe another alternative way is in cache-deployer script, deleting the cache deployer Job after it finishes(self deletion). A small concern here is that it will lose all log info and it's hard to debug.

and lack of self-healing may be problems
