### ISSUE TITLE
Using stable versions of Bazel for the backend build

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3461]
Bazel is already at v3.0.0, but the backend seems to require pretty old version of Bazel (v0.23).
It would be great if the backend would successfully build using the stable supported version of Bazel.

**Comment by Bobgy** [comment]
/cc @rmgogogo @jingzhang36 
I think we have an existing similar issue. Do you have any ideas?

**Comment by Ark-kun** [comment]
Related: https://github.com/kubeflow/pipelines/issues/3061

**Comment by Ark-kun** [comment]
I've tried to upgrade the build rulez, bazel and gazelle. After fixing some issues, I think we'll also need to update the Kubernetes repositories and modules.

**Comment by Ark-kun** [comment]
This is the branch where I tried to update the workplace: https://github.com/Ark-kun/pipelines/commits/Backend---Updated-BUILD-files-using-gazelle

**Comment by animeshsingh** [comment]
@Ark-kun is there any other Bazel expert on KFP team side ? Having a harder time finding experts on our side, given bazel is very specific to Google - and it seems the current version being very old is blocking us to use Tekton Go modules, as @Tomcli outlined

**Comment by Ark-kun** [comment]
KFP Backend build was converted to Bazel by @neuromage . I've assigned him to this issue.

**Comment by animeshsingh** [comment]
Thanks @Ark-kun 

@neuromage please see if you can get this unblocked at your end

**Comment by neuromage** [comment]
/assign @Ark-kun 

Unfortunately, I don't have cycles to look into this right now. Alexey, since you've already been looking into this, can you try and update our Bazel version and WORKSPACE files?

@animeshsingh @Tomcli we're happy to accept PRs here as well. Bazel is open sourced, and our knowledge is based around OSS-ed documentation, so there's no real advantage here. If there is a configuration that works to unblock your use-case for Tekton modules, we'd be happy to accept the change. Thanks!

/cc @jessiezcc 
/cc @paveldournov

**Comment by neuromage** [comment]
@Ark-kun  I took a look at the code again, and it looks like Bazel is no longer required to build API server, since @dushyanthsc removed the MLMD dependency we previously had. I think you can make this a lot simpler by upgrading Bazel to just work for building the protos, and remove it from all other places. Since there is no longer a need to build the C++ dependency anymore, you can just use native Go for all other places in the backend. 

/cc @IronPan 
/cc @rmgogogo 
to see if they have any objections to this plan.

**Comment by rmgogogo** [comment]
> @Ark-kun I took a look at the code again, and it looks like Bazel is no longer required to build API server, since @dushyanthsc removed the MLMD dependency we previously had. I think you can make this a lot simpler by upgrading Bazel to just work for building the protos, and remove it from all other places. Since there is no longer a need to build the C++ dependency anymore, you can just use native Go for all other places in the backend.
> 
> /cc @IronPan
> /cc @rmgogogo
> to see if they have any objections to this plan.

No problem. The major unblocker is removing the TensorFlow WORKSPACE dependency which is already be done before.

**Comment by rmgogogo** [comment]
@Bobgy as talked offline, we may remove Bazel, but use go mod for BE.

**Comment by Bobgy** [comment]
We've removed bazel, now we can close this
