### ISSUE TITLE
SDK: outputs appear to be getting truncated, at least when used in conditional tests

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#3596]
Using KFP 0.4.

I believe that this is new-ish behaviour.

I have a component that returns a string `'deploy'` as output under certain circs, otherwise returns `'False'.`  (it used to return True & False, but the boolean handling also broke recently for some reason [probably needs a separate bug], then in the process of debugging that, I switched to returning strings.)

The component function specifies:
`) -> NamedTuple('Outputs', [('deploy', str)]):`
(I also tried using `'String'` instead of `str` and got the same behaviour).

So the component function does a `return 'deploy'`.
Then in a pipeline that uses that component, I have (well, _had_) this conditional check:
`  with dsl.Condition(eval_metrics.outputs['deploy'] == 'deploy'):`

That no longer works.  It's only grabbing the 'd' part of the output string, apparently (?)
I now have to write my conditional like this:
`  with dsl.Condition(eval_metrics.outputs['deploy'] == 'd'):`

If I do not do the above, and instead use 
`  with dsl.Condition(eval_metrics.outputs['deploy'] == 'deploy'):`
I see:
![image](https://user-images.githubusercontent.com/115093/80136960-53a20f00-8557-11ea-8339-8ef3d6c26dfe.png)
clearly indicating that it's just using 'd' as the "output value".
If I rather compare the output to just `'d'`, things work as expected, with a return value of 'deploy' causing the conditional check to pass.

This should be pretty easy for you to repro.  (fwiw, [here's an example pipeline](https://gist.github.com/amygdala/d8ac7d42338c7f7efd4297ffaecb88dc) where I see the issue, and [here's the component function](https://github.com/amygdala/code-snippets/blob/master/ml/automl/tables/kfp_e2e/create_model_for_tables/tables_eval_metrics_component.py), but there might not be enough context for someone else to run this successfully.)

**Comment by amygdala** [comment]
meant to add... I have a number of pipelines where I'm having to change to use this new single-char condition check (else they don't work properly) but I'm worried that in the next sdk release that might break them again in the other direction? So let me know if that will be the case.

**Comment by Ark-kun** [comment]
>probably needs a separate bug

Please file the bug for this.

>So the component function does a return 'deploy'.

I think I understand what's happening. I'm really sorry for breaking you.

There was a change that fixed inconsistency of handling list outputs and single outputs (there was a bug that caused only the first element of a list being returned). Unfortunately the fix seems to have not quite intended consequences.

Here is the root cause: You've declared that the return of your component function is a NamedTuple. So the generated code treats the return value as a tuple (or a list). In python, string acts like a list of characters so only the first element is used for the first output.

To fix the issue you need to make your return declaration and return value consistent.

Either both should be strings:
```
def my_func() -> str:
    return "deploy"
```
or both should be tuples (lists/sequences/...)
```
def my_func() -> NamedTuple('Outputs', [('deploy', str)]):
    return ("deploy",) # 1-tuple
   # or
    return ["deploy"]) # list
    return namedtuple('Outputs', ['deploy'])("deploy"]) # namedtuple
    return NamedTuple('Outputs', [('deploy', str)])("deploy"]) # NamedTuple
```

I can try to make a hack in the SDK, so that your code starts working again. I agree that the outcome looks confusing. I was also confused at times when `isinstance("deploy", list) == true`.

**Comment by amygdala** [comment]
great, got it... returning a tuple works, and I'm happy to make changes to my code to fix it. 
I believe my earlier issue related to returning a boolean was the same thing (I can't remember the exact error, but the gist was that it was trying to index in to the boolean, similar to the error it would now get with an int).

From memory, we might need to update the documentation to reflect this change.  (I haven't checked to confirm).
/cc @joeliedtke

**Comment by Bobgy** [comment]
@joeliedtke @Ark-kun Do we need to update documentation? or can we close this?
