### ISSUE TITLE
Component/Pipeline code organization for e2e testing / Specifying e2e tests using notebooks. 

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#360]
We lack the story for testing and debugging components.
Current situation:
1) Unit Test: users can call the component python function in the notebook if only the server has the dependency installed.(option: installing the dependencies directly in the server, however, this might affect other notebooks that are running in the same notebook server).
2) Integration tests: users can submit a whole pipeline with the authored component. However, this requires the user to author an extra pipeline just to test this single component.

**Comment by vicaire** [comment]
Would it be possible to come up with a structure so that for each component: 
- There is a directory
- There is notebook that demonstrates how to use the component in that directory. 
- The notebook also provides the documentation. 
- The notebook also provides tests. 
- The notebook is automatically run by the test infrastructure.

**Comment by gaoning777** [comment]
@vicaire I created this issue to standardize the testing for components. Are you requesting that we should support a notebook sample tests and have the test infra support it?

**Comment by gaoning777** [comment]
We already support the notebook sample tests. Standardizing the component tests will be part of the component template efforts.
