### ISSUE TITLE
AWS Sagemaker Components : Add unit tests and integration tests 

### ISSUE THREAD

**Issue by akartsky** [kubeflow/pipelines#3631]
1] Add unit tests for all the components 
2] Add integration tests for all the components

**Comment by surajkota** [comment]
target is to create a test setup using pytest to maintain code quality and prevent regressions in kubeflow pipeline components for sagemaker which are in this [directory](https://github.com/kubeflow/pipelines/tree/master/components/aws/sagemaker)

The tests will not run as part of PR builds in this repository since an AWS account is needed for the jobs to run on Sagemaker. Tests will be accompanied with a README which can be used to run them manually

**Comment by Jeffwan** [comment]
Sounds like a good plan.  

How do you plan to run integration tests?

**Comment by surajkota** [comment]
Created a sample [PR](https://github.com/kubeflow/pipelines/pull/3654) as proof of concept with a pytest based testing framework using KFP SDK to answer this question.

Could please take a look and provide feedback?

**Comment by surajkota** [comment]
changes have been merged. tests are here: https://github.com/kubeflow/pipelines/tree/master/components/aws/sagemaker/tests

this issue can be closed
