### ISSUE TITLE
Behavior of InputArgumentPath vs PipelineParam

### ISSUE THREAD

**Issue by allenc97** [kubeflow/pipelines#3685]
### What steps did you take:
[A clear and concise description of what the bug is.]

Consider the following as a pipeline:
```
    produce_op = dsl.ContainerOp(
        name="produce",
        image='alpine',
        command=['/bin/sh', '-c'],
        arguments=[f"""
            mkdir -p /training_csvs/; \
            echo "Head Training CSV"; \
            echo "ImgUrl,ProductId,xmin,ymin,xmax,ymax" >> /training_csvs/train.csv; \
            echo "http://abc.com/123,1234,0.4598064,0.25266839999999996,0.5676966999999999,0.4289054" \
                >> /training_csvs/train.csv; \
            cat /training_csvs/train.csv; \
        """],
        file_outputs={
            'csvs': '/training_csvs/train.csv'
        }
    )

    test_op = dsl.ContainerOp(
        name='consumer',
        image='alpine',
        command=['cat'],
        arguments=[
            produce_op.outputs['csvs']
        ]
    )
```
For test_op, rather I pass in ```produce_op.outputs['csvs']``` or 
``` "%s" % produce_op.outputs['csvs']```, the compiled result becomes 
``` args: ['{{inputs.parameters.produce-csvs}}']```.

However, if I instead wrap with InputArgumentPath, like ```dsl.InputArgumentPath(produce_op.outputs['csvs'])``` vs. 
```"%s" % dsl.InputArgumentPath(produce_op.outputs['csvs'])```,  I will respectively get ``` args: [/tmp/inputs/input-0/data]```, where input-0/data represents the path and not data, verses ```args: [<kfp.dsl._container_op.InputArgumentPath object at 0x1263fea50>]```, which is not the intended result.

### What happened:
When wrapped as InputArgumentPath, you no longer get the same behavior, unlike for PipelineParam, where you can both use it as a serialized string or actual PipelineParam.

### What did you expect to happen:
I expected the same behavior as PipelineParam. This small difference defines rather I need to store results using a PVC, or simply get the object through the path with copying taken care of.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

Deployed on GKE cluster
KFP version: 
743746b
KFP SDK version: 
0.5.0

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by allenc97** [comment]
PS, the same behavior will happen for fstrings.

**Comment by Ark-kun** [comment]
We really discourage converting `PipelineParam` to a string and for `InputArgumentPath` this is unsupported.
Can you avoid doing that?
Should we throw an error when people try to convert `InputArgumentPath` to string?

**Comment by allenc97** [comment]
Note that the official docs, I.e https://www.kubeflow.org/docs/pipelines/sdk/build-component/#create-a-python-class-for-your-component, says the following:
```
Although the value of each dsl.PipelineParam is only available at run time, you can still use the parameters inline in the arguments by using %s variable substitution. At run time the argument contains the value of the parameter.
```
I actually have no issue with not using it as a string. It would just be nice if the behavior is consistent, and that the documentation should reflect that stringifying ```PipelineParam``` is discouraged. Throwing an error in before the pipeline is ran is probably the right way to go.

**Comment by Ark-kun** [comment]
Sounds good. We'll try improving the documentation.

P.S. We'd also like users to create proper reusable components (component.yaml) instead of creating instances of `ContainerOp` directly. And also to use systemgenerated paths instead of hard-coding them in the component code (this will prevent compatibility problems in the future).

Just create a `component.yaml` file with the following content:
```yaml
name: produce
outputs:
- name: training_data
implementation:
  container:
    image: alpine
    command:
    - /bin/sh
    - -c
    - |
      mkdir -p "$(dirname "$0")"
      echo "Head Training CSV"
      echo "ImgUrl,ProductId,xmin,ymin,xmax,ymax" >>"$0"
      echo "http://abc.com/123,1234,0.4598064,0.25266839999999996,0.5676966999999999,0.4289054" >>"$0"
      cat "$0"
    - {outputPath: training_data}
```

And then load it and use in the pipeline:

```python
from kfp.components import load_component_from_file

produce_op = load_component_from_file('component.yaml')

def my_pipeline():
    produce_task = produce_op()
    # train_op(training_data=produce_task.outputs['training_data'])

kfp.Client().create_run_from_pipeline_func(my_pipeline, arguments={})
```

There are also load_component_from_uri and load_component_from_text loading functions.

You might find this tutorial useful: https://github.com/Ark-kun/kfp_samples/blob/master/2019-10%20Kubeflow%20summit/106%20-%20Creating%20components%20from%20command-line%20programs/106%20-%20Creating%20components%20from%20command-line%20programs.ipynb

**Comment by allenc97** [comment]
Ok. In this case, is there a way to transform say ContainerOps or other supported ops into their yaml formats? One of the biggest reasons our company wants to use Kubeflow is so different data scientists can build reusable pipelines without having to learn much new material. (I.e do everything in python). 

It appears to me that there are a lot of functions that exist that you'd prefer users not to use, or instead to use their higher level abstractions.

**Comment by Ark-kun** [comment]
> In this case, is there a way to transform say ContainerOps or other supported ops into their yaml formats?

When the components are instantiated, they become ContainerOp objects.
But it's pretty hard to do an automatic conversion in the other direction due to information loss (e.g. the information about the inputs is lost as some of them are even inlined).

Writing component.yaml files should be pretty easy (see the end of my comment) and might be even easier than dealing with ContainerOp.

>It appears to me that there are a lot of functions that exist that you'd prefer users not to use, or instead to use their higher level abstractions.

That's true. We had retained backwards compatibility for a pretty long time, but the price for that is that older and lower-level abstractions are still available (and the documentation is not always updated).

Generally, you only need 2-3 functions to build and run pipelines:

* Load components: [load_component_from_url](https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.components.html#kfp.components.load_component_from_url) (or [load_component_from_file](https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.components.html#kfp.components.load_component_from_file) or [load_component_from_text](https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.components.html#kfp.components.load_component_from_text))
* Create python components: [create_component_from_func](https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.components.html#kfp.components.create_component_from_func) == [func_to_container_op](https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.components.html#kfp.components.func_to_container_op)
* Run pipeline: kfp.Client().[create_run_from_pipeline_func](https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.client.html#kfp.Client.create_run_from_pipeline_func)

>One of the biggest reasons our company wants to use Kubeflow is so different data scientists can build reusable pipelines without having to learn much new material. (I.e do everything in python).

We're trying to make KFP component-centric. Components can be authored by writing component.yaml files describing containerized command-line programs. We also have a "shortcut" that can generate a component[.yaml] for you from a self-contained python function (often you do not even need to build a new container image). The data scientists can use `create_component_from_func(my_func, output_component_file='my.component.yaml', ...)` to create reusable components that can be shared between different pipelines and people.

These docs and tutorials should help:

* https://www.kubeflow.org/docs/pipelines/sdk/component-development/
* https://www.kubeflow.org/docs/pipelines/sdk/lightweight-python-components/
* [Data passing in python components](https://github.com/kubeflow/pipelines/blob/master/samples/tutorials/Data%20passing%20in%20python%20components.ipynb)
* [Creating components from command-line programs](https://github.com/Ark-kun/kfp_samples/blob/master/2019-10%20Kubeflow%20summit/106%20-%20Creating%20components%20from%20command-line%20programs/106%20-%20Creating%20components%20from%20command-line%20programs.ipynb)

**Comment by allenc97** [comment]
Ok. Is there anywhere I can find a roadmap for the future development plans? (I.e what new support is coming in, when certain deprecations will hit)
