### ISSUE TITLE
New runs' details page always loading

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#3763]
### What steps did you take:
* Deploy a KFP cluster
* Wait for a long time (likely something that happened in this period is required, e.g. upgrading cluster kubernetes version)

### What happened:
Sometimes, after a job is submitted and successfully executed, the KFP UI fails to display run details (empty page with a spinning wheel) via the url: https://${CLUSTER_URI}/_/pipeline/?ns=keshi#/runs/details/${RUN_ID} for every new run.

Additionally, the problem is that kfp db doesn't have those information, because persistence agent stopped syncing new workflows.
One thing strange is that, when looking at persistence agent logs, it still loops properly listing all the old workflows, but it no longer detect newly created workflows.

### What did you expect to happen:
PA should keep syncing workflows.

### Environment:
How did you deploy Kubeflow Pipelines (KFP)?

Kubeflow deployment

KFP version: 
I don't remember clearly, but I think I've seen the issue in rare occasions from 0.2.0 to 0.5.0.

/kind bug

**Comment by Bobgy** [comment]
/assign @Bobgy 
/cc @IronPan @jingzhang36 
Record a known issue here.

**Comment by Bobgy** [comment]
Workaround: run `kubectl delete pod ml-pipeline-persistenceagent-xxxxxxx-xxxx -n kubeflow` to restart persistence agent.

**Comment by Bobgy** [comment]
I'm thinking even if we couldn't fix the issue directly, adding a liveness probe to persistence agent would be the best. However, persistence agent doesn't just hang, it keeps working properly just without getting new information.

If there are any ideas we can implement a liveness probe for this situation that would be awesome.

**Comment by Bobgy** [comment]
1 extra data point: we got one more external report about this

**Comment by rmgogogo** [comment]
Copy notes here:

"One thing strange is that, when looking at persistence agent logs, it still loops properly listing all the old workflows, but it no longer detect newly created workflows."

"it happens after reschedule pod to another node-pool"

**Comment by Bobgy** [comment]
The other report is different from root cause of this one.
Making a summary here first:
* The symptom: "new runs' details page always empty" means persistence agent is not syncing workflows to KFP db.
* The root cause can be various reasons.
  * The reason listed above is one possibility, it can be worked around by restarting persistence agent.
  * Another possibility is basically there are too many workflows in the cluster, that kubernetes api server starts to crash. In this case, the suggested fix is to set a shorter workflow TTL, so that total workflow count doesn't increase too much.

**Comment by jingzhang36** [comment]
A qq: does the empty detail page usually turn normal after a while? Or they stay empty?

**Comment by Bobgy** [comment]
@jingzhang36 No, it doesn't recover by itself.

**Comment by jingzhang36** [comment]
> @jingzhang36 No, it doesn't recover by itself.

Then, do you still have the instance where this issue happens?

**Comment by Bobgy** [comment]
I don't, I can ping you next time I reproduce it

**Comment by Bobgy** [comment]
I no longer see this happening any more

**Comment by daikeshi** [comment]
@Bobgy I'm curious if you have any updates on this issue. After we upgraded our cluster to KFP 1.3 and this issue seems to occur more often especially when the cluster is busy. When it happened, the run status was shown as unknown in the experiment page, and the run details page was empty and showed a spinning wheel.
![kfp_ui_issue](https://user-images.githubusercontent.com/475945/120727718-4456fa00-c4a9-11eb-8f72-54240d29ff99.png)

It can be fixed by deleting `ml-pipeline-persistenceagent` pod under `kubeflow` namespace. I also tried to increase resource configuration for `ml-pipeline-persistenceagent`. It seems to help (less frequent now) but it still can occur from time to time. Do you have more info regarding this issue? or is there anything that we can help look into?

**Comment by Bobgy** [comment]
@daikeshi I no longer see this issue after my last post here. My suspect is that this might have sth to do with controller runtime version.

Can you try upgrading persistent agent and see if there's any changes? (You can check changehistory to find out which version we upgraded controller runtime)

**Comment by daikeshi** [comment]
hmm, we are using `gcr.io/ml-pipeline/persistenceagent:1.3.0`. Are you referring to `controller-runtime` lib version [here](https://github.com/kubeflow/pipelines/blob/1.3.0/go.mod#L51)? It seems that it hasn't been changed since v1.3.0

**Comment by Bobgy** [comment]
Yes, I've got a wrong impression. There's a new pending PR that updates this lib and k8s client. That might help.

Based on my investigation, this seems a problem with the controller boilerplate code or the library.

**Comment by daikeshi** [comment]
@Bobgy that's awesome! Would you mind sharing the link to that new PR, so l keep an eye on it when it gets merged and released? Thank you!

**Comment by Bobgy** [comment]
Sure, it's https://github.com/kubeflow/pipelines/pull/5792

**Comment by kim-sardine** [comment]
I'm having the same issue. and solved it by deleting `ml-pipeline-persistenceagent`

when there was a problem, I found a log `Unknown node phase: undefined` in Chrom DevTool's console.
and it came from [Status.tsx](https://github.com/kubeflow/pipelines/blob/6f96e74bed2106129b7ad567d9cd8c2fe0d99455/frontend/src/pages/Status.tsx#L95) or [StatusUtils.ts](https://github.com/kubeflow/pipelines/blob/6f96e74bed2106129b7ad567d9cd8c2fe0d99455/frontend/src/lib/StatusUtils.ts#L88).

and I found that kubeflow pipeline's `getRun` api don't have `status` property in its response. 
(by accessing `ENDPOINT/pipeline/apis/v1beta1/runs/RUN_ID`)

**Comment by Bobgy** [comment]
Yes, it's expected that `status` property is empty when ml-pipeline-persistenceagent is stuck, because it stocks syncing status from argo workflow to KFP db.
The root cause is still about persistence agent. If there're insights in there, or if there are ideas to detect this problem and set it as liveness hook (when liveness hook fails, the server restarts), they will help a lot.

**Comment by kvamshi** [comment]
Deleting the ml-pipeline-persistenceagent is not helping. 
Our KFP version is 1.4.1, installed in GCP as part of AI Platform Pipelines

**Comment by kvamshi** [comment]
> 
@Bobgy How many is too many workflows ?. It is supposed to scale horizontally. So, what is the bottle next here.
Are you referring to running workflows or even the finished ones ?

**Comment by Bobgy** [comment]
cc @zijianjoy @chensun

**Comment by chensun** [comment]
> Deleting the ml-pipeline-persistenceagent is not helping. 
> Our KFP version is 1.4.1, installed in GCP as part of AI Platform Pipelines

Per https://github.com/kubeflow/pipelines/issues/3763#issuecomment-855257690, There was a fix (#5792) for this issue, which was released in 1.7.0. 
Can you please try upgrading your development and see if it helps?

**Comment by kvamshi** [comment]
We did. It helped. TY !!

**Comment by kvamshi** [comment]
It still is happening occasionally (not sure how often) in 1.7

**Comment by kvamshi** [comment]
Here are logs from kube-dns 

2022-02-03 02:16:49.025 PSTError while fetching metric descriptors for kubedns: googleapi: Error 503: The service is currently unavailable., backendError
Warning
2022-02-03 04:06:44.906 PSTpkg/mod/k8s.io/client-go@v0.19.12/tools/cache/reflector.go:156: watch of *v1.Service ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
Warning
2022-02-03 04:06:44.906 PSTpkg/mod/k8s.io/client-go@v0.19.12/tools/cache/reflector.go:156: watch of *v1.Endpoints ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
Warning
2022-02-03 04:06:54.844 PSTpkg/mod/k8s.io/client-go@v0.19.12/tools/cache/reflector.go:156: watch of *v1.Endpoints ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
Error
2022-02-03 04:06:54.844 PSTpkg/mod/k8s.io/client-go@v0.19.12/tools/cache/reflector.go:156: Failed to watch *v1.Service: Get "https://10.224.0.1:443/api/v1/services?allowWatchBookmarks=true&resourceVersion=2109172&timeoutSeconds=529&watch=true": http2: client connection lost

**Comment by thesuperzapper** [comment]
@Bobgy @james-jwu I found that "new runs" hanging is caused by network interruptions between Kubeflow Pipelines and the MySQL database, and still happens in the latest KFP versions.

That is, this issue always happens when you see errors like `[mysql] XXXX/XX/XX XX:XX:XX packets.go:36: unexpected EOF` in your `cache-server` and other pods, and goes away when the network issue is resolved.

See issues that user's are raising when they have database connection issues:

- https://github.com/kubeflow/pipelines/issues/5223
- https://github.com/kubeflow/pipelines/issues/8332
- https://github.com/kubeflow/pipelines/issues/5329

From Kubeflow Pipeline's perspective, we should probably make database network issues fail more catastrophically, so that users are not left with semi-working Kubeflow Pipelines, and not understanding why things are not working.

----

For users, the solution is to fix your cluster's network access to your MySQL, which could be quite hard to debug, as network issues usually are.

If your MySQL is a managed service (like AWS RDS or Google Cloud SQL), look for VPC routing issues like asymmetric routing. For example, I had a case where the cluster accessed the database via an AWS VPN Gateway, but there was no route back from the database to the cluster.

Note that MySQL sometimes initiates connections back to the client from the "server side", which will obviously fail in the above case.

**Comment by rimolive** [comment]
Closing this issue as there is no users reporting this error since 2022. Feel free to reopen it if the issue remains in latest releases.

/close
