### ISSUE TITLE
should dsl.VolumeOp() create the underlying PV as well as the PVC?

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#3780]
With an example like [this](https://github.com/kubeflow/pipelines/blob/e8a6feb2299d6adf7ea172ca4c058f99aeb1960f/samples/core/volume_ops/volumeop_basic.py) one (also shown below), would we expect the underlying PV to be created in the process of defining the PVC?  I was assuming that was the case given that the docs don't seem to indicate it's necessary to create separately, and as indicated in [these](https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes#dynamic_provisioning) k8s docs, when you create a PVC, Kuberenetes dynamically creates a corresponding PersistentVolume object.  I confirmed that worked.

However, when I run this example pipeline, the PVC gets created, but NOT a corresponding PV.  And I just see the following for the second step:
`This step is in Pending state with this message: Unschedulable: pod has unbound immediate PersistentVolumeClaims (repeated 3 times)`
What should be happening?

```python
@dsl.pipeline(
    name="VolumeOp Basic",
    description="A Basic Example on VolumeOp Usage."
)
def volumeop_basic(size):
    vop = dsl.VolumeOp(
        name="create_pvc",
        resource_name="my-pvc",
        modes=dsl.VOLUME_MODE_RWM,
        size=size
    )

    cop = dsl.ContainerOp(
        name="cop",
        image="library/bash:4.4.23",
        command=["sh", "-c"],
        arguments=["echo foo > /mnt/file1"],
        pvolumes={"/mnt": vop.volume}
    )
```

**Comment by amygdala** [comment]
/assign @elikatsis 
(on Alexey's suggestion-- feel free to reassign)

**Comment by elikatsis** [comment]
This operation is a wrapper of Argo's `ResourceTemplate` which performs an action on a Kubernetes resource. `VolumeOp` performs a `create` for a PVC.

When creating a PVC, it is assumed that you either have a storage class that can provision PVs dynamically, or that your cluster admin has cut PVs for your PVCs to bind.

To provide an answer to your suggestion of provisioning both PV and PVC:
* First of all, it is a bad practice to allow the user be in control of PVs, because they are actually **physical** resources. If it is not under the supervision of the admin, it may mess the cluster up. On the contrary, PVCs are just tickets requesting resources from the admin.
* Secondly, this practice will mess up the logic of clusters with dynamic provisioning

That is why I don't agree with the suggestion.

You linked GKE docs, so I'd guess you run on GKE.
If yes, maybe the problem is that you are asking for PVCs of `ReadWriteMany` mode, which is not supported. Try changing this:
https://github.com/kubeflow/pipelines/blob/e8a6feb2299d6adf7ea172ca4c058f99aeb1960f/samples/core/volume_ops/volumeop_basic.py#L27
into
```python
modes=dsl.VOLUME_MODE_RWO
```

If you are not on GKE, could you give details about your deployment?

---

Another solution would be to have a `ResourceOp` creating a PV just as you like it, and then have a `VolumeOp` bind to it, using this argument:

**Comment by elikatsis** [comment]
This operation is a wrapper of Argo's `ResourceTemplate` which performs an action on a Kubernetes resource. `VolumeOp` performs a `create` for a PVC.

When creating a PVC, it is assumed that you either have a storage class that can provision PVs dynamically, or that your cluster admin has cut PVs for your PVCs to bind.

To provide an answer to your suggestion of provisioning both PV and PVC:
* First of all, it is a bad practice to allow the user be in control of PVs, because they are actually **physical** resources. If it is not under the supervision of the admin, it may mess the cluster up. On the contrary, PVCs are just tickets requesting resources from the admin.
* Secondly, this practice will mess up the logic of clusters with dynamic provisioning

That is why I don't agree with the suggestion.

You linked GKE docs, so I'd guess you run on GKE.
If yes, maybe the problem is that you are asking for PVCs of `ReadWriteMany` mode, which is not supported. Try changing this:
https://github.com/kubeflow/pipelines/blob/e8a6feb2299d6adf7ea172ca4c058f99aeb1960f/samples/core/volume_ops/volumeop_basic.py#L27
into
```python
modes=dsl.VOLUME_MODE_RWO
```

If you are not on GKE, could you give details about your deployment?

---

Another solution would be to have a `ResourceOp` creating a PV just as you like it, and then have a `VolumeOp` bind to it, using this argument:
https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/dsl/_volume_op.py#L47

**Comment by amygdala** [comment]
Thanks for the quick response. I wasn't sure how the op was expected to work, but it makes sense that it's just a PVC creation given the issues in generalizing and managing the PV setup.
 
Closing this issue since it's WAI, though perhaps we should document in a bit more detail (cc @joeliedtke )
