### ISSUE TITLE
Pipeline metrics do not show up on UI

### ISSUE THREAD

**Issue by HongHuangNeu** [kubeflow/pipelines#3809]
### What steps did you take:
[A clear and concise description of what the bug is.]
I use kubeflow dsl containerOp and I try to show the metrics following 
https://www.kubeflow.org/docs/pipelines/sdk/pipelines-metrics/
I generate the metric json following the instructions: write the json file to /mlpipelin-metrics.json and config the ContainerOp like this:
dsl.ContainerOp(
......
     file_outputs={
    'pipeline-metrics':'/mlpipeline-metrics.json'
    }
)

### What happened:
Once the container completes, the metric json file is uploaded to minio which kubeflow is connected to, but THE METRICS ARE NOT DISPLAYED ON THE UI. The 'Run output' tab reports that 'No metrics found for this run.'
### What did you expect to happen:
the metrics should show up in the UI
### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 
kubeflow 1.0
KFP SDK version: 
kfp       0.5.1
kfp-server-api       0.5.0

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug
/area sdk

**Comment by Ark-kun** [comment]
What are the metric names you're using? The issue is probably fixed by https://github.com/kubeflow/pipelines/pull/3741

**Comment by elikatsis** [comment]
Based on your description, @HongHuangNeu 
```python
dsl.ContainerOp(
    ......
    file_outputs={
        'pipeline-metrics':'/mlpipeline-metrics.json'
    }
)
```
the name must be `mlpipeline-metrics` instead of `pipeline-metrics`.

I think the docs are incorrect. It doesn't matter what the path is, it's the (artifact) name that matters.

See these:
https://github.com/kubeflow/pipelines/blob/291f5b3d7a23d906d0f8e82e76dc18ef9be36b24/backend/src/agent/persistence/worker/metrics_reporter.go#L30
https://github.com/kubeflow/pipelines/blob/291f5b3d7a23d906d0f8e82e76dc18ef9be36b24/backend/src/agent/persistence/worker/metrics_reporter.go#L130-L135

And the API call ends up to this function:
https://github.com/kubeflow/pipelines/blob/291f5b3d7a23d906d0f8e82e76dc18ef9be36b24/backend/src/apiserver/resource/resource_manager.go#L938

**Comment by HongHuangNeu** [comment]
@elikatsis Sorry, my actual code for op definition is as follows:

`    
dsl.ContainerOp(
        ......
        file_outputs={'mlpipeline-metrics': '/mlpipeline-metrics.json',
                               'mlpipeline-ui-metadata': '/mlpipeline-ui-metadata.json'}
        ,
    output_artifact_paths={    'mlpipeline-metrics': '/mlpipeline-metrics.json',
                         'mlpipeline-ui-metadata': '/mlpipeline-ui-metadata.json'}
    )
`
@Ark-kun   My metric names are **test_auc_score** and **gbdt_auc_score** respectively.

**Comment by Ark-kun** [comment]
> @Ark-kun My metric names are **test_auc_score** and **gbdt_auc_score** respectively

What happens if you change them to "test-auc-score" and "gbdt-auc-score"?

**Comment by HongHuangNeu** [comment]
It works,thanks!

**Comment by Mistobaan** [comment]
This issue made me double notice that is actually written in the docs that the name has to match a REGEX:
```
pattern = re.compile("^[a-z]([-a-z0-9]{0,62}[a-z0-9])?$")
```
