### ISSUE TITLE
Is there any milestone when this project go to stable?

### ISSUE THREAD

**Issue by tarjintor** [kubeflow/pipelines#3822]
Hello,I am using pipeline recently,it's great
I used to wrote my own code to solve problems like record experiments,compare a set of exps,make workflow for some indpendent jobs.
A lot of pain for me
Thanks for your great work to help people like me

I want to use this in our production envriment

But as the doc says,pipeline is still in beta status,and the issue milestone only find M-2019Q4

So I wonder if there is any plan when this project go to stable?

**Comment by Ark-kun** [comment]
Thank you for your kind words!

We're currently preparing for the 1.0 release which will become the stable version.

**Comment by tarjintor** [comment]
How will pipeline integrity with kubeflow,It seems kubeflow1.0 uses pipeline 0.25,but you already developed to 1.0 now?
or should I use pipeline alone?

**Comment by Ark-kun** [comment]
> How will pipeline integrity with kubeflow,It seems kubeflow1.0 uses pipeline 0.25,but you already developed to 1.0 now?
> or should I use pipeline alone?

The KFP "standalone" deployment method lets you install the latest KFP release. We used to have weekly releases, but have switched to bi-weekly.

The KFP "hosted" or "marketplace" deployment sometimes lags a little bit for stabilization. https://console.cloud.google.com/marketplace/details/google-cloud-ai-platform/kubeflow-pipelines

The Kubeflow (kfctl) deployment of KFP is partially maintained by the community. It's often fals behind due to Kubeflow's quarterly release cycle.

We recommend you use the marketplace or standalone deployment methods.

**Comment by rmgogogo** [comment]
Feel free to create ticket whenever you hit problems.
