### ISSUE TITLE
Input Artifact Path in Component Spec

### ISSUE THREAD

**Issue by venci6** [kubeflow/pipelines#3826]
I'm converting ComponentOps to component specs and am having trouble figuring out to specify a path for an input artifact.

With dsl.InputArgumentPath, I was able to specify a custom path to save the input artifact. However in the component spec, the path defaults to: /tmp/inputs/Input_path/data. Is there a way to define this in the component spec? 

Previous implementation that worked:
```
class Op1(dsl.ContainerOp):
  def __init__(self, name, input_path, ...):
    ...
    artifact_argument_paths = [dsl.InputArgumentPath(argument=input_path, path='/to/desired/path/..')]
    ...
```

Current component spec:
```
name: op1
...
inputs:
- {name: Input path}
...

implementation:
  container:
    ...
    args: [
      '--input_path', {inputPath: Input path}
      ...
    ]
```

**Comment by Ark-kun** [comment]
>I'm converting ComponentOps to component specs

This is great. I'll be glad to help you with the process.

>With dsl.InputArgumentPath, I was able to specify a custom path to save the input artifact. However in the component spec, the path defaults to: /tmp/inputs/Input_path/data. Is there a way to define this in the component spec?

There is no way to do so for inputs. There is a deprecated-from-start way to specify hard-coded paths for outputs, but not for input paths.

We're discouraging the use of hard-coded paths in component code. There are multiple problems with hardcoded paths related to getting data into container and out of the container. And to avoid those current and future problems, the paths need to have certain format (e.g. every output path needs be inside a different directory and have the same filename (e.g. `data`)), so it's just easier to generate the paths.
Generated paths give us the flexibility of executing components on different systems (local environment, Docker, Kubernetes, Google Cloud AI Platform Training, etc). If the paths were hardcoded inside the component, it would be impossible to execute the component code locally.

It seems to us that most programs in the world do not hardcode the paths for input and output data in the program code, but rather receive the paths from the command-line.
And for the few misbehaving programs, the issue is trivial to fix with a tiny shell script wrapper that copies or symlinks the file.

```
name: op1
...
inputs:
- {name: Input path}
...

implementation:
  container:
    command:
    - sh
    - -exc
    - |
      cp "$0" /some/hardcoded/path
      my_prog --input_path /some/hardcoded/path
    - {inputPath: Input path}
```

But of course the best solution is to not hardcode any paths in the component code.

**Comment by venci6** [comment]
@Ark-kun Yeah, avoiding hardcoded paths is obviously better, but since it was possible with the dsl code, just wanted to check all bases first. Thanks for the clarification!
