### ISSUE TITLE
Storing and Accessing a Private Dataset for a Pipeline

### ISSUE THREAD

**Issue by mmwebster** [kubeflow/pipelines#4023]
/kind question

**Question**
What is the recommended way to store and access a private dataset (~200GB extracted) for use in a component in a Kubeflow pipeline run on GCP?

**Context/Environment**
For context, (not sure if relevant) my data is currently on a GCP VM instance, I’m using PyTorch, and I’ll be using preemtible VMs for my GPU nodes. And I’m using Kubeflow v1.0.2 and have already followed the guides for deploying it (w/ KF pipelines) on GCP.

**More Granularly**
1. How should I store a private dataset on GCP?
2. How should I transfer this data to the GCP storage mechanism?
3. How should I access this data from a Kubeflow pipeline component using PyTorch?
4. How does this method ensure low-latency for fetching training batches, close enough to that of a local filesystem?
5. How should I store and access transformations/preprocessing of this dataset that will be prone to change? (Whereas the dataset can be read-only)

**Comment by rmgogogo** [comment]
It seems not a question to KFP but more general GCP/cloud question.

There are several options. GCS for objective data. CloudSQL for relational data. BigQuery for bigdata-styled/columar stuff.

as for how access them, you may write certain connector with it. Are you using TFX SDK? If so, you may write Custom Component in TFX. If you prefer arbitry codes packaged in a container image, that's also doable. BTW, PyTorch also can work together with TFX (we may improve the internface be better, however using TF may save efforts considering it's same stack).

https://github.com/tensorflow/tfx/tree/master/tfx/examples/bigquery_ml

Here is a reference.

**Comment by mmwebster** [comment]
@rmgogogo Thank you! This helps a lot.

Specifically on the KFP side—would you advise against using the outputPath/inputPath mechanisms for passing many GBs of data to a training component that has compute resources? My understanding is that this IO mechanism copies data to/from GCS, and so would limit the training component from fully utilizing GPU resources while data is being downloaded in bulk from GCS. Is this correct? Would it be better to stream training data from GCS during training?

On the TFX side—what specific feature/component would help, here? What does a TFX Custom Component provide that PyTorch in a KFP component cannot?

**Comment by Ark-kun** [comment]
Hello, @mmwebster 
The main options are:

1) Downloading the data
2) Accessing the data by URI
3) Mounting the data

## Downloading the data:

This option is realized through `inputPath`/`outputPath` placeholders in `component.yaml` (and `inputPath`/`OutputPath` annotations in python).

pros:
* The data access is the fastest. For ML training where you need to go through the dataset multiple times, this option is the best.
cons:
* Downloading takes time
* For big data, the containers need big disks. AFAIK, the default size is 100GB, so for 200GB you'll need to customize the storage.

## Accessing the data by URI

To use this option, define inputs for the input **and output** URIs and also outputs for the output URIs. Output URIs need to be inputs, because tehy need to be passed in, but they also need to be outputs, so that they can be passed to the downstream components.
```
inputs:
- name: input1_uri
- name: input2_uri
- name: output1_uri
- name: output2_uri
outputs:
- name: output1_uri
- name: output2_uri
implementation:
  container:
    args: [
      '--input1-uri', {inputValue: input1_uri},
      '--input2-uri', {inputValue: input2_uri},
      '--output1-uri', {inputValue: output1_uri},
      '--output2-uri', {inputValue: output1_uri},
      '--output1-uri-file', {outputPath: output1_uri},
      '--output2-uri-file', {outputPath: output1_uri},
    ]
```

pros:
* Supports accessing arbitrary storage systems
* Accessing data of any size
cons:
* The component can become storage-specific. If you use GCS library to access the data, your component is not GCP-specific and won't work in-prem.
* The system no longer manages the intermediate data for you. The components may write/delete/modify any data it has access to. The data immutability is no longer guaranteed.
* The system no longer auto-generates unique URIs for your data, so you need to make the URIs unique yourself by using the `kfp.dsl.EXECUTION_ID_PLACEHOLDER`.

## Mounting the data

This a more experimental area.
It's possible to put the data on a Kubernetes volume and then mount that volume to every pipeline step that needs the data (`task.add_volume_mount`, `task.add_volume`).
There is also an experimental [PR](https://github.com/kubeflow/pipelines/pull/3371) that will be merged soon that allows taking a pipeline that uses `inputPath`/`outputPath` and convert it to use a specified volume for data passing instead of S3/Minio storage. This way you can have a normal pipeline that can also be launched for really big data. There are many different kinds of volumes. There are NFS volumes that support Google's FileStore storage. There are also examples of exposing GCS buckets as Kubernetes volumes.

What do you think?

**Comment by mmwebster** [comment]
@Ark-kun This was exactly what I was looking for! Thank you!

I was a little too optimistic about the URI option and tried streaming individual dataset samples (large .wav files...) to compose batches on the fly. This allowed me to immediately begin training on component startup, however I discovered that download speeds were far bellow what they would need to be in order to keep up with even the lowest tier GPU on GCP. So now I'm switching to the download option you recommended, and storing the dataset in a ~60GB compressed form as a single blob in a bucket.

Can I modify the Kubeflow-generated default `gcp-config/cluster-kubeflow.yaml` in order to increase the size of the gpu-pool's boot disk?

**Comment by mmwebster** [comment]
For anyone stumbling across this thread, I just created a new GCP node pool based off of the [KF preemptible VM guides](https://www.kubeflow.org/docs/gke/pipelines/preemptible/) in order to increase the size of my GPU node boot disks. My main unknown was authentication for the new node pool—you can actually assign your existing kubeflow service account to the node pool. And I used `--disk-size=400GB` to get the size I needed.
