### ISSUE TITLE
KFP-Cache - Template name should not affect cache key

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4038]

**Comment by rmgogogo** [comment]
Hi Alexey, will you handle this in Q3?

In my side plan, I will support native MLMD which may deprecate cache server and MLMD-writer. Aka in the future, TFX SDK will cover major feature of KFP SDK. Since KFP-cache and MLMD-writer is only need when using KFP SDK, I didn't treat this (and #4036) with priority. However if you can jump in to solve it, also helps.

**Comment by Ark-kun** [comment]
> Hi Alexey, will you handle this in Q3?

Sure. I've self-assigned this item from the start.
Do not worry. I'm supporting Metadata Writer and Cache so I'm self-assigning all issues to myself.
These issues are more like my ToDos for myself to remember. I do not want to take anyone's time for these items.

>I didn't treat this (and #4036) with priority.

I've merged a fix for that one already.
