### ISSUE TITLE
Pipeline API should expose an API to set default version for a given pipeline

### ISSUE THREAD

**Issue by lilida** [kubeflow/pipelines#4049]
Today, there is no Pipeline API to update the default version id for a given pipeline. Pipeline default version is only automatically updated when a new version is created. Although UpdatePipelineDefaultVersion has been implemented pipeline_store.go, it was not exposed to pipeline service api.

**Comment by Bobgy** [comment]
@NikeNano let's discuss in the issue first

My questions:
https://github.com/kubeflow/pipelines/pull/4406#issuecomment-679029048

**Comment by NikeNano** [comment]
I think it make sene to have the possibility to set the default pipeline. Currently the default pipeline is updated when a new pipeline is uploaded to the latest. 

We have had problems when development where done uploading new pipelines and runs where done with the latest versions by mistake instead of the last stable version.

However one possibility would also be to no automatically update when a new pipeline is uploaded.

**Comment by Bobgy** [comment]
Right, looks like the behavior you want is to not automatically update when a new pipeline is uploaded, while being able to set default version programmatically

**Comment by Bobgy** [comment]
Can you think about a reasonable way to make the new behavior available to you without breaking backward compatibility?

**Comment by NikeNano** [comment]
> Can you think about a reasonable way to make the new behavior available to you without breaking backward compatibility?
> or maybe a generic tag system can be better?

I guess we could add it as an option to update the default version when a new pipeline is uploaded and set it a default to. updates.  Thus have the same default behaviour as it is today. But I also think it makes sense to be able to change the default without uploading a new pipeline.

**Comment by Bobgy** [comment]
@NikeNano great idea, that sounds reasonable!

I can help you review any PRs if you'd like to contribute.
