### ISSUE TITLE
Allow specifying inputs to be excluded from cache validation process

### ISSUE THREAD

**Issue by JakeTheWise** [kubeflow/pipelines#4090]
My pipeline steps currently take `pod_name: str = '{{pod.name}}'` argument so that my component can be made aware of its own metadata environment. Obviously, the pod name changes every run, which means kubeflow's caching mechanism won't work, even if nothing about the component inputs, code or outputs actually changed. I think there should be a) a first-class way for components to get info about their runtime metadata and/or b) a way to at least exclude my `pod_name` param so that the caching mechanism will ignore it if its value changes run to run. Perhaps we can expose `pod_name` as an environment variable inside each container?

**Comment by JakeTheWise** [comment]
By inspecting the environment variables that are present inside each step's container, you'll notice that `HOSTNAME` is set to be the pod name.

**Comment by meowcakes** [comment]
I think this feature request would still be useful. To give an example, if the component launches an EMR job and you want to use `{{workflow.uid}}` in the job name or tags so that it can be traced to a specific workflow. The job name has no effect on the output of the component, but Kubeflow will never use the cache because `{{workflow.uid}}` is always unique.
