### ISSUE TITLE
Make low level APIs for DSL ContainerOp by leveraging k8s and argo library

### ISSUE THREAD

**Issue by hongye-sun** [kubeflow/pipelines#415]
Currently, ContainerOp is a wrapper of Argo's template object which also wraps a k8s container object. The current high level APIs are not flexible enough that user can edit the full spec of the wrapped object. 

It's better to provide a low level API to let advanced user to use Argo and k8s py lib to build the underlying object directly, while still keep high level APIs easy to use for most of the users.

**Comment by jlewi** [comment]
Should there be a clean separation between the APIs and the python library? 
Should the primary goal of python library to be able to construct API objects using idiomatic  python?

A model would be something like OpenAPI where the API can be defined in a language independent manner. For a given API, one can then create client libraries in a given language to construct it an idiomatic fashion.

Related question, how can the DSL be easily extended to orchestrate custom Kubernetes resources? It would be nice if I could just "inline" custom resources (similar to what Argo supports argoproj/argo#606).

I think the desired semantics would be something like

   1. Create a custom resource
   1. Wait for the specified conditions to be reached

**Comment by qimingj** [comment]
Is there a strong reason that DSL needs to follow the OpenAPI pattern? I don't foresee in the near future another DSL with a different programming language. Introducing a language neutral API is more useful when you want to expose it in multiple languages.

CRD support --- yes. I would like to support two levels of K8sOp. The low level is arbitrary resource:

op = K8sOp(resource_spec, jsonPath='...')

We should also provide resource specific high level ops:

op = TfJobOp(container_image='...', ...)

One gap is that argo only supports gathering output from job status, and not all CRDs insert results there. This requirement is important because we want to pass output to downstream components.

**Comment by vicaire** [comment]
@hongye-sun, can we close this now?

**Comment by hongye-sun** [comment]
Yes, this issue has been addressed by #801 .
