### ISSUE TITLE
Troubleshoot step caching 

### ISSUE THREAD

**Issue by sudivate** [kubeflow/pipelines#4169]
Followed https://github.com/kubeflow/pipelines/tree/master/backend/src/cache  and 
https://www.kubeflow.org/docs/pipelines/caching/#what-is-step-caching 

But had no luck caching pipeline step. How do I troubleshoot if the caching server is step up correctly? 

KFP 0.5.0

 /area backend

**Comment by Ark-kun** [comment]
The caching should work transparently. Just run a pipeline. Wait for it to finish. Run the same pipeline again. The pipeline should execute faster due to skipped steps.

Let's try to find the root of the problem. Are you running a custom pipeline? Does a preloaded pipeline work (e.g. Data passing)?

Can you check that the cluster is healthy? Use `kubectl get pods --all-namespaces` and check for any kubeflow pods in error state.

**Comment by sudivate** [comment]
All pods including the cache server and mysql are running healthy. Yes, I'm running my custom pipeline with static component and caching enabled by setting  caching_strategy.max_cache_staleness="P30D" but  I don't see the step getting skipped on re-execution

**Comment by Ark-kun** [comment]
>caching enabled by setting caching_strategy.max_cache_staleness="P30D"

JFYI: This is not required.

How did you deploy KFP? Marketplace, Standalone or kfctl?

Can you check the cache serverlogs:

```
kubectl logs --selector app=cache-server
```

I think KFP 0.5.0 lacks UX indication of skipped steps. But the log tab should say that the step was skipped. Can you please check the annotations of some pods that should have been skipped, but was executed?

P.S. There were been some fixes and improvements to the UX and the way the caching server is deployed in v0.5.1. Also we're going to release v1.0 in few days. Maybe this will fix your issue.

**Comment by sudivate** [comment]
Thank you @Ark-kun. I ran with KFP-1.0.0-rc5 and works smoothly. This is good to close. 

Any tentative dates on release?

**Comment by Bobgy** [comment]
The coming monday!

/close
