### ISSUE TITLE
After archiving an experiment, its runs can no longer be observed

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#4172]
### What steps did you take:
1. create an experiment
2. create a few runs in it
3. archive the experiment
4. go to "Archive" -> "Experiments" -> select the experiment

### What happened:
it shows no runs there.

### What did you expect to happen:
It should show all the archived runs in that experiment.

### Environment:
KFP version: 1.0.0-rc.4

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by jingzhang36** [comment]
Can you have a screen recording for this? In case I can't reproduce it. And also, it takes time to list runs (takes more than it should due to some strange performance issue. So, moreover, could you check back later to see if the runs show up after a while?

**Comment by Bobgy** [comment]
@jingzhang36 you can look at this https://3f976e6d7065d25b-dot-asia-east1.pipelines.googleusercontent.com/#/experiments/details/6d821dc6-ecc8-4bcb-b627-4549809c67f5

or this video https://youtu.be/1o_GHm8aEvM

**Comment by Bobgy** [comment]
This is good for UI on boarding

**Comment by zijianjoy** [comment]
Sharing some thought on the issue:

1. There are two levels of `Archive` on KFP: Archive an experiment, or Archive a run.
2. When archiving a run, it will disappear from the experiment detail page.
3. When archiving an experiment, the experiment object itself is archived, and all the runs it contains are also archived.
4. Therefore, after archiving an experiment, and we went on to check this experiment out, there is no run. (It makes sense because experiment detail page only shows active run)

Suggestion on approach:
Experiment detail page should have an entry point to `archived run` which allows user to see the result of their `Archive Run` and `Archive Experiment` action, which is moving one run or all the runs to an Archive location they can access.

How do people think?

**Comment by Bobgy** [comment]
> Therefore, after archiving an experiment, and we went on to check this experiment out, there is no run. (It makes sense because experiment detail page only shows active run)

All the runs of an archived experiment can only be archived, so it makes experiment details page of an archived experiment useless. That's why I proposed to slightly change the expected behavior:
1. when experiment is active, its details page shows active runs
2. when experiment is archived, its details page shows archived runs

but I think your suggestion can be a further improvement, because in KFP UI, there's no way to find all archived runs that below to a single experiment.
Probably, the UX I preferred can be translated to:
1. when experiment is active, visiting details page shows “active runs tab" by default
2. when experiment is archived, visiting details page shows "archived runs tab" by default

What do you think?

**Comment by zijianjoy** [comment]
> 1. when experiment is active, visiting experiment details page shows “active runs tab" by default
> 2. when experiment is archived, visiting experiment details page shows "archived runs tab" by default

That sounds good! I will explore more to see how to implement this behavior.
