### ISSUE TITLE
Trying to upload a new pipeline version with the SDK returns an AttributeError

### ISSUE THREAD

**Issue by BoecquaertJonas** [kubeflow/pipelines#4173]
### What steps did you take:
I'm trying to create and upload a new pipeline version using the kfp SDK.
I'm following the documentation I found here: https://www.kubeflow.org/docs/pipelines/tutorials/sdk-examples/
```python
CLIENT = kfp.Client(host=HOST)
pipeline_version = CLIENT.pipeline_uploads.upload_pipeline_version(
    uploadfile=pipeline_filename,
    name=PIPELINE_VERSION_NAME,
    pipelineid=PIPELINE_ID
)
```
I'm not uploading a pipeline first, because the pipeline already exists. I copy, pasted the `PIPELINE_ID` from the frontend UI for testing purposes, and when I use `CLIENT.get_pipeline(PIPELINE_ID)` I'm getting the correct result.

### What happened:
I'm getting the following error when trying to run the code above.
![image](https://user-images.githubusercontent.com/29035046/86906416-cca31280-c113-11ea-8f5e-a3b4b521e480.png)

### What did you expect to happen:
I expected a new pipeline version to get uploaded.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?
kfp standalone deployment 0.5.1 on GCP AI Platform pipelines.

KFP SDK version:
![image](https://user-images.githubusercontent.com/29035046/86906648-260b4180-c114-11ea-92fa-32ea00fb06af.png)

### Anything else you would like to add:
I found this comment on a previous issue, stating that with the SDK versions and deployment I'm using, the code I try running should work: https://github.com/kubeflow/pipelines/issues/3805#issuecomment-631868930

**Comment by Ark-kun** [comment]
Thank you for the report.

Can you please check what this code prints?
```
print(dir(CLIENT.pipeline_uploads))
```

**Comment by BoecquaertJonas** [comment]
This is what I get back.
![image](https://user-images.githubusercontent.com/29035046/87287729-beca0480-c4fa-11ea-900b-ce50a3585c55.png)

No trace of `upload_pipeline_version`.

**Comment by Ark-kun** [comment]
Thank you for your patience.

I think I've found the root cause.

@rmgogogo It looks like KFP 0.5.1 was released with API changes ([PR](https://github.com/kubeflow/pipelines/pull/3001/files#diff-61677d48aaf2ae7c6ed570f39ccd4d1cR55)), but without releasing a corresponding version of the [kfp-server-api](https://pypi.org/project/kfp-server-api/#history) python client package. The latest release version of [kfp-server-api](https://pypi.org/project/kfp-server-api/#history) is 0.5.0.

@BoecquaertJonas As a workaround, please update your kfp-server-api package to a pre-release version: `pip3 install kfp-server-api==1.0.0rc5`

**Comment by BoecquaertJonas** [comment]
Upgrading the kfp-server-api package did not fix the issue.
![image](https://user-images.githubusercontent.com/29035046/87525365-b18f5000-c689-11ea-8d22-af483bd0dc8d.png)
![image](https://user-images.githubusercontent.com/29035046/87525536-eb605680-c689-11ea-9541-9822f9b9ab8a.png)

**Comment by BoecquaertJonas** [comment]
I upgraded the kfp-server-api package to 1.0.0rc5 and now it works. Thank you for the workaround.
