### ISSUE TITLE
[Question] ComponentSpec that can specify Kubernetes resources

### ISSUE THREAD

**Issue by terrykong** [kubeflow/pipelines#4229]
I understand from a few KFP issues that component specs (in yaml) are the most portable way to specify our tasks, but I have not found a way to do the following:

I want to convert a component I had a while back where I explicitly created a `ContainerOp` to a component yaml spec.

The example I have is
```
@kfp.dsl.component
def export_to_nfs(save_path):
    export_op = kfp.dsl.ContainerOp(name='export',
                                    image='alpine',
                                    command=['sh', '-c'],
                                    arguments=['echo hi > /mnt/foobar.txt'],
                                    )
    export_op.container.add_env_from(V1EnvFromSource(secret_ref=V1SecretEnvSource(name='my-secret', optional=False)))
    nfs_volume = V1Volume(name='nfs-volume', nfs=V1NFSVolumeSource(server='a-nfs-server.com',
                                                                   path='/path/to/save/stuff',
                                                                   read_only=False))

    export_op.add_pvolumes(pvolumes={'/mnt': nfs_volume})
    return export_op
```

But looking at https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/components/_structures.py#L235, there doesn't seem to be a way to specify any of those kubernetes resources in the yaml spec.

Is what I'm trying to achieve possible in KFP currently?

**Comment by Ark-kun** [comment]
For container components this feature does not exist by design:
KFP components are designed to be portable. It's possible to run them on non-Kubernetes systems like local Docker, and various container-running services like Google Cloud or AWS. If it was possible to add that volume mount to the component itself, the component would have only worked on one cluster and won't be reusable.

How to apply any Kubernetes customizations then? It's possible. When you create an instance of some component during compilation using KFP's DSL compiler you get a ContainerOp object. You can use that object to customize the particular task (component instance, not component). So, for now you can use the exact same code, just with `export_op = load_component_from_url(...)`.

P.S. Graph components represent a pipeline graph. They describe tasks and allow customizing them. We're currently refactoring the support for Kubernetes customizations. Once the work is done, you'd be able to create a single-task graph component that overlays Kubernetes customizations (like volumes) on top of a container component task.
Still, the reusability of such component component would be limited. I wonder whether you can directly write to NFS without using volumes using an NFS client library like https://github.com/sahlberg/libnfs-python/.

**Comment by terrykong** [comment]
Thanks @Ark-kun for the explanation. Is there an open issue where I can track the kubernetes customization support?

It looks like there was support for specifying kubernetes stuff here
https://github.com/kubeflow/pipelines/commit/39975e3cde7ba4dcea2bca835b92d0fe40b1ae3c

But was removed recently. Is this the kind of kubernetes customization you were speaking of?

**Comment by terrykong** [comment]
Sorry, wasn't able to get back to this until just the other day.

Yes, I can confirm that your suggestion works for me. I guess I'll close this issue, and look forward to being able to specify kubernetes constructs in these specs.

**Comment by terrykong** [comment]
Hi @Ark-kun . I'm revisiting this from almost a year ago since this is still a feature that would be helpful for our team. Has "launcherOptions" been abandoned? I see that **https://github.com/kubeflow/pipelines/pull/4156** was closed with no replacement.
