### ISSUE TITLE
[Release] release script should bump kfp-server-api requirements.txt version

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#4262]
Can you also add automation for updating this during release so we don't miss it next time?
https://github.com/kubeflow/pipelines/blob/22063ff88d4a459a3b60023cc82bdf3d0d0243d7/sdk/hack/release.sh

_Originally posted by @Bobgy in https://github.com/kubeflow/pipelines/pull/4255#issuecomment-662796651_

**Comment by Ark-kun** [comment]
I think the problem is a bit different. `requirements.txt` needs to be changed every time you change `requirements.in` (or requirements in `setup.py`). Maybe we need some test to check that these files are always changed together.

**Comment by Bobgy** [comment]
@Ark-kun but `requirements.in` is only specifying loose versions
e.g. `kfp-server-api>=0.2.5, <2.0.0`

So I guess we need to re-pin `requirements.txt` after a release is out?

Where are `requirements.txt` used? Is it for testing and readthedocs? Any other places?

**Comment by Ark-kun** [comment]
> So I guess we need to re-pin `requirements.txt` after a release is out?

`requirements.txt` should be updated (using the provided script and command-line) at least every time `requirements.in` is changed. Otherwise they are out of sync.

>Where are requirements.txt used? Is it for testing and readthedocs? Any other places?

It's also used in the tests and it can be used by people installing KFP to get a known-good environment. Otherwise we can get the same problems as TFX - some dependency has released a new version and now all tests are broken and the installation does not work for the new users.

**Comment by Bobgy** [comment]
I see, I'll add it as a post release step.
