### ISSUE TITLE
The node was low on resource memory from kubeflow pod

### ISSUE THREAD

**Issue by vishal-kr-yadav** [kubeflow/pipelines#4275]
I tried to increase the number of nodes from the kubeflow clusters from 3 to 12 but it didnt work.

This is the dockerfile i am using : https://github.com/kubeflow/examples/blob/master/object_detection/docker/Dockerfile.training

Based on the dockerfile i am generating the kubeflow pipeline using kfp

I can run the docker image on a VM and its saving the checkpoint of the tensorflow models.
I have tested the kubeflow pipeline its running fine initially but when its tring to start the training then its getting OOM problems from kubeflow pipeline.

ERROR LOGS FROM THE POD : **This step is in Failed state with this message: The node was low on resource: memory. Container main was using 1783932Ki, which exceeds its request of 0. Container wait was using 13296Ki, which exceeds its request of 0.**

kubeflow version : 0.5.1

How did you deploy Kubeflow Pipelines (KFP)?
I have deployed the kubeflow pipeline from the GCP market place--> deploy kubeflow pipeline 

I tried with sample pipeline from kubeflow assets it was running fine on the same clusters, but when i was trying to make my own pipeline from scratch by using my docker containers it was throwing this error

**Comment by motilalmeher** [comment]
"/reopen"

**Comment by motilalmeher** [comment]
@vishal-kr-yadav Have you solved this issue?

**Comment by Subhraj07** [comment]
Is there any solution available?

**Comment by Joel-De** [comment]
Please reopen this issue, if I'm understanding the error log correctly KFP requests 0 memory and so when a Nodes RAM fills up it's first to be evicted. It would be nice if this were some non 0 value / if we had explicit control over it. In my case the KFP pod is scheduled to a node that doesn't have a lot of RAM available (which is legal since it's requesting 0 RAM) and OOM's then moment a process starts. I have other nodes available with lots of free RAM but KFP isn't being scheduled there due to this bug,
