### ISSUE TITLE
KALE pipeline for R kernal

### ISSUE THREAD

**Issue by sabarikannan-ai** [kubeflow/pipelines#4423]
We build so many python based pipeline with KALE successfully. But R it is not working. Why because of , the  kfp compile code is written on .py . 

Advice me how to use KALE for R

**Comment by Ark-kun** [comment]
KFP orchestrates containerized command-line programs.
To use R or any other language, you'll need to create a command-line program and wrap it in component.yaml definition like all other components.

**Comment by DavidSpek** [comment]
@sabarikannan-ai This issue seems to be more relevant for https://github.com/kubeflow-kale/kale. Kale does not have support for R at the moment as it needs to parse the code for pipeline metrics, pipeline parameters and to understand its data dependencies. I am currently looking into [rpy2](https://pypi.org/project/rpy2/) which might be a way to use R with Kale (I have not gotten around to trying it myself yet though).

**Comment by Ark-kun** [comment]
BTW, there is not a Papermill component that can run notebooks. But it's for Python.
Is there a similar system that can execute R notebooks? You could contribute a component wrapping it.

**Comment by DavidSpek** [comment]
It seems this project is similar to Kale and does have support for R notebooks. https://github.com/elyra-ai/elyra
