### ISSUE TITLE
FR: render TB vizualization while a pipeline step is running

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#4431]
/kind feature
(using KFP 1.0.0)

I have a pipeline with training steps that generate the tensorboard visualization (via writing out a metadata dict).  This viz doesn't show up until a training step is done.  It would be preferable to be able to launch TB from the dashboard while the training is running. Would this be doable?

**Comment by Ark-kun** [comment]
You can use the [Prepare TensorBoard](https://raw.githubusercontent.com/kubeflow/pipelines/master/components/tensorflow/tensorboard/prepare_tensorboard/component.yaml) component to initialize tensorboard and output a URI for logs. You can then pass that URI to your trainer component (add a "Log dir URI" input), so that it can be used for TB logging. This way you can watch Tensorboard during the training.

**Comment by amygdala** [comment]
> You can use the [Prepare TensorBoard](https://raw.githubusercontent.com/kubeflow/pipelines/master/components/tensorflow/tensorboard/prepare_tensorboard/component.yaml) component to initialize tensorboard and output a URI for logs. You can then pass that URI to your trainer component (add a "Log dir URI" input), so that it can be used for TB logging. This way you can watch Tensorboard during the training.

oh, I had missed that component.  cool!  Will give it a try.
