### ISSUE TITLE
Change adding V1Toleration, V1Affinity pattern in the container

### ISSUE THREAD

**Issue by subodh101** [kubeflow/pipelines#4454]
What?
`add_toleration` and `add_affinity` requires users to add [V1Toleration](https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/dsl/_container_op.py#L793) and [V1Affinity](https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/dsl/_container_op.py#L804) objects.
Instead, pass the arguments and create the object in the SDK itself.

Why?
[Users](https://kubeflow.slack.com/archives/CE10KS9M4/p1598915504014300) and I myself found it difficult at first as I was expecting this to happen under the hood similar to other `add_*` functions.
Also sometimes people don't even know where to get the `V1Toleration` and `V1Affinity` objects.
Another important reason is that this feature itself is very important when it comes to cost optimization of the workloads. So should be straight forward of use.

How?
- By deprecating the current approach.
- and adding new changes.

**Comment by Ark-kun** [comment]
1. Generally we try not to add such functions ourselves, but rely on existing structures for the maintenance. For example, task.container just uses the V1Container Kubernetes type. We had to add add_toleration and add_affinity to ContainerOp since they belong to the Kubernetes PodSpec, but we/Argo cannot support most of the PodSpec attributes. So we have to manually add support for those attributes.
2. These two functions have either been community We're not using these functions ourselves, so we do not know the user scenarios and do not know how to simplify them. We try to avoid the DSL being too Kubernetes-specific so adding multiple simplified variants of the same advanced function might be questionable.

We'd like to see your proposal for a simplified and more user-friendly version of these functions.

We could then try to add them to either ContainerOp or the extensions (similarly to `kfp.on_prem.mount_pvc`)
