### ISSUE TITLE
What's the relationships between static type checking in kfp and that like mypy

### ISSUE THREAD

**Issue by zyxue** [kubeflow/pipelines#4489]
I wonder if the [static type checking in kfp](https://www.kubeflow.org/docs/pipelines/sdk/static-type-checking/) is an alternative to something like [mypy](https://mypy.readthedocs.io/en/stable/)?

**Comment by Ark-kun** [comment]
KFP's static type checking is more like compile-time type compatibility checking. When you pass task output to component input, the compiler checks that the declared types are the same.

Static type checking tools like mypy cannot be used for this because the pipelines are dynamic - the components are loaded from remote URIs and dynamic functions are generated.
