### ISSUE TITLE
Add new github label specific for AWS SageMaker Components 

### ISSUE THREAD

**Issue by akartsky** [kubeflow/pipelines#4541]
Request to add a new label specific for AWS SageMaker Components so that it's easier to filter 
https://github.com/kubeflow/pipelines/labels

Currently we only have "platform/aws"

**Comment by akartsky** [comment]
@Jeffwan

**Comment by Bobgy** [comment]
@akartsky Can you give me a label name you prefer?
I can help you add it.

**Comment by Bobgy** [comment]
Actually, suggest following guidelines in https://github.com/kubeflow/testing/tree/master/label_sync.
You can submit a PR to add it

**Comment by jlewi** [comment]
@Bobgy I'm not sure label_sync is applied to kubeflow/pipelines I think we might be excluding that repo from the sync. I think originally the pipelines repo owners didn't want the sync because it would have created a bunch of labels related to the other projects and not pipelines to the repo.
I think there might be a way to sync different labels to different repos now.

**Comment by Bobgy** [comment]
@jlewi @akartsky I see, that's right. I'll create a label for you manually.

**Comment by Bobgy** [comment]
@akartsky does this work for you? Do you propose a different label name?

**Comment by akartsky** [comment]
this works 
thanks !
