### ISSUE TITLE
Is it possible to use a kfp pipeline as a kfp component?

### ISSUE THREAD

**Issue by simanw304** [kubeflow/pipelines#4555]
I understand I can containerize a kfp pipeline `A` and use it as a component in another pipeline `B`. In that component, it will submit a kfp run to gcloud kfp platform and give me the link. Is it possible to somehow watch the status of that run and continue processing in `B` after that run finishes? I wonder whether there is related functionality or similar practices. Thanks.

**Comment by Ark-kun** [comment]
Generally, there are two options:
1) Create graph component from a pipeline A (`create_graph_component_from_pipeline_func`), then load and use that component in pipeline B. With the current compiler the result would be that A will be inlined into B. This can be done now.
2) Create a component that launches a particular KFP pipeline and use that component in pipeline B. Such component does not exist yet and in recent KFP versions, connecting to KFP API server from container became harder: https://github.com/kubeflow/pipelines/issues/4440

**Comment by Bobgy** [comment]
You can use https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.client.html#kfp.Client.wait_for_run_completion to watch a pipeline's status from a pipeline component.

**Comment by Udiknedormin** [comment]
@Ark-kun 
Ad 1, creating graph component --- I think it doesn't support many features available in pipelines, correct? Component yaml format only contains conditions (although that feature didn't work the last time I checked),  but not e.g. `ParallelFor` equivalent? Or did I miss something?

**Comment by romanwozniak** [comment]
Also interested in this. Is there any particular blocker/design decision on why `create_graph_component_from_pipeline_func` doesn't support many things that is possible to do in the pipeline itself?

For example:

```python
def my_component(a: str, b: int) -> str:
    return a + str(b)

my_component_op = kfp.components.func_to_container_op(my_component)

@dsl.pipeline()
def my_graph_component():
    with dsl.ParallelFor([{'a': "a", "b": 1}, {'a': "b", "b": 2}]) as item:
        my_component_op(item.a, item.b)

kfp.components.create_graph_component_from_pipeline_func(my_graph_component, __file__ + '.yaml')
```
results in
```
  File "/Users/rwozniak/dev/source.golabs.io/roman.wozniak/gobstopper/pipelines/kubeflow_pipelines.py", line 15, in my_graph_component
    with dsl.ParallelFor([{'a': "a", "b": 1}, {'a': "b", "b": 2}]) as item:
  File "/Users/rwozniak/.miniconda3/envs/gobstopper_new/lib/python3.7/site-packages/kfp/dsl/_ops_group.py", line 211, in __init__
    code=str(_pipeline.Pipeline.get_default_pipeline().get_next_group_id()),
AttributeError: 'NoneType' object has no attribute 'get_next_group_id'
```

it is not even possible to explicitly set the dependencies between tasks in the graph component:

```python
@dsl.pipeline()
def my_graph_component():
    task_a = my_component_op("a", 1)
    my_component_op("b", 2).after(task_a)
```
fails with:
```
'TaskSpec' object has no attribute 'after'
```
Thanks!

**Comment by Ark-kun** [comment]
> Also interested in this. Is there any particular blocker/design decision on why `create_graph_component_from_pipeline_func` doesn't support many things that is possible to do in the pipeline itself?

There are two issues:
* Some of the features (loops) are not yet supported in the graph component spec
* Some features like conditionals exist in the spec, but are not exposed in the DSL.

Can you please tell me more about your scenario? Is it similar to @simanw304's? Do you just want to run a pipeline and wait for it to complete? What kid of pipeline with ParallelFor or condition you want to componentize?

P.S. Normally, components are connected through data passing, so `.after` is not needed. It's a bit of a code smell that indicates problems.

**Comment by romanwozniak** [comment]
> Can you please tell me more about your scenario?

One use case I'm evaluating at the moment is packaging multi-step pipelines as a separate component, that can be used in another pipeline. For example, the pipeline I'm thinking about packaging as a component is something like: 
- Step 1.  use `ResourceOp` to create a Spark cluster (dataproc)
- Step 2. Submit a pyspark job into that cluster and wait for the job completion
- Step 3. Clean-up resources from k8s

I want to have these three steps to be packed as an "atomic" component, that later on can be loaded and added into another pipeline.

> What kid of pipeline with ParallelFor or condition you want to componentize?

I have something like this on my mind: package a component, that accepts a comma-separated string value as an `inputParam` and then runs a separate instance of some task (or a sequence of tasks) in parallel.  

> Normally, components are connected through data passing, so .after is not needed. It's a bit of a code smell that indicates problems

I think that it's _possible_ to write a pipeline that `after` relation is expressed implicitly through data passing, but it's not always necessary to do so. Example: a pipeline that consists of steps: 
1. Spark job that generates some dataset and writes it into BQ
2. Spark job that uses dataset generated in step1 and does some ML model inference on it

Clearly, step2 has a dependency on step1 and it's _possible_ to define a pipeline in a way, that step1 outputs the name of generated dataset and step2 uses it as inputParam. But the datasetName is probably a pipeline parameter, (because step1 should know where to write the data to), so step2 can use this param directly and not relying on the outputs of step1. And in this case, `.after(step1_op)` is easier to understand because of its explicitness.

**Comment by Michallote** [comment]
This is totally possible to do. Just call the pipelines inside another pipeline object. (As if they were simply components.)

You can specify sequences and dependencies using `.after`

Now as to how to "surface" the Artifacts or Output[Datasets] created by one pipeline. You will need to use the named tuple notation to declare an output. Then simply add the return statement to each pipeline, that way the Task they return upon finishing will house all artifacts you specify as a return key.

```python
@pipeline(pipeline_root=PIPELINE_ROOT, name=PIPELINE_NAME)
def compiled_pipeline():
     p1_task = download_and_process_pipeline()
     p2_task = training_pipeline().after(p1_task) # When you have no explicit outputs from a pipeline.    
```

Example on how to specify a pipeline output:

```python

outputs = NamedTuple("outputs", training_dataset=Dataset)

@pipeline(pipeline_root=PIPELINE_ROOT, name=PIPELINE_NAME)
def compiled_pipeline() -> outputs:
    s0_output = s0_parameters_parse_dates_stage()
    ... # your other components
    s4_output = s4_raw_processing(work_dates_idst=s0_output.output)
    return outputs(s4_output.output)
```
