### ISSUE TITLE
Empty pipeline parameters are passed as empty strings instead of ignored

### ISSUE THREAD

**Issue by alexlatchford** [kubeflow/pipelines#4562]
### What steps did you take:

1. Create a pipeline using to the `func_to_container_op` and have it accept a `str` pipeline parameter with no default argument (ie. it is positional argument from a python perspective).
1. Then create a run using that compiled pipeline from the UI leaving the field blank.

### What happened:

1. The run executes with `''` passed as the value for the input.

### What did you expect to happen:

1. Either it should error within the UI or,
1. (ideally) it should not pass the value at all (ie. default to `None`).

### Environment:

How did you deploy Kubeflow Pipelines (KFP)? We deploy KFP as a part of a wider KF v1.1 installation.
KFP version: v1.0.0
KFP SDK version: v1.0.0

### Anything else you would like to add:

/kind bug
/area frontend
/area backend
/area sdk

**Comment by Ark-kun** [comment]
> 1. Create a pipeline using to the `func_to_container_op`

Can you please elaborate on this. This sentence seems to mix information about pipeline and component definitions.

I think this is by design.

* It's invalid to not provide an argument for a non-optional input

"leaving the field blank" is indistinguishable form an empty string. Empty string is a valid string value.

It does not seem feasible to add a feature in the UX to stop passing some argument. All pipeline arguments are required. It's just that some of them have default values that are pre-populated in the UX.

>(ideally) it should not pass the value at all (ie. default to None).

I'm not sure this is generally possible. KFP orchestrates containerized command-line programs. In all operating system, command-line arguments are an array of strings. Can you explain how do you propose to pass `None` to a C++ command-line program?

P.S. Technically it could be possible to have pipelines with real optional inputs (passed to optional component inputs) and expose that in the UX. (This is different from what you're asking). But it's pretty hard to implement and does not seem to be a widely requested feature.
