### ISSUE TITLE
dsl-compile not able to take command line arguments

### ISSUE THREAD

**Issue by ajinkya933** [kubeflow/pipelines#4628]
### What steps did you take:
[A clear and concise description of what the bug is.]

I have following python script
[mnist_REST_API_temp.py](https://github.com/ajinkya933/Kubeflow/blob/master/mnist_REST_API_temp.py)

This script takes ```experiment_name``` as a command line argument . Normally I would run this script as 
```
python3   mnist_REST_API_temp.py myExperiment1
```
where myExperiment1 is my command line argument 

But when I run this file through dsl-combine I get this error: 

```
i$ dsl-compile --py mnist_REST_API_temp.py my_experiment --output yaml.yaml
/home/ajinkya/anaconda3/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.10) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
usage: dsl-compile [-h] [--py PY] [--function FUNCTION]
                   [--namespace NAMESPACE] --output OUTPUT
                   [--disable-type-check]
dsl-compile: error: unrecognized arguments: my_experiment
```
How do I make dsl-compile accept command line arguments ?

### What happened:
dsl-compile did not accept command line arguments 

### What did you expect to happen:
dsl-compile to accept command line arguments 

How did you deploy Kubeflow Pipelines (KFP)?
microk8s

**Comment by Ark-kun** [comment]
Please help me understand your issue.

dsl-compile does not support passing any command-line argument to the pipeline. That's because it's supposed to operate on a passive pipeline function. To compile it, not execute it.

If you want to run pipeline script with argument, you can just use python for that.

I've looked at the code and I'm not sure why it sets the `experiment_name` variable, since it's not used anywhere.

I'm also not sure what would be a possible use for that variable, since compiled pipelines have no information about experiments.

**Comment by HunterEl** [comment]
Also encountering this issue, @Ark-kun . I wrote a python script to take in command line args then generate a workflow. Once I started generating worfklows with KFP I started getting `error: unrecognized arguments`. Was able to step through the debugger and the exception occurs only when I call `compile`. I tried using `click` and `argparse` and issue is encoutered with both of them.

**Comment by ajinkya933** [comment]
There is no way to do this. The best alternative is to directly edit your yaml files too get a different output
