### ISSUE TITLE
Optional input artifacts not working

### ISSUE THREAD

**Issue by jackwhelpton** [kubeflow/pipelines#4701]
### What steps did you take:

Passed an output from a `dsl.Condition` block to a subsequent operation.

### What happened:

```
Unable to resolve: {{tasks.condition-1.outputs.artifacts.download-from-gcs-2-Data}}
```

### What did you expect to happen:
`None` to be passed to the subsequent component.

### Environment:

KFP version: 1.0.1
KFP SDK version: 
kfp                            1.0.3
kfp-server-api                 1.0.3

### Anything else you would like to add:
This seems very much like the following Argo issue:

https://github.com/argoproj/argo/issues/3491

for which a fix has been merged, is it possible to update the version of Argo used by KFP?

**Comment by Ark-kun** [comment]
It's a bit more complicated.
Currently, optional inputs are compile-time optional: You may connect them or leave them unconnected.

>None to be passed to the subsequent component.

This does not seem to be possible. At runtime, there is no Python and no `None`s. There are only command-lines. The command-lines are resolved at compile-time (most of it), so the `inputPath` placeholder must be resolved to something. It's resolved to a local path:
```
my_program --input1-path /tmp/input/input1/data
```
This cannot be changed at runtime.

What Argo can do is to not fail if the input is marked as optional when trying to download the data to the file. This file does not exist then.
Would that work for you?

Another issue is that currently the KFP's DSL compiler does not mark any artifacts as optional in Argo workflows. This can be fixed.
It will still not help you because the downstream components depend on upstream components. So when upstream is skipped, all downstream components are skipped as well. Overcoming this issue is non-trivial to design. Artifact aggregation support would have helped, but Argo does not support it yet. https://github.com/argoproj/argo/issues/934


P.S. Can you please tell us a bit more about your bigger scenario? I might think of a workaround.

**Comment by jackwhelpton** [comment]
Sure, the bigger scenario probably makes it clearer. I was hoping to write a training pipeline where a user could optionally supply a GCS location for a base model, in which case that model would be downloaded and used for transfer learning.

Currently the Python code for training deals exclusively with local paths, and if it is passed an empty string for the base model it will train from scratch.

One way I can think of addressing this is adding the gcloud SDK to the docker image containing the training code, and extending the component to download the file if required, handling the local path/empty string to feed to the Python code once the gsutil command has completed.

Initially, I had hoped to keep that component as a simple wrapper around the Python logic, using a standard component within a conditional to download the base model if required, but that manifests the above error, as if that download stage is skipped, the output is unresolved and can't be fed to the training step.

Does that make some sort of sense?

**Comment by jackwhelpton** [comment]
I should add, I realized I mangled my description of expectations by referring to `None`. What I'd hoped for was that `optional_step.output` would be an empty string, rather than a failure of (as I think you proposed above) a path to a non-existent file.

The former would let Python code say "oh, I shouldn't use this parameter", while the latter would/should be an error condition. As you'd suggested, we could group these together and say "if the file doesn't exist, assume a decision was made not to download it and use the base model instead", but logically that feels a bit off.

**Comment by nicokuzak** [comment]
> Sure, the bigger scenario probably makes it clearer. I was hoping to write a training pipeline where a user could optionally supply a GCS location for a base model, in which case that model would be downloaded and used for transfer learning.
> 
> Currently the Python code for training deals exclusively with local paths, and if it is passed an empty string for the base model it will train from scratch.
> 
> One way I can think of addressing this is adding the gcloud SDK to the docker image containing the training code, and extending the component to download the file if required, handling the local path/empty string to feed to the Python code once the gsutil command has completed.
> 
> Initially, I had hoped to keep that component as a simple wrapper around the Python logic, using a standard component within a conditional to download the base model if required, but that manifests the above error, as if that download stage is skipped, the output is unresolved and can't be fed to the training step.
> 
> Does that make some sort of sense?

@jackwhelpton did you end up figuring out how the optional parameters work here?

**Comment by susan-shu-c** [comment]
I'm curious about this as well!

**Comment by nicokuzak** [comment]
@susan-shu-c FYI it still works to leave inputs blank if you are using Vertex Pipelines GUI even though there is a red box in the UI for the parameters

**Comment by gabrielgcbs** [comment]
So anyone got a solution for that?

**Comment by shengy90** [comment]
My solution is a bit more convoluted but would love for pipeline components to support optional artifacts. The way I did this:

1. Say I have an optional input artifact Input[Model] (takes in a pretrained model and do something else on top if provided, otherwise train from scratch)

2. Create 2 versions of the pipeline component - one that takes in Input[Model] and one that doesn't

3. Write a wrapper class that can accept 'Model' as an optional input. If 'Model' is provided, call the component that takes in the optional Input[Model] artifact. If not, call the pipeline component that doesn't.

It's super clunky and ugly, but that's the best I could as components doesn't accept optional artifacts (None type object). I'm trying make my pipeline components reusable across many projects so that people don't have to code their own components/ abstract the complexities away from end users (hence my solution with a wrapper class).

**Comment by carlthome** [comment]
I was surprised that taking in an optional pretrained model doesn't seem to work. I thought this would compile to an optional input artifact.

```py
@dsl.component
def train_op(pretrained_weights: Optional[dsl.Model] = None):
    ...
```
but apparently it makes the input required.
