### ISSUE TITLE
How to compose parameters to components based on parameters to the pipeline

### ISSUE THREAD

**Issue by rafaelbarreto87** [kubeflow/pipelines#4776]
### What steps did you take:

I have a pipeline that receives a list parameter and uses that to compose a dictionary, which is then passed to a component that accepts a dict type. Here’s a minimum example:

```
def resolve_model_training_config(
    parameters: dict
):
    return None


resolve_model_training_config_comp = kfp.components.create_component_from_func(
    func=resolve_model_training_config,
    base_image=BASE_IMAGE
)


@kfp.dsl.pipeline(
    name='pipeline',
)
def model_training_pipeline(
    feats_dropout_rate: float=0.3,
    feats_to_dropout: list=["a", "b", "c"],
):  
    parameters = {
        'FEATS_DROPOUT_RATE': feats_dropout_rate,
        'FEATS_TO_DROPOUT': feats_to_dropout,
    }
    resolve_config_op = resolve_model_training_config_comp(
        parameters=parameters
    )
```

Unfortunately, running this fails with the following error:

```
usage: resolve_model_training_config [-h] --parameters PARAMETERS
resolve_model_training_config: error: argument --parameters: invalid loads value: '{"FEATS_DROPOUT_RATE": "0.3", "FEATS_TO_DROPOUT": "["a", "b", "c"]"}'
```

It seems KFP is just injecting a string json representation of `feats_to_dropout` into the serialized `parameters` without escaping, i.e. as if `parameters` were defined as:

```
{"FEATS_DROPOUT_RATE": "{{pipelineparam:op=;name=feats_dropout_rate}}", "FEATS_TO_DROPOUT": "{{pipelineparam:op=;name=feats_to_dropout}}"}
```

And then the json string corresponding to `feats_to_dropout` is just replaced directly into it. This means that we can’t really compose it like that because unfortunately the resulting string is not valid. Is there any workaround here? Basically, my goal is just to be able to create a parameters dict from the arguments passed to the pipeline that I can then pass to another component.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 1.0.0

KFP SDK version: 1.0.0

/kind question
/area sdk
-->

**Comment by Ark-kun** [comment]
There are two issues you're facing.
One issue is with pipeline parameter default values. It has bee fixed in https://github.com/kubeflow/pipelines/pull/3832
There was a pretty long delay in the releases, but the latest KFP SDK package has this fix.

Another issue is more fundamental. Argo (and KFP) does not have a concept or support of JSON substitutions.
Remember that KFP orchestrates command-line programs which do not in general have a concept of a dictionary. So, how is KFP supposed to pass a python dictionary to a C++ program?

>It seems KFP is just injecting a string json representation of feats_to_dropout into the serialized parameters without escaping

You're correct. KFP compiler does not escape the values, because the values do not exist at compile time. There is nothing to escape. The compiled workflow has the following: `{"FEATS_DROPOUT_RATE": "{{workflow.feats_dropout_rate}}", "FEATS_TO_DROPOUT": "{{workflow.feats_to_dropout}}"}`. When executing the workflow Argo has no knowledge that this string is supposed to be a valid JSON.

BTW, what do you expect to happen when the JSON is constructed from an output of a component and that output is a string which may be a serialized JSON string? How should the system know whether to unwrap the inner JSON or not?

What you want is not directly supported by the system. See related issues: https://github.com/kubeflow/pipelines/issues/4801 https://github.com/kubeflow/pipelines/issues/4802

However there are workarounds. You can just use the [json/Build dict](https://raw.githubusercontent.com/kubeflow/pipelines/616c48babede5cde4ef20b6c35cea24c66b1c44d/components/json/Build_dict/component.yaml) component.

```python
build_dict_op = load_component_from_utl('https://raw.githubusercontent.com/kubeflow/pipelines/616c48babede5cde4ef20b6c35cea24c66b1c44d/components/json/Build_dict/component.yaml')

    parameters_json = build_dict_op(
        key_1='FEATS_DROPOUT_RATE', value_1=feats_dropout_rate,
        key_2='FEATS_TO_DROPOUT', value_2=feats_to_dropout,
    )
```

Does this solve your problem?

**Comment by Udiknedormin** [comment]
@rafaelbarreto87 

Because you know all of the types, you know which parameters need escaping with `"` --- in your case none of them --- and therefore can do that instead of leaving it to the KFP engine:

```python
@kfp.dsl.pipeline(
    name='pipeline',
)
def model_training_pipeline(
    feats_dropout_rate: float=0.3,
    feats_to_dropout: list=["a", "b", "c"],
):  
    parameters = f"""{{
        "FEATS_DROPOUT_RATE": {feats_dropout_rate},
        "FEATS_TO_DROPOUT": {feats_to_dropout},
    }}"""
    resolve_config_op = resolve_model_training_config_comp(
        parameters=parameters
    )
```
__________

Now, let's get into details on WHY it works and what you did does not.

First : it seems to me your problem does NOT arise when your component is an inline `ContainerOp`:

```python
def pip_func(
    feats_dropout_rate: float=0.3,
    feats_to_dropout: list=["a", "b", "c"],
):  
    parameters = {
        "FEATS_DROPOUT_RATE": feats_dropout_rate,
        "FEATS_TO_DROPOUT": feats_to_dropout
    }
    op1 = ContainerOp(name='op', image='foo', command=['bar'], arguments=[parameters])
    op2 = load_component_from_file('component.yaml')(parameters)
```

```
  - name: op1
    container:
      args: ['{''FEATS_DROPOUT_RATE'': {{inputs.parameters.feats_dropout_rate}}, ''FEATS_TO_DROPOUT'':
          {{inputs.parameters.feats_to_dropout}}}']
      (...)
  - name: op2
    container:
      args: ['{"FEATS_DROPOUT_RATE": "{{inputs.parameters.feats_dropout_rate}}", "FEATS_TO_DROPOUT":
          "{{inputs.parameters.feats_to_dropout}}"}']
      (...)
```

^ notice no `"` around `PipelineParam` in the first case

As you correctly noticed, it's because KFP handles your input as `dict` / `JsonObject`, the serialiser of which is `_data_passing._serialize_json`:

```python
Converter([dict], ['JsonObject', 'Dictionary', 'Dict', 'dict'], _serialize_json, 'json.loads', 'import json'),
```

```python
def _serialize_json(obj) -> str:
    if isinstance(obj, str):
        return obj
    import json
    def default_serializer(obj):
        if hasattr(obj, 'to_struct'):
            return obj.to_struct()
        else:
            raise TypeError("Object of type '%s' is not JSON serializable and does not have .to_struct() method." % obj.__class__.__name__)
    return json.dumps(obj, default=default_serializer, sort_keys=True)
```

Please note that the above ALWAYS returns a valid json, so it's not even possible to create `"{ "FEATS_DROPOUT_RATE": {{pipelineparam:op=;name=feats_dropout_rate}}, "FEATS_TO_DROPOUT": {{pipelineparam:op=;name=feats_dropout}} }"`, which is the value you'd expect to have here.

Because `PipelineParam` isn't supported by `json.dumps` via simple means, `default_serializer`, defined above, is run on it and its `to_struct` method is called:

```python
  def to_struct(self):
    # Used by the json serializer. Outputs a JSON-serializable representation of the object
    return str(self)
```

Notice: it does NOT depend on the `PipelineParam`'s `param_type` field. In your case, `param_type` is `float` and `list`. Technically, your `PipelineParam`'s type COULD be included and therefore produce what I proposed here as a manual solution.

@Ark-kun It seems to me that it's a thing that could be done on KFP compiler level, provided `PipelineParam` does have its `param_type` specified and its json representation is known. If we searched the `dict`'s fields (recursively) for all `"{{pipelineparam:op=...;name=...}}"`` and replaced the ones with specified non-string json type with the un-string-escaped variants, we could get:

```python
# 1
{
  "FEATS_DROPOUT_RATE": feats_dropout_rate,
  "FEATS_TO_DROPOUT": feats_to_dropout
}

# 2
"""
{
  "FEATS_DROPOUT_RATE": "{{pipelineparam:op=;name=feats_dropout_rate}}",
  "FEATS_TO_DROPOUT": "{{pipelineparam:op=;name=feats_to_dropout}}"
}
"""

# 3

```
