### ISSUE TITLE
Cached pipeline step should reset the node selector

### ISSUE THREAD

**Issue by gcampax** [kubeflow/pipelines#4777]
### What steps did you take:
Create a pipeline step, and set a node selector that restricts the execution of that step only on certain nodes (in my case, on certain GPU nodes, by EC2 instance type).
Run the pipeline once, so the step is cached.
Run the pipeline again.

### What happened:
KFP recognized that the pipeline step was cached, and replaced the pod with a dummy pod that prints "This step is taken from cache.". The resource requests for that pod were reset to nothing, but the node selector was not removed. Hence, the pod still triggered autoscaling of a GPU node, waited until the GPU node was ready, was scheduled, and then immediately exited. This increases latency and wastes money as cluster-autoscaler has some latency in taking down unused nodes.

### What did you expect to happen:
The new pod has no node selector, and is scheduled anywhere, as it is a dummy pod with no effect.

### Environment:
How did you deploy Kubeflow Pipelines (KFP)?
AWS installation guide for Kubeflow.

KFP version: 1.0.0

/kind bug
/area backend

**Comment by Ark-kun** [comment]
I'm not sure this is a bug (caching makes the execution almost instantaneous), but this might be a nice feature to have.

We're somewhat afraid to add some features, because the proposed behavior violates some customizations that come from the user.

The situation could be the opposite: The user could have a cheap preemptible node pool where they schedule most of the tasks. But when node selector is removed, the pod is scheduled on some node pool, taking up the resources.

How should we know the user's intent?

Also, what are similar pod attributes that you think need to be removed from the dummy re-used pod?

**Comment by gcampax** [comment]
Well, the dummy pod takes no resources, both in terms of K8s resources and in practice, so I don't quite see your concern. It should be possible to schedule it anywhere. I really cannot see a use case where the user really wants to spin up a fresh machine in a dedicated pool to run the dummy pod.

Any pod properties related to scheduling should be removed, in my opinion. That would be node selector, node affinity, pod affinity.

**Comment by NikeNano** [comment]
/assign

I will take a look at this.

**Comment by NikeNano** [comment]
https://github.com/kubeflow/pipelines/pull/5456
