### ISSUE TITLE
[Testing] cache sample failure did not fail postsubmit

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#4839]
The test https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow-pipeline-postsubmit-integration-test/1332269653426180096 passed, but it shows caching sample failed from junit logs.

When looking at the caching sample pod log, it is indeed failing:
https://storage.googleapis.com/kubernetes-jenkins/logs/kubeflow-pipeline-postsubmit-integration-test/1332269653426180096/artifacts/pods_info/sample-test-lbbl8-2775615982.txt

> [0;31mRuntimeError\u001b[0m: The cached execution was not re-used or pipeline run took to long to complete.

/assign @Ark-kun

**Comment by Ark-kun** [comment]
Are those the correct logs? I'm trying to find the error message.

**Comment by Ark-kun** [comment]
Maybe this is related to the fact that I had to change the sample from code file to a notebook. TBH, we might want to spend some resources on improving the sample test capabilities, so that it's easier to add more tests.

https://github.com/kubeflow/pipelines/issues/4844
https://github.com/kubeflow/pipelines/issues/4602

**Comment by Bobgy** [comment]
I saw the error message on
https://cloudlogging.app.goo.gl/73Cvb3kHH3qd1rCr7
