### ISSUE TITLE
Add in support for podSpecPatch

### ISSUE THREAD

**Issue by alexlatchford** [kubeflow/pipelines#4877]
Often defining CPU/Mem/GPU resources at compile time is too inflexible. This is especially important if when you deploy your pipeline into different environments you may be sending through smaller datasets to expedite testing and want to recoup hardware costs as we no longer require such large machines.

To do this with Argo they have implemented `podSpecPatch` but this is not exposed in `kfp`, see their examples:
* https://github.com/argoproj/argo/blob/master/examples/pod-spec-from-previous-step.yaml
* https://github.com/argoproj/argo/blob/master/examples/pod-spec-patch.yaml
* https://github.com/argoproj/argo/blob/master/examples/pod-spec-yaml-patch.yaml
* https://github.com/argoproj/argo/blob/master/examples/pod-spec-patch-wf-tmpl.yaml

Not clear to me the exact syntax changes to the KFP DSL that'd be required to support this but from our perspective the per-template injection of resources is likely the most important, either from a [prior step](https://github.com/argoproj/argo/blob/master/examples/pod-spec-from-previous-step.yaml) or via a [pipeline parameter](https://github.com/argoproj/argo/blob/master/examples/pod-spec-patch.yaml).

/area sdk
/kind feature

**Comment by zijianjoy** [comment]
Similar feature request: https://github.com/kubeflow/pipelines/issues/1956.

**Comment by Bobgy** [comment]
Are there use-cases other than https://github.com/kubeflow/pipelines/issues/1956: use resource request based on PipelineParam?

**Comment by zrlaida** [comment]
@Bobgy the solution in #1956 is not general and does not work for other resources than memory and cpu.
Argo supports podSpecPatch also for gpu parameters see https://github.com/argoproj/argo-workflows/issues/3058
while kfp only for memory and cpu probably because of this if

https://github.com/kubeflow/pipelines/blob/b7d4b1ba7cb04e7247ade93cca02044103217faa/sdk/python/kfp/compiler/_op_to_template.py#L296

That condition makes not possible to use directly neither `add_resource_request` nor `add_resource_limit` for all other resources.

This means that the solution in #1956 is not general.

In addition to this several other functions do not support PipelineParam in the input. For example 
https://github.com/kubeflow/pipelines/blob/b7d4b1ba7cb04e7247ade93cca02044103217faa/sdk/python/kfp/dsl/_container_op.py#L362 when the input is a PipelineParam crashes during validation.

I think that if Argo supports the settings of resources at runtime this must be as well supported in kfp but this is not currently the case.

**Comment by zrlaida** [comment]
@NikeNano can you please have a look at this?

**Comment by NikeNano** [comment]
I make a fix @zrlaida to add settings for GPU resources at runtime.
