### ISSUE TITLE
Persistence agent delays syncing workflow in the db and UI lags

### ISSUE THREAD

**Issue by elikatsis** [kubeflow/pipelines#4886]
### What steps did you take:
Submit a run

### What happened:
Sometimes the workflow is running (or even completes) but the UI took very long time to load it (2-5 mins)

### What did you expect to happen:
The UI to be always in sync with the run's state

### Anything else you would like to add:

The UI draws exactly what it finds in the database, but it seems like the database is empty.
It is the persistence agent who is responsible to sync the workflow (aka the run's state) in the database.

However:

* The persistence agent uses a rate limiting workqueue with an exponential delay rate limiter ([source](https://github.com/kubeflow/pipelines/blob/04d5e609f224d7be2e8bfc20a3fa7857906cae1c/backend/src/agent/persistence/worker/persistence_worker.go#L68-L69))
* The queue has a base delay of 10 seconds, maxing out to 360 seconds ([source](https://github.com/kubeflow/pipelines/blob/04d5e609f224d7be2e8bfc20a3fa7857906cae1c/backend/src/agent/persistence/worker/persistence_worker.go#L30-L35)).
  This is the mathematical equation that decides the delay:
  ```
  delay = 10 * 2^num_failures
  ```
  [Note that [this comment](https://github.com/kubeflow/pipelines/blob/04d5e609f224d7be2e8bfc20a3fa7857906cae1c/backend/src/agent/persistence/worker/persistence_worker.go#L178) is wrong]
* The number of failures is incremented every time the agent attempts to enqueue the object: [event handler](https://github.com/kubeflow/pipelines/blob/04d5e609f224d7be2e8bfc20a3fa7857906cae1c/backend/src/agent/persistence/worker/persistence_worker.go#L116), [failure during item processing](https://github.com/kubeflow/pipelines/blob/04d5e609f224d7be2e8bfc20a3fa7857906cae1c/backend/src/agent/persistence/worker/persistence_worker.go#L196)
  This is because limiter's [`When()`](https://github.com/kubernetes/client-go/blob/73fd2ddc918095ed6a4da2073b2f79e7721cf44b/util/workqueue/default_rate_limiters.go#L89-L108) method increments the failures, and it is called even when the object doesn't get actually added in the queue (e.g., if it already is in the queue):
  1. The agent calls [`AddRateLimited()`](https://github.com/kubernetes/client-go/blob/73fd2ddc918095ed6a4da2073b2f79e7721cf44b/util/workqueue/rate_limiting_queue.go#L58-L61), which calls `AddAfter(item, limiter.When(item))`
  2. [`AddAfter()`](https://github.com/kubernetes/client-go/blob/73fd2ddc918095ed6a4da2073b2f79e7721cf44b/util/workqueue/delaying_queue.go#L149-L170): adds `item` in the queue after duration `duration`
  3. [`Add()`](https://github.com/kubernetes/client-go/blob/73fd2ddc918095ed6a4da2073b2f79e7721cf44b/util/workqueue/queue.go#L107-L127): adds `item` in the queue if it's not already in it

#### So, what's happening?

Now that we know exactly when and how the delays are decided, the question is why do we get such huge delays.

Adding a few logs here and there we can see that the persistence agent has an event handler ([source](https://github.com/kubeflow/pipelines/blob/04d5e609f224d7be2e8bfc20a3fa7857906cae1c/backend/src/agent/persistence/worker/persistence_worker.go#L77-L84)). which calls [`enqueue()`](https://github.com/kubeflow/pipelines/blob/04d5e609f224d7be2e8bfc20a3fa7857906cae1c/backend/src/agent/persistence/worker/persistence_worker.go#L105-L120) when an object is added (`AddFunc`) as well as when an object is updated `UpdateFunc`).

From the [documentation](https://pkg.go.dev/k8s.io/client-go/tools/cache@v0.0.0-20191225075139-73fd2ddc9180#ResourceEventHandler) we find this:
>* OnAdd is called when an object is added.
>* OnUpdate is called when an object is modified. Note that oldObj is the
    last known state of the object-- it is possible that several changes
    were combined together, so you can't use this to see every single
    change. OnUpdate is also called when a re-list happens, and it will
    get called even if nothing changed. This is useful for periodically
    evaluating or syncing something.

This `enqueue()` method adds the workflow in the queue using `AddRateLimited()`, triggering the exponential increase.
However, it doesn't make sense to use `AddRateLimited()` since we should need the exponential delay **only when something is failing**.

Here are the logs we added (`NumRequeues` is the number of failures which are part of the computation of the exponential delay):
```
time="2020-10-27T19:41:14Z" level=info msg="========== EVENT_HANDLER.UpdateFunc =========="
time="2020-10-27T19:41:15Z" level=info msg="ENQUEUE:: Key: kubeflow-user/dog-breed-r0p46-9gkwx, NumRequeues: 0"
time="2020-10-27T19:41:15Z" level=info msg="========== EVENT_HANDLER.UpdateFunc =========="
time="2020-10-27T19:41:15Z" level=info msg="ENQUEUE:: Key: kubeflow-user/dog-breed-r0p46-9gkwx, NumRequeues: 1"
time="2020-10-27T19:41:16Z" level=info msg="========== EVENT_HANDLER.UpdateFunc =========="
time="2020-10-27T19:41:16Z" level=info msg="ENQUEUE:: Key: kubeflow-user/dog-breed-r0p46-9gkwx, NumRequeues: 2"
time="2020-10-27T19:41:17Z" level=info msg="========== EVENT_HANDLER.UpdateFunc =========="
time="2020-10-27T19:41:17Z" level=info msg="ENQUEUE:: Key: kubeflow-user/dog-breed-r0p46-9gkwx, NumRequeues: 3"
time="2020-10-27T19:41:19Z" level=info msg="========== EVENT_HANDLER.UpdateFunc =========="
time="2020-10-27T19:41:19Z" level=info msg="ENQUEUE:: Key: kubeflow-user/dog-breed-r0p46-9gkwx, NumRequeues: 4"
time="2020-10-27T19:41:21Z" level=info msg="========== EVENT_HANDLER.UpdateFunc =========="
time="2020-10-27T19:41:21Z" level=info msg="ENQUEUE:: Key: kubeflow-user/dog-breed-r0p46-9gkwx, NumRequeues: 5"
time="2020-10-27T19:41:22Z" level=info msg="========== EVENT_HANDLER.UpdateFunc =========="
time="2020-10-27T19:41:22Z" level=info msg="ENQUEUE:: Key: kubeflow-user/dog-breed-r0p46-9gkwx, NumRequeues: 6"
time="2020-10-27T19:41:25Z" level=info msg="========== EVENT_HANDLER.UpdateFunc =========="
time="2020-10-27T19:41:25Z" level=info msg="ENQUEUE:: Key: kubeflow-user/dog-breed-r0p46-9gkwx, NumRequeues: 7"
time="2020-10-27T19:41:25Z" level=info msg="PROCESS_WORK_ITEM:: Obj: kubeflow-user/dog-breed-r0p46-9gkwx, NumRequeues(obj): 8, NumRequeues(key): 8"
```

So this is what we are probably hitting:
1. The workflow `Informer` provides the agent with a workflow to process
2. The agent starts processing the workflow
3. Multiple updates on the workflow trigger the object to be requeued multiple times (incrementing the number of requeues, aka failures)
4. The processing of the workflow fails because of some transient error (Istio transport closing)
5. The agent adds the workflow back in the queue, with the exponential delay of `X` failures (`X = num_updates + 1`)

/kind bug

**Comment by elikatsis** [comment]
I'll be opening a PR very soon fixing this behavior

/cc @Bobgy

**Comment by Bobgy** [comment]
/assign @capri-xiyue 
I think it's a good issue for you to follow up

**Comment by capri-xiyue** [comment]
Rate Limit can also be used to avoid hot loop. I'm not sure why at first we use enforceRequeueDelays for persistent agent. Will it cause performance issues when there are too many work items in the work queue? Any backgound info @Bobgy
If we think the delay is too much, in our code, the base delay is 10 seconds. Based on the book programming kubernetes, https://www.google.com/books/edition/Programming_Kubernetes/6VKjDwAAQBAJ?hl=en&gbpv=1&bsq=work%20queue. Most controllers will just use the DefaultControllerRateLimiter() whose exponential back-ff starting at 5ms and going up to 1000 seconds.`

If we think the 10 seconds delay is too much, I think we follow the behavior of DefaultControllerRateLimiter() ti change the exponential back-ff starting at 5ms.

**Comment by capri-xiyue** [comment]
assign @Bobgy  I need background info regarding whether we should  add exponential delays in non-error mode.

**Comment by elikatsis** [comment]
Hello @Bobgy, @capri-xiyue. Sorry for the delayed answer (twas the holidays :smile: )
Continuing the discussion from [this comment](https://github.com/kubeflow/pipelines/pull/4887#discussion_r549485704) which @capri-xiyue copied above.

From the logs in my first comment, the workflow is pushed to the queue quite often. This allows us to assume that someone triggers workflow updates. I think pod updates may trigger this since they have an owner reference specifying the workflow as `controller: true`, but also it's the controller itself that updates the workflow's status according to pod changes.

We have been [testing and] deploying this for quite some time now, even with big loads, and we haven't encountered performance issues. It'd be great if you tested this as well.

What we have repeatedly seen, though, is the UI showing everything stuck for 5 minutes [while all is running smoothly] and then immediately present a successful run. This is terrible UX, right?

I think changing the base of the exponential backoff will make a change but not a great one. According to the logs, showing the frequency the methods are called, we may still bump into big delays if the workflow keeps being enqueued for whatever reason. The change may be something like a 2-3 minute delay instead of a 5 minute one. I strongly believe we shouldn't go down that road.

**Comment by capri-xiyue** [comment]
It looks like the `update` will be triggered every time when the step of workflow gets updated which is quite often. And the we don't need to sync so often. That's one reason why we have exponential delay in non-error mode at first. And based on the comment of the code https://github.com/kubeflow/pipelines/blob/master/backend/src/agent/persistence/worker/persistence_worker.go#L47, we have rate-limited work queue is to `ensure we only process a fixed amount of resources at a
and makes it easy to ensure we are never processing the same item simultaneously in two different workers.`  It looks like we have this rate-limited work queue to avoid the queue will get overloaded by huge number of work items since the update will be quite often. The comment also hinted that we will encounter issues when we processing the same item simultaneously in two different workers. It looks like we still need to keep rate-limited  work queue considering the above concerns. I'm not sure whether the use cases have changed or not. @Bobgy Do you have any more background info about these?

I agree that the UI showing everything stuck for 5 minutes [while all is running smoothly] and then immediately present a successful run is a terrible UX and we should fix it or mitigate it.

Every time when we enqueue the object, we will enqueue the key of the object which usually is the `namespace/name` [enqueue source](https://github.com/kubeflow/pipelines/blob/c8c9905bf2b2662a851c339afbd143cfdbdb603c/backend/src/agent/persistence/worker/persistence_worker.go#L111).
And when we process the item in the work queue, it will try to fetch the latest state of the workflow [source]https://github.com/kubeflow/pipelines/blob/c8c9905bf2b2662a851c339afbd143cfdbdb603c/backend/src/agent/persistence/worker/swf_saver.go#L41l) and save it to the database. 
So it doesn't matter whether when we enqueue the object which goes to running stage or complete stage. We will save the the workflow to database even though the key is enqueued by an update of a step as long as at that time when we get the key out of the queue and fetch the workflow via client, the state of workflow is running or complete.
Therefore, I think the Persistence agent delays syncing workflow in the db and UI lags should be kind of rare.
If we want to mitigate the problem, I think it will be better if we change the base of the exponential backoff or we change it to constant delays. As far as I can see, I prefer constant delays.

**Comment by capri-xiyue** [comment]
@Bobgy When we discussed offline, you suggested that we can do some hack to figure out the object we try to enqueue is related to some final state or not, if it is related to some final state, we should add that key of the object into the queue immediately. As I go through the code, we find our persistent agent handles two object `workflow` and `ScheduledWorkflow`, and the object that the resource handler pass is type `interface{}`. If we want to do the hack, we have to figure out which object the resource handler pass and put the business logic of specific object into the enqueue logic which is kind of general. And every time when we want to add some new object that the persistent agent handle, the logic may break. Therefore, to mitigate the Persistence agent delays, I'd prefer to change the base of the exponential backoff or we change it to constant delays.

**Comment by elikatsis** [comment]
@capri-xiyue Thanks for digging into it!

Constant delays sound a bit better but still, it is on us to decide a (probably) slow refresh rate.
We could do exponential with a small number as base (e.g. 5ms, as you suggested) and a small maximum delay (e.g., 5 seconds?).
How does that sound? Does any of you have anything in mind as a burden for such small maximum delays?

I don't get this proposal:
>we can do some hack to figure out the object we try to enqueue is related to some final state or not, if it is related to some final state, we should add that key of the object into the queue immediately

This will also make the system stuck and the run to pop when it gets to a final state. This still is bad UX.

Of course it also comes with the technical difficulties you mention.

**Comment by capri-xiyue** [comment]
@elikatsis You are right, the proposal of the hack will still make the system stuck and the run to pop when it gets to a final state. 
Regarding the setting of delay, I think 5ms is too often considering the use cases of kubeflow pipelines. (5ms is usually used in non-error mode) It looks like the update of workflow is very often based on the workflow and every time when the persistent agent sync the workflow successfully, it will call `Forget()`[source](https://github.com/kubeflow/pipelines/blob/c8c9905bf2b2662a851c339afbd143cfdbdb603c/backend/src/agent/persistence/worker/persistence_worker.go#L211) which will clear `rateLimiter. So I don't think in our cases, the rateLimiter will go to 360 seconds in non-error mode since every time when we successfully sync the workflow, we will clear the `rateLimiter`. Therefore, I doubt whether the delay of 5 mins will happen in non-error mode. In theory, it should be quite rare.  By the way, the exponential delay is also used in error-mode. If we change it too often, we may encounter hot loop issues in error mode.

I prefer we use constant delays in non-error mode and exponential delay in error mode. For constant delays, I'm not sure whether 30 seconds is ok? If we set the delay too short in non-error mode, I'm not sure the work queue will be overloaded.

**Comment by capri-xiyue** [comment]
I submitted another PR to https://github.com/kubeflow/pipelines/pull/4957 to fix the issue
FYI @elikatsis 
I checked the logs, the change of base delay works.
```
+ ml-pipeline-persistenceagent-6bd54697c6-kbd9v › ml-pipeline-persistenceagent
ml-pipeline-persistenceagent-6bd54697c6-kbd9v ml-pipeline-persistenceagent time="2021-01-06T05:21:39Z" level=info msg="Syncing object:: Key: kubeflow/conditional-execution-pipeline-with-exit-handler-ngmdj"
ml-pipeline-persistenceagent-6bd54697c6-kbd9v ml-pipeline-persistenceagent time="2021-01-06T05:21:40Z" level=info msg="Syncing object:: Key: kubeflow/conditional-execution-pipeline-with-exit-handler-ngmdj"
ml-pipeline-persistenceagent-6bd54697c6-kbd9v ml-pipeline-persistenceagent time="2021-01-06T05:21:41Z" level=info msg="Syncing object:: Key: kubeflow/conditional-execution-pipeline-with-exit-handler-ngmdj"
ml-pipeline-persistenceagent-6bd54697c6-kbd9v ml-pipeline-persistenceagent time="2021-01-06T05:21:43Z" level=info msg="Syncing object:: Key: kubeflow/conditional-execution-pipeline-with-exit-handler-ngmdj"
ml-pipeline-persistenceagent-6bd54697c6-kbd9v ml-pipeline-persistenceagent time="2021-01-06T05:21:45Z" level=info msg="Syncing object:: Key: kubeflow/conditional-execution-pipeline-with-exit-handler-ngmdj"
ml-pipeline-persistenceagent-6bd54697c6-kbd9v ml-pipeline-persistenceagent time="2021-01-06T05:21:46Z" level=info msg="Syncing object:: Key: kubeflow/conditional-execution-pipeline-with-exit-handler-ngmdj"
ml-pipeline-persistenceagent-6bd54697c6-kbd9v ml-pipeline-persistenceagent time="2021-01-06T05:21:47Z" level=info msg="Syncing object:: Key: kubeflow/conditional-execution-pipeline-with-exit-handler-ngmdj"
ml-pipeline-persistenceagent-6bd54697c6-kbd9v ml-pipeline-persistenceagent time="2021-01-06T05:21:48Z" level=info msg="Syncing object:: Key: kubeflow/conditional-execution-pipeline-with-exit-handler-ngmdj"
ml-pipeline-persistenceagent-6bd54697c6-kbd9v ml-pipeline-persistenceagent time="2021-01-06T05:21:49Z" level=info msg="Syncing object:: Key: kubeflow/conditional-execution-pipeline-with-exit-handler-ngmdj"
ml-pipeline-persistenceagent-6bd54697c6-kbd9v ml-pipeline-persistenceagent time="2021-01-06T05:21:50Z" level=info msg="Syncing object:: Key: kubeflow/conditional-execution-pipeline-with-exit-handler-ngmdj"

```

**Comment by capri-xiyue** [comment]
> By the way, I think same item won't be simultaneously handled in two different workers because of the `processing set` [source](https://github.com/kubernetes/client-go/blob/0d3f257a17bb46ce0d7f022e257e3cbcd01ff5cb/util/workqueue/queue.go#L84) in the work queue logic. Please correct me if I'm wrong.

I took a look at the code again.I think `processing set` [source](https://github.com/kubernetes/client-go/blob/0d3f257a17bb46ce0d7f022e257e3cbcd01ff5cb/util/workqueue/queue.go#L84) can't prevent same item from being simultaneously handled in two different workers because of the in the work queue logic since it won't throw error when you try to insert a existed item into the processing set
