### ISSUE TITLE
Pipeline runs are disappearing

### ISSUE THREAD

**Issue by kd303** [kubeflow/pipelines#4997]
### What steps did you take:
Pipeline runs disappears when executing pipeline using SDK. When we run the pipeline for a specific experiments, we are able to see the logs appearing in pods as well the runid (UUID) is also getting generated. I have done tracking in mysql/mlpipeline/run_details table and can also see run appearing there.

However in some cases after above observations the run gets disapper from mysql and UI and nothing appearing in the UI

### What did you expect to happen:
Usually this is observed when the Pods are getting initialized, and for same pipeline the run works sometime
### Environment:

KFP 1.1 on a local Kubernetes cluster
How did you deploy Kubeflow Pipelines (KFP)?

Full kubeflow deployment, on premise cluster

KFP version: 1.0 

KFP SDK version: 1. 

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

/area backend

**Comment by zijianjoy** [comment]
Hello @kd303, I need more information in order to reproduce this issue. Based on the description, this happens when Pods are getting initialized. But Pods should be up and running when triggering a pipeline run. Did you uninstall KFP instance and redeploy before the issue happens?

To further investigate this issue, would you like to answer the followings:
1. Reproduce steps in more detail: What tools you are using for local cluster deployment? What steps have been taken from beginning? 
2. Does it happen to all pipelines you create, or does it happen to specific pipeline? Can you share a sample of pipeline for reproducing the issue?

**Comment by kd303** [comment]
After lot of runs and debugging we realize that 'delete run' has been triggering. I am documenting this for anyone else.

We have been using APIs to automtically running our pipeline as well checking the status of the same. Now when the runs are longer then status check intervals, we saw in our code we are authenticating the user to make the API call every single time and when second time the authentication is done to check the status, it seems the runs were disappearing. for now we have changed the design to use Exit handlers for status updates (to an external tool where the dashboards are created for users) instead of using the status check APIs. 

Just documenting for others in case they face similar issue, although I am bit puzzled at this point as to why delete run has been triggering second time.
