### ISSUE TITLE
[FR] Support namespaced pipelines from the UI

### ISSUE THREAD

**Issue by StefanoFioravanzo** [kubeflow/pipelines#5084]
Given the backend support of namespaced pipelines (https://github.com/kubeflow/pipelines/pull/4835), we can use this issue to discuss how to bring this feature to the UI as well. We (Arrikto) will start working on this soon and provide updates here for discussion.

cc @Bobgy @yanniszark @elikatsis @maganaluis

**Comment by Bobgy** [comment]
Part of https://github.com/kubeflow/pipelines/issues/5084

**Comment by Bobgy** [comment]
A summary of previous discussion,

Do we all agree on key criteria for this feature?
* p0 being backward-compatible (e.g. if user stays in non-separation mode for pipelines, they should still be able to do what they want).
* p0 allow users to upload to shared/non-shared
* p0 allow users to list/select from shared/non-shared pipelines using a switch/tabs
* p1 allow a configuration to disable shared pipelines from both API & UI

**Comment by toshi-k** [comment]
@StefanoFioravanzo How is your situation for this issue ? Do you work on this internally ?

**Comment by StefanoFioravanzo** [comment]
Hey @toshi-k we will start working on this soon!

**Comment by Bobgy** [comment]
Latest status for the backend API implementation is summarized in https://github.com/kubeflow/pipelines/issues/4197#issuecomment-900821642

**Comment by d-gol** [comment]
Hello, and thanks for implementing this in backend! Completing this feature in frontend would be really useful for us. Along with the potential implementation of [namespaced artifacts](https://github.com/kubeflow/pipelines/issues/4649), it would provide complete isolation of resources. 

Since we work with different users, they would like to have complete control over the resources they submit (pipeline, runs, experiments, artifacts). 

Any chance this feature can be prioritized in the following months?

**Comment by zijianjoy** [comment]
cc @jbottum , who has also raised the same request during Kubeflow Pipelines community meeting this week.

**Comment by juliusvonkohout** [comment]
> cc @jbottum , who has also raised the same request during Kubeflow Pipelines community meeting this week.

Is there any progress made regarding the frontend issue?
