### ISSUE TITLE
kfp.compiler.Compiler.compile() failed with Bazel due to kfp.CHECK_TYPE not found

### ISSUE THREAD

**Issue by yzhang5471** [kubeflow/pipelines#5087]
### What steps did you take:
I use Bazel to compile the pipeline. It has been working for `kfp==1.0.0` but failed for `kfp>=1.1.2`.

### Environment:
python==3.8.5
bazel==3.2.0

KFP SDK version: `kfp==1.1.2` as well as `kfp==1.3.0`

### Anything else you would like to add:
Traceback from `kfp==1.1.2`
```python
.../pypi_kfp/kfp/compiler/compiler.py", line 917, in compile
    type_check_old_value = kfp.TYPE_CHECK
AttributeError: module 'kfp' has no attribute 'TYPE_CHECK'
```
I suspect that the pkgutil style namespace packaging breaks the import (at least in Bazel)
https://github.com/kubeflow/pipelines/blob/1.1.2/sdk/python/kfp/__init__.py#L17

/kind bug
/area sdk

**Comment by chensun** [comment]
The pkgutil-style namespace packages was introduced to turn the existing package into a namespace package, so that [kfp-pipeline-spec](https://github.com/kubeflow/pipelines/tree/master/api/v2alpha1/python/kfp/pipeline_spec) can share the same namespace `kfp` while it's published as a separate package.

This has been working for non-bazel use case, so not sure if this might be a bazel issue. 

Long term, we do plan to merge `kfp-pipeline-spec` back into `kfp`, by that time, we can revert the pkgutil-style namespace package.

**Comment by greggdonovan** [comment]
@chensun We're running into this issue trying to compile our KFP pipeline with Bazel. Have there been any updates or is there a workaround we might try?

**Comment by cristifalcas** [comment]
This error comes from 2 things:
- rules_python adds an [`__init__.py`](https://github.com/bazelbuild/rules_python/blob/888fa20176cdcaebb33f968dc7a8112fb678731d/python/pip_install/extract_wheels/lib/namespace_pkgs.py#L73-L85) for each module
- `kfp` module depends on [kfp-pipeline-spec](https://pypi.org/project/kfp-pipeline-spec/#files), which has a folder `kfp`

Rules python will make that `kfp` folder from `kfp-pipeline-spec` a module and, after that, python will try to load 'TYPE_CHECK' from there and everything fails.

As a workaround you need to delete the generated `__init__.py` file from bazel path.

Something like this before loading the kfp module:

```py
import sys

for module_path in sys.path:
    if module_path.endswith("nameused_kfp_pipeline_spec"):
        os.remove(f"{module_path}/kfp/__init__.py")
```

replace the path with whatever you have named your pip_parse/pip_install call in WORKSPACE.

Or open an issue with rules_python for a proper fix

**Comment by pyang-aurora** [comment]
Given that the original goal for adopting namespace package style is to ensure the protobuf generated python modules can be accessed under the same kfp namespace, would it be possible to bundle them at release time?

**Comment by cnsgsz** [comment]
I also ran into the same issue. It shows up as `kfp.__version__` does not exist, as `kfp` points to the one under `kfp_pipeline_spec`.

It seems incorrect to me that `kfp` and `kfp_pipeline_spec` have different `__init__.py`:
```
$ cat pip_parsed_deps_kfp/site-packages/kfp/__init__.py 
# Copyright 2018-2022 The Kubeflow Authors
#
...
# `kfp` is a namespace package.
# https://packaging.python.org/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages
__path__ = __import__('pkgutil').extend_path(__path__, __name__)

__version__ = '2.0.1'

TYPE_CHECK = True

from kfp import dsl
from kfp.client import Client

swang@swang-carbon10:~/CLionProjects/moffett/bazel-bin/garage/pipeline.runfiles$ cat pip_parsed_deps_kfp_pipeline_spec/site-packages/kfp/__init__.py 
# __path__ manipulation added by bazelbuild/rules_python to support namespace pkgs.
__path__ = __import__('pkgutil').extend_path(__path__, __name__)
```
According to[ python's documentation](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages),
```
Every distribution that uses the namespace package must include an identical __init__.py. If any distribution does not, it will cause the namespace logic to fail and the other sub-packages will not be importable. Any additional code in __init__.py will be inaccessible.
```

A fix would be to remove the extra imports etc from `kfp`'s `__init__.py`, or add exactly the same ones to `kfp_pipeline_spec`'s. It would be hard to have bazel add the same `__init__.py` between the two packages.

@cristifalcas Does your fix work? It seems to me removing `kfp_pipeline_spec`'s `__init__.py` will prevent it from being recognized as a module and imported?

**Comment by cristifalcas** [comment]
@cnsgsz I don't believe we use this hack right now, but it was working correctly, so I still expect it to work?

**Comment by chensun** [comment]
> A fix would be to remove the extra imports etc from `kfp`'s `__init__.py`, or add exactly the same ones to `kfp_pipeline_spec`'s. It would be hard to have bazel add the same `__init__.py` between the two packages.

@cnsgsz Removing the extra imports from `kfp`'s `__init__.py` is a breaking change affects all users, while those extra imports cannot be added to `kfp_pipeline_spec`'s, as they are not available to `kfp_pipeline_spec`, which is an independent sub-package.

The difference in `__init__.py` files is proven to be working just fine for the users, `bazel` is the only scenario it might not be compatible, though not verified. 

At this moment, the KFP team has no plan to support `bazel` as as a building tool. In fact, `bazel` was deprecated from our repo from a long time ago (https://github.com/kubeflow/pipelines/issues/3250).

@cristifalcas in the [above](https://github.com/kubeflow/pipelines/issues/5087#issuecomment-1096879641) mentioned a workaround and pointed out the underlying issue is likely [rules_python](https://github.com/bazelbuild/rules_python).

**Comment by cnsgsz** [comment]
@cristifalcas : do you know what changed? why don't you need the hack anymore?

@chensun:
I understand the difficulty in making it backward compatible etc, though I'm still not convinced that the underlying issue is rules_python. Even without rules_python, namespace packages need to include identical init files, per the python doc I  quoted above?

Will it be possible to merge pipeline spec into kfp as suggested [earlier in the thread](https://github.com/kubeflow/pipelines/issues/5087#issuecomment-1040721497)? 

I use bazel to work with python, c++ etc, just as in tensorflow etc. I understand that google internally uses something similar to bazel. What build tool would you recommend in open source if not bazel? What does kfp use without bazel?

**Comment by cristifalcas** [comment]
@cnsgsz , sorry, I was trying to say that the I expect the hack to still work, but we do not use it to be able to confirm this.

**Comment by chensun** [comment]
> Even without rules_python, namespace packages need to include identical init files, per the python doc I quoted above?

We were aware of the deviation from what's suggested in the python doc when we made the namespace package change. My memory of why we possibly had to have this difference is hazy. But based on our research at that time and the experiment in the field, the difference doesn't seems to cause any issue until later this Bazel case which hasn't been proved to the result of the init.py difference yet.
That being said, @connor-mccarthy on our team is currently actively investigating this topic for a different scenario.

> Will it be possible to merge pipeline spec into kfp as suggested https://github.com/kubeflow/pipelines/issues/5087#issuecomment-1040721497?

Likely not an option. Pipeline spec was part of KFP package, and a copy was part of TFX package, the result was users cannot install KFP and TFX in the same environment otherwise the proto-generated Python code conflicts with each other.  Due to that issue, we made pipeline spec a standalone package as a dependency for both KFP and TFX--TFX doesn't need to take the entire KFP package as a dependency.

> I use bazel to work with python, c++ etc, just as in tensorflow etc. I understand that google internally uses something similar to bazel. What build tool would you recommend in open source if not bazel? What does kfp use without bazel?

For KFP, the SDK part is implicitly "built" through test and packaged using setuptools. The rests (backend and frontend) are built into containers using Dockerfile. I don't have any recommendation for build tools in open source. Maybe you can try this question in [the KFP Slack channel](https://kubeflow.slack.com/)?

**Comment by cnsgsz** [comment]
I confirm that bazel added `pip_parsed_deps_kfp_pipeline_spec/site-packages/kfp/__init__.py` and removing it as @cristifalcas suggested works as a work-around.

Nonetheless, this work-around does not seem to conform to [namespace packages' documentation](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/), as `kfp_pipeline_spec` does not have `__init__.py` while `kfp` has `__init__.py`?

**Comment by mering** [comment]
The [workaround](https://github.com/kubeflow/pipelines/issues/5087#issuecomment-1096879641) doesn't seem to work any more with Bzlmod. Even though the file is removed, it is still imported from there.

Example code with debug info:
```
for module_path in sys.path:
  if module_path.endswith("kfp_pipeline_spec"):
    obj = f"{module_path}/site-packages/kfp/__init__.py"
    print(f"checking obj {obj}")
    if os.path.exists(obj):
      print(f"removing {obj}")
      os.remove(obj)
      print(f"check if {obj} still exists: {os.path.exists(obj)}")

import kfp

print(f"imported kfp from {kfp.__file__}")
```

**Comment by reiyw** [comment]
`pip_parse` (WORKSPACE) or `pip.parse` (Bzlmod) has an attribute [enable_implicit_namespace_pkgs](https://rules-python.readthedocs.io/en/latest/api/python/extensions/pip.html#pip.parse.enable_implicit_namespace_pkgs). By setting this to True and also setting Bazel's flag `--incompatible_default_to_explicit_init_py`, you can disable the creation of `__init__.py` for all pip-installed libraries.
