### ISSUE TITLE
[Testing] periodic functional test failing frequently 2.20

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5154]
https://oss-prow.knative.dev/?repo=kubeflow%2Fpipelines
/assign @capri-xiyue

**Comment by Bobgy** [comment]
This wasn't notified, because after migration to gcp oss prow, I haven't set up testgrid and notification, that will be the last step during migration in https://github.com/kubernetes/test-infra/issues/14343

**Comment by capri-xiyue** [comment]
The logs showed that the periodic functional test failed because it encountered 403 error when creating experiment.
I was able to reproduce the same error in local.
It worked when I used kfp ui to create experiment but it failed with 403 when I used kfp sdk to create experiment.
It also failed with 403 even after I granted the service account which is used to run periodic functional test with Editor or Owner role. 
It looks like something went wrong with kfp sdk. We used https://github.com/kubeflow/pipelines/blob/61f9c2c328d245d89c9d9b8c923f24dbbd08cdc9/test/kfp-functional-test/run_kfp_functional_test.py#L59 to initialize the sdk.

**Comment by capri-xiyue** [comment]
I tried to switch from production proxy to staging proxy via https://oss-prow.knative.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/5167/kubeflow-pipeline-sample-test/1363986291280056320. It failed with 403 error.
Looks like there is something wrong with staging inverse proxy.

**Comment by capri-xiyue** [comment]
Will try to switch from staging proxy to production proxy for https://oss-prow.knative.dev/?repo=kubeflow%2Fpipelines to further verify whether the root cause is staging inverse proxy.

**Comment by capri-xiyue** [comment]
https://github.com/kubeflow/testing/pull/907 is just a possible temporary fix.

**Comment by capri-xiyue** [comment]
> [kubeflow/testing#907](https://github.com/kubeflow/testing/pull/907) is just a possible temporary fix.

Verified that production proxy works with https://oss-prow.knative.dev/view/gs/oss-prow/logs/kubeflow-pipelines-periodic-functional-test/1364066509248270336

**Comment by capri-xiyue** [comment]
Found out the root cause. Somehow the staging inverse proxy only passes request with scope "https://www.googleapis.com/auth/cloud-platform.read-only". And we use https://github.com/kubeflow/pipelines/blob/1fee4054a77d39877d997ec94374201188fa87d0/sdk/python/kfp/_auth.py#L40 which is "https://www.googleapis.com/auth/cloud-platform".
But staging proxy should support both scope "https://www.googleapis.com/auth/cloud-platform" and "https://www.googleapis.com/auth/cloud-platform.read-only"

**Comment by Bobgy** [comment]
Awesome, does that mean your efforts prevented an outage in prod?

**Comment by capri-xiyue** [comment]
> Awesome, does that mean your efforts prevented an outage in prod?

I think so.

**Comment by capri-xiyue** [comment]
https://oss-prow.knative.dev/view/gs/oss-prow/logs/kubeflow-pipelines-periodic-functional-test/1364764611215101952 passed.
