### ISSUE TITLE
UI metadata sometimes fails to load

### ISSUE THREAD

**Issue by muyajil** [kubeflow/pipelines#5166]
### What steps did you take?
Create UI metadata artifacts as inline web apps.

### What happened?
When trying to view the artifacts I receive the error:
`Could not parse metadata file at: artifacts/xxx/xxx/mlpipeline-ui-metadata.tgz. Error: SyntaxError: Unexpected end of JSON input`
Sometimes it works and sometimes it does not.

### What did you expect to happen
That I can see the generated web apps always.

### Environment:
Azure with OIDC
KFP version: 1.2.0

### Anything else you would like to add:
The error is triggered in this line:
https://github.com/kubeflow/pipelines/blob/61f9c2c328d245d89c9d9b8c923f24dbbd08cdc9/frontend/src/lib/OutputArtifactLoader.ts#L75

I think the error can be solved by awaiting the promise in this function:
https://github.com/kubeflow/pipelines/blob/61f9c2c328d245d89c9d9b8c923f24dbbd08cdc9/frontend/src/lib/Apis.ts#L212

However I am not sure about the implications and would appreciate some feedback. If this would fix the issue, I would happily submit a PR.

**Comment by Bobgy** [comment]
Hi @muyajil, the code you mentioned is correct, because the _fetch function also returns a Promise, this function can just return it, and let its callsites to await for the promise.

I'm not sure what the problem you hit, welcome more investigation to the root cause. You may follow https://github.com/kubeflow/pipelines/tree/master/frontend to develop the UI server locally to verify your ideas.
