### ISSUE TITLE
Issue with current implementation of data passing using volume.

### ISSUE THREAD

**Issue by boarder7395** [kubeflow/pipelines#5221]
### What steps did you take:
When using the experimental feature of data passing with a volume mlpipeline-metadata-ui artifacts, and metrics-ui artifacts do not work. I ran some local testing and have identified the issue to be in kfp/compiler/_data_passing_using_volume.py::rewrite_data_passing_to_use_volumes. Currently this function deletes all artifacts and replaces them with parameters. I believe instead this function should delete all artifacts except mlpipeline-metadata-ui, and metrics-ui artifacts.

### What happened:
Artifacts are not displayed in UI when using volume data passing.

### What did you expect to happen:
Artifacts to be displayed.

### Environment:
Running kfp on aws.

How did you deploy Kubeflow Pipelines (KFP)?
Full kubeflow deployment.

KFP version: 
743746b

KFP SDK version: 
1.4.0

### Anything else you would like to add:
I have implemented the fix and tested on my end. Happy to make the PR to fix this just having some issues pushing my code to kfp github. I have signed the developer agreement. Are there additional steps I need to take to be able to contribute, from the documentation I don't believe I am missing anything.

/kind bug
/area sdk

**Comment by neuromage** [comment]
Thanks @boarder7395 for filing this issue. 

I think the solution for treating `mlpipeline-metadata-ui` and `metrics-ui artifacts` as special in this rewriter is reasonable. If you submit a PR, we can review it. You mentioned you had a couple of other options too. Would you mind outlining them in this issue?

Also, question on your use-case - where does the data actually reside? E.g., if it's on s3, would it be easier for you to operate on the blob store or do you need local file access? I'm assuming the latter but would like to check if that's indeed the case. If not, we're working on placeholders called `InputUri` and `OutputUri` which may help with letting the component directly operate on the location of the data in Cloud storage. 

/cc @chensun 
/cc @Bobgy

**Comment by boarder7395** [comment]
We have a few different use cases. But data is sourced from potentially two locations; s3, and internal databases. 

To walk through an example pipeline:
1) We extract the data in a single component and write that data to an fsx volume using the data_passing_using_volume implementation. 
2) The next component will do some preprocessing to the dataset, for this we are using spark kubernetes implementation with the components pod acting as the driver. This then outputs a preprocessed dataset.
3) The preprocessed dataset is uploaded to s3 using a component that only does the upload operation.
3) The next component trains a tensorflow model using the preprocessed dataset on the fsx volume.
4) The model and tensorboard logs are uploaded in a separate component to s3.

As for potential other solutions:

Currently the workflow rewriter replaces all component artifacts with parameters that point to the location of a directory/file on the volume.

Instead the new implementation would use the component input/output annotations to specify whether the input/output should be passed using artifacts or parameters or potentially both.

Our use case would benefit from passing outputs using both parameters and artifacts while inputs would be handled only with parameters. This way data artifacts are uploaded to artifact storage for tracking and subsequent components can use the parameter reference location to avoid downloading large amounts of data from artifact storage.

When a step in the pipeline outputs an artifact and a parameter, the subsequent step should use the parameter output from the previous component instead of the artifact to prevent downloading the data from artifact storage.

Benefits of this implementation:
Data can be uploaded to artifact storage for tracking.
This approach removes the need to download data from artifact storage to run the next step since the data is already available on the volume.

**Comment by boarder7395** [comment]
Okay so the more I do testing on this it seems like I cannot use both parameters and artifacts since both would try to be at the some mount point. 

I will continue to explore options in this space.

**Comment by boarder7395** [comment]
@neuromage I am curious about the inputUri, and outputURI. If it does what I think it does that could be the solution to my use case. 

Ideal workflow:
Spark job read data from database, and then outputs to an outputURI in minio (aws:s3). The next component is the train component then takes in the outputURI but maps it to an inputPath so the argo wait container handles the download from artifact storage to container storage. Would this be possible? Also if you have a branch for this work I'd love to take a look at the implementation.

**Comment by Ark-kun** [comment]
Most of the UX features currently do not support volumes. Most Kubernetes volumes can only be mounted to a single Pod at a time, so if the frontend or backend pod mounts the volume, it cannot be mounted to other pods for reading or writing.
The volume is not mounted to frontend or backend, so the UX cannot visualize the data in volumes, be it the volume data-passing method or the VolumeOp or manually mounted volumes.

The volume-based data passing method is currently suitable for the following scenario: The user develops a pipeline using the normal data-passing method to debug the pipeline on <100GB datasets. One the pipeline is debugged and ready for production, if more than 100GB data passing is needed, then the pipeline can be compiled in a special way to use volumes for data passing.

>I believe instead this function should delete all artifacts except mlpipeline-ui-metadata, and mlpipeline-metrics artifacts.

I'm not sure this will fully solve the issue. The `mlpipeline-ui-metadata` is usually a small JSON structure that just points to some other artifact data. But since the artifact data is in storage, the frontend and backend cannot reach it.

A better solution would be to support volume-based data passing on the backend and frontend side: There should be a single persistent volume intended for data storage. That volume should be exposed as an NFS volume, so that multiple pods can read it and write to it. (This is similar to how Minio exposes a persistent disk as S3 storage.) The NFS volume will be mounted to the backend and frontend pods. This way the frontend and backend can access the data stored in the volume and the artifact preview and visualizations will work.

@Bobgy What do you think about this proposal? (Expose the storage volume as NFS and mount to backend Pod).

**Comment by Bobgy** [comment]
Agree with that. It aligns with the existing feature in https://github.com/kubeflow/pipelines/blob/master/docs/config/volume-support.md

**Comment by boarder7395** [comment]
The proposed solution makes sense to me at first glance but one issue I’m having trouble understanding is if we’re using NFS volumes for artifact storage wouldn’t that mean we need to provision enough storage to hold all artifacts? For an example scenario imagine an average pipeline uses 1.5TB of data, and our users are running 15 experiments daily. In this case the daily required FSx storage would be 22.5 TB. If we cleared unused artifacts after 3 months then we would potentially require 2025 TB of storage allocated for artifacts. The cost of running volume only artifact storage then explodes. 

Alternatively if using FSx with lustre a daemonset could be created that watches active pipelines and pushes artifacts to s3, utilizing hsm_archive, when the pipeline is done with those components. Then if the front end needs access to those artifacts at a later date lustre will pull the data from the cheap s3 object storage. I believe this will work for GCP as well since it seems like you can create a lustre file system there as well. With this setup storage could be reduced to 22.5TB (or less) since only while the pipeline is running will storage be on the FSx volume. 


<img width="823" alt="Screen Shot 2021-03-22 at 4 07 59 PM" src="https://user-images.githubusercontent.com/37314943/112051838-c8474a00-8b28-11eb-9b2b-28ad983fdf45.png">  
_Figure 1: Architecture using Lustre_

&nbsp;
&nbsp;

Alternatively I have been testing an approach using outputUri. For this approach the spark component in the pipeline will write directly to minio artifact storage and subsequent steps can use inputPath to download the data to local using argo wait container, or they can use inputUri and handle access to minio directly. The limitation with this approach is idempotence is not guaranteed. Also currently kfp does not support passing between an outputUri and InputPath. I have done only basic testing to this point and have not tested whether step caching works with this configuration, any insights here would be greatly appreciated.

<img width="989" alt="Screen Shot 2021-03-22 at 3 47 09 PM" src="https://user-images.githubusercontent.com/37314943/112051525-6a1a6700-8b28-11eb-93e7-48ddc1c2d665.png">  
_Figure 2: Artifact Passing using Only Uri’s_

&nbsp;
&nbsp;

<img width="711" alt="Screen Shot 2021-03-22 at 4 07 27 PM" src="https://user-images.githubusercontent.com/37314943/112051766-b796d400-8b28-11eb-8cfa-bd5df6185009.png">  
_Figure 3: Uri Passing for Spark Only_

&nbsp;
&nbsp;

**Comment by boarder7395** [comment]
@neuromage I did some local testing with inputUri and outputUri. In my simple test it seems like the UI does not recognize those are artifacts and they're not tracked by the metadata service. Is that correct?

**Comment by neuromage** [comment]
Hi @boarder7395 yes I think InputUri and OutputIUri aren't supported yet in the UI. 

It sounds like you want the first step of your pipeline (the Spark job) to read/write directly to S3, and the second step to download from S3 into local container, perform training, and then re-upload back to S3. The Evaluate step is the same as the Train step. Am I reading this right?

If so, then I think we can try to support this in our v2-compatible mode we've been experimenting with. It sounds like you'd want to be able to specify when the inputURI should be downloaded and when it shouldn't. Is this right or am I totally misunderstanding the problem?

Also, do you need minio here, or is this just drawn because that's how Argo works? In the v2 compatible pipeline, we have a custom launcher that does the data download/upload, which means you may not need minio. Let me know what you think. On my part, let me send a quick doc/readme to explain the v2-compatible mode. 

/cc @Bobgy

**Comment by boarder7395** [comment]
@neuromage Yes you are reading that correctly. Being able to specify when to download and when not is exactly the functionality I was trying to accomplish. And your right I have no need for minIO in the diagrams above only included it because that’s how Argo works.

As for the quick doc/readme that would be greatly appreciated!!

You mentioned inputUri and outputUri aren’t supported yet in the UI. Curious if the planning with volume data passing would treat workflow parameters similarly to artifacts and work with step cacheing? Or is the concept of parameters vs artifacts different in the V2 version.
