### ISSUE TITLE
Feature Request: Enable custom runtime parameters from user transforms

### ISSUE THREAD

**Issue by aoen** [kubeflow/pipelines#5295]
We are trying to use KFP's [ScheduledTime] parameter in TFX Pipelines runtime parameters. [We have discussed](https://github.com/tensorflow/tfx/issues/3354) with @1025KB from the TFX project and he suggested we file this ticket to enable this functionality on the KFP side by allowing users to be able to specify transforms on KFP runtime parameters like [ScheduledTime], and have these transformed values accessible by the components in the running pipeline.

e.g. a user could specify a transform like iso_date_to_tfx_span("[ScheduledTime]") which would convert the scheduled time in ISO format to an integer representing the corresponding TFX span using the TFX utility libraries. This is an example interface, and will leave the details for the interface and the actual parameter storage and retrieval interface to TFX/KFP folks to suss out.

cc @casassg

**Comment by zijianjoy** [comment]
We currently have the following support for time formatting: https://github.com/kubeflow/pipelines/blob/0795597562e076437a21745e524b5c960b1edb68/backend/src/crd/samples/scheduledworkflow/parameterized.yaml#L29-L33.

Does it fit your use case?

**Comment by casassg** [comment]
Hi @zijianjoy  tried exploring the documentation. 

Let me provide a deeper detail:
- We are looking to parametrize our TFX pipeline to pick up ScheduledTime so that it runs on the correct partition for that run. - For that, we need some way to extract days since epoch (which is what TFX defines as `span`  as seen [here](https://github.com/tensorflow/tfx/blob/v0.28.0/tfx/components/example_gen/utils.py#L240-L242) )
- In addition, we need to parse it as an integer which is problematic, since when specified it's a string on TFX RuntimParameter
