### ISSUE TITLE
User should be able to start a new run from the pipeline page.

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#53]

**Comment by Ark-kun** [comment]
Do we want the users to create an experiment for each run?

What's the typical number of runs per experiment and experiments per pipeline did we estimate during the planning stage of the "experiments" feature?

**Comment by ajayalfred** [comment]
There is no real meaningful way of estimating that number as a user can use a pipeline to create any number of runs and experiments. The idea was to give the user maximum flexibility in creating experiments as they see fit.

Although, your suggestion is a valid one - we'll be testing the current experience and identifying potential optimizations. Starting a run without having to create an experiment seems like a viable optimization, and we'll make this change after gathering feedback from user studies.

**Comment by rileyjbauer** [comment]
@ajayalfred, since there is no "Create experiment" button on the Pipeline list page, should we instead direct the user straight to the Pipeline Details page of the pipeline they just uploaded?

Additionally, we've had a few requests already for a "Create experiment" button from the Pipeline list page itself.

**Comment by ajayalfred** [comment]
Redirecting to pipeline details page after upload sounds good. That's usually the most common action done after uploading, so makes sense to optimize.

I'm hesitant to put a 'Create experiment' button in the list since it will be disabled until a user selects a pipeline, and it only works for single selection. If you count the number of clicks, that's exactly the same as clicking the pipeline link and clicking 'Create experiment' from the details page. So the additional button on the list page is not an optimization and doesn't improve the experience.

What we could do however is add an icon button in the pipeline list row to start an experiment. I'll create and self-assign issue to track this exploration.

**Comment by ajayalfred** [comment]
#256

**Comment by ajayalfred** [comment]
We discussed and agree this is valuable to have. I am creating a design spec for this and the associated workflow changes.
