### ISSUE TITLE
[frontend] Add pagination to Artifact list 

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/pipelines#5316]
### What is the issue

Discussion: https://github.com/kubeflow/pipelines/pull/5311#pullrequestreview-613890507

It is hard to scale when there are many artifacts to show on [Artifact list](https://github.com/zijianjoy/pipelines/blob/master/frontend/src/pages/ArtifactList.tsx). We should implement something that API can accept pageSize and pageToken like [listPipelines](https://github.com/zijianjoy/pipelines/blob/master/frontend/src/pages/PipelineList.tsx#L174-L179).

It might require update on backend API, or we can implement this during KFPv2 implementation, because it touches metadata store communication.

/kind bug
/area frontend

@Bobgy

**Comment by elikatsis** [comment]
Hello!

There are two old issues about this, so let's link to them:
* https://github.com/kubeflow/pipelines/issues/3226
* https://github.com/kubeflow/pipelines/issues/3731

Moreover, to fix this I suggest we rely on existing pagination support of the backend, thus making the the UI backwards compatible.

1. KFP manifests deploy MLMetadata version 0.25.1 ([source](https://github.com/kubeflow/pipelines/blob/5990285894d655b0b52ca4d9a2f08756a99f1ec8/manifests/kustomize/base/metadata/metadata-grpc-deployment.yaml#L25))
2. MLMetadata supports pagination in `GetArtifacts`, `GetExecutions`, and `GetContexts` APIs since 0.23.0 ([release notes](https://github.com/google/ml-metadata/releases/tag/v0.23.0))
3. MLMetadata support pagination in `GetExecutionsByContext` and
`GetArtifactsByContext` APIs since 0.25.1 ([release notes](https://github.com/google/ml-metadata/releases/tag/v0.25.1))

Therefore, it's just a matter of
1. updating the client used by the UI, and
2. update the UI code to show pages similar to runs list, experiments list, ...

In the end, there will be no breaking changes, no backend API changes, or different metadata store communication. What do you think?

**Comment by Bobgy** [comment]
Yes, the original plan was to support pagination when backend supports that. And the backend support has already been released as @elikatsis pointed out.

Suggest close either this issue or the existing issue, so that we do not have two threads for the same topic

**Comment by zijianjoy** [comment]
Thank you @elikatsis and @Bobgy for the reference! It makes sense to change client since metadata has already supported pagination. I will close this issue here. Since we have linked this issue to the previous ones, we can find the reference for our decision on making client changes for supporting pagination.
