### ISSUE TITLE
[feature] CLI command to run a pipeline from python files

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5381]
### Feature Area

/area sdk

### What feature would you like to see?

A kfp CLI command to directly run python pipelines.
For example:

```bash
kfp run sample_pipeline.py --host <host-name> --params=key1=value1,key2=value2,...
```

This command directly compiles a python pipeline and submits it to KFP instance with specified hostname.

Expectation of `sample_pipeline.py` should be the same as `dsl-compile` command.

Or what can be even better --

Set up KFP instance connection configuration including credentials:
```bash
vim ~/.kfp/config.json # this stores all KFP related configuration in a local config file
# or
export KF_PIPELINES_ENDPOINT=<kfp-host>
```

Run samples you want:
```bash
# all host and credentials information are loaded from either a config file or env vars
# so these command do not need to repeat them
kfp run sample_pipeline.py --params=key1=value1,key2=value2,...
```

### What is the use case or pain point?

I have two options for doing the same thing:
* write python script wrappers that calls `create_run_from_pipeline_func`
* use `dsl-compile` and then `kfp upload` and then `kfp run`

Both options involve some unnecessary steps, I think it's beneficial providing a CLI command to make this common command easier, because
* this command can be very helpful during pipeline development
* people do not need to write `__main__` function for every pipeline, and they do not need to support arguments like host, parameters. All of these interface can be standardized in kfp run CLI.
* it's convenient for building a KFP component that runs KFP pipelines or hooking up a KFP pipeline in a CI step

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by hahns0lo** [comment]
This would be nice. We based our KFP repo on [this example](https://github.com/ksalama/kubeflow-examples/tree/master/kfp-cloudbuild), which is referred to in this [GCP article](https://cloud.google.com/solutions/machine-learning/architecture-for-mlops-using-tfx-kubeflow-pipelines-and-cloud-build#cicd_architecture) about using KFP with Cloud Build.

The [Cloud Build pipeline](https://github.com/ksalama/kubeflow-examples/tree/master/kfp-cloudbuild#cloud-build-steps) from the example includes the following steps:

> 6. Compile Pipeline: This executes dsl-compile to compile the pipeline defined in [workflow.py](https://github.com/ksalama/kubeflow-examples/blob/master/kfp-cloudbuild/pipeline/workflow.py), to generate pipeline.tar.gz package.
> 7. Upload to GCS: This uploads the pipeline.tar.gz package to GCS.
> 8. Deploy & Run Pipeline: This executes the deploy_pipeline method in the [helper.py](https://github.com/ksalama/kubeflow-examples/blob/master/kfp-cloudbuild/pipeline/helper.py) module, given the pipeline.tar.gz package and pipeline version. The method deploys the pipeline package to KFP. If an optional --run argument is passed, the method also creates and experiment in KFP, and run pipeline given the created experiment, compiled pipeline package, and loaded parameter values from the [settings.yaml](https://github.com/ksalama/kubeflow-examples/blob/master/kfp-cloudbuild/pipeline/settings.yaml) file.

We've modified the helper.py script a bit, but the core functionality of uploading and running a pipeline remains the same.

A few comments:
1. We are basically doing the same thing as the "use dsl-compile and then kfp upload and then kfp run" option mentioned in the description. I think this proposed feature would allow us to replace the helper.py script with a call to `kfp run`.
2. helper.py loads a settings.yaml file, converts the key-value pairs in settings.yaml into a dict, then passes that dict into `kfp.Client.run_pipeline`'s `params` parameter. I would still want to store our pipeline parameters into a separate config file, so I would probably write a script that parses settings.yaml and pass them into the proposed `--params=key1=value1,key2=value2,...` command line option.
3. By using helper.py, we don't need a `__main__` in our pipelines and don't need to call `kfp.Client`, similar to the proposed `kfp run`.
4. Our CI pipeline retains step 7 from the example repo, "Upload to GCS." We have a push trigger that will run CI when PRs are merged to our main branch, which will compile our KFP pipelines and upload them to a GCS bucket. We have a separate CI pipeline that runs each night and, instead of compiling the KFP pipelines, will download the latest compiled KFP pipeline from GCS and run that. So, even though the proposed `kfp run` command removes the need to call `dsl-compile`, it might still be nice to optionally produce the compiled pipeline, for archival purposes.

**Comment by berndverst** [comment]
Let me know if you need help. I have built exactly this in Go (but it calls `dsl-compile` for the compilation step for the time being).

**Comment by aronchick** [comment]
This is super interesting to us! We're working on some higher level abstractions here too and would love to collaborate. Has this already been committed to? We'd love to sync offline and see what we could do together.

**Comment by Bobgy** [comment]
@aronchick Is it possible to present a demo on KFP community meetings? Or you need to wait until it's open?

**Comment by aronchick** [comment]
I think i'd like to wait until it's open, but happy to give as many folks as would like private demos.
________________________________

**Comment by Bobgy** [comment]
Thanks for the heads up! I'd love to wait for a presentation in KFP community meeting when it's open.

**Comment by Bobgy** [comment]
With the number of things on my hand for v2 and v2 compatible. I don't currently have bandwidth on this. Welcome anyone who's interested to pick up

**Comment by Bobgy** [comment]
Cross posting for context, I think @aronchick is talking about [The SAME Project: A Cloud Native Approach to Reproducible Machine Learning - David Aronchick](https://www.youtube.com/watch?v=aQvvGKVX25I)

**Comment by aronchick** [comment]
This is correct 🙂 I'll do a demo in the coming weeks - as soon as i can find the time!
________________________________
From: Yuan (Bob) Gong ***@***.***>
Sent: Thursday, July 1, 2021 3:06 AM
To: kubeflow/pipelines ***@***.***>
Cc: David Aronchick ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [kubeflow/pipelines] [feature] CLI command to run a pipeline from python files (#5381)


Cross posting for context, I think @aronchick<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faronchick&data=04%7C01%7Cdavid.aronchick%40microsoft.com%7Ca53824335d68462b152508d93c77e32d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637607307879377677%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=g5GtbOdP0C%2B4lzEbllVRUK4gpTalpybv14x%2BtUxv380%3D&reserved=0> is talking about The SAME Project: A Cloud Native Approach to Reproducible Machine Learning - David Aronchick<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DaQvvGKVX25I&data=04%7C01%7Cdavid.aronchick%40microsoft.com%7Ca53824335d68462b152508d93c77e32d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637607307879377677%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AdfdEUTYvIwsQZdlCTmiZaMdyOHg42UIY2o%2B%2FUok7AI%3D&reserved=0>
