### ISSUE TITLE
[frontend] mismatched frontend api client

### ISSUE THREAD

**Issue by algs** [kubeflow/pipelines#5444]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?

*  KFP version: 1.5.0-rc

### Steps to reproduce

1. clone the repo with latest version
2. cd frontend
3. npm run apis
4. git status and get modified files
5. found the definition of `ExperimentStorageState` change into `ApiExperimentStorageState` while the import statements in `frontend/src/pages/ExperimentDetails.tsx`, `frontend/src/components/ExperimentList.tsx`, etc. still `import ExperimentStorageState`, leading to import error

### Expected result
No import error, frontend and backend keep consistent.

### Materials and Reference

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

cc @Jeffwan

**Comment by Jeffwan** [comment]
1. https://github.com/kubeflow/pipelines/blob/9116a5a162ac36a2615d4185d879dabfd0d7ad9a/backend/api/experiment.proto#L178-L182  has not been changed. 

2. swagger file has been changed in this PR https://github.com/kubeflow/pipelines/pull/4906/files#r573449242

I think it's due to higher version generator. 

3.  the good thing is frontend won't break because request param is still `storagestate`. But this is not a good experience. One thing we can detect this kind of issue earlier is to always generate apis in presubmit test. Otherwise, build will use local generate sdks (old version) which will pass tests.

**Comment by Jeffwan** [comment]
@algs Feel free to help improve it once  @NikeNano @Bobgy (who work on https://github.com/kubeflow/pipelines/issues/3250) confirms.

**Comment by Bobgy** [comment]
Thank you for the investigations!
Yes, we should better regenerate frontend client after proto change.

Do you want to submit a PR?

**Comment by algs** [comment]
> Thank you for the investigations!
> Yes, we should better regenerate frontend client after proto change.
> 
> Do you want to submit a PR?

**Comment by algs** [comment]
@Bobgy Sure, I'll submit a PR to fix this issue
