### ISSUE TITLE
[feature] graph_component accepting non-PipelineParam arguments

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/pipelines#5496]
### Feature Area

/area sdk

### What feature would you like to see?

`@graph_component` decorator accepting literal values, not just `PipelineParam`s. Currently, if a literal is passed, e.g. `0`, then the following error will be raised:
```
ValueError: arguments to {function_name} should be PipelineParams.
```

### What is the use case or pain point?

If a sequential recursive loop is to be implemented, it may start with a literal:

```python
@graph_component
def sequential_loop(iter_num: int, i: int = 0):
  ...
  incr_i = ... # increase the loop counter (e.g. via python)
  with dsl.Condition(incr_i < iter_num):
    sequential_loop(iter_num, incr_i)

@dsl.pipeline("main")
def main(iter_num: int):
  sequential_loop(iter_num) # throws error!
```

It's even worse if such loop is somewhere deeper in the call stack.

I think it can be done by using `@graph_component` to wrap the function's arguments into some type that could be treated like PipelineParam inside of an OpsGroup (i.e. not be inlined) and like a literal outside of it (so that a literal is passed to the OpsGroup's parameter).

I imagine it to work similarly to `LoopArguments`.

### Is there a workaround currently?

```python
@graph_component
def sequential_loop(iter_num: int, i: int = 0):
  ...
  incr_i = ... # increase the loop counter (e.g. via python)
  with dsl.Condition(incr_i < iter_num):
    sequential_loop(iter_num, incr_i

@dsl.pipeline("main")
def main(iter_num: int, start_idx: int = 0):
  sequential_loop(iter_num, start_idx)
```

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by Udiknedormin** [comment]
@neuromage @chensun Any progress regarding this issue?

**Comment by Tomcli** [comment]
@Ark-kun We want to support non-PipelineParam arguments on graph_component so that we can define the graph function with some default arguments. Do you think it makes sense to implement this feature? Thank you.

**Comment by Ark-kun** [comment]
@Tomcli @Udiknedormin I consider this issue to be a compiler bug or missing feature.
It makes sense to fix that, but it can be non-trivial due to the general compiler architecture.
In most cases, the compiler is "task-oriented", not "component-oriented". It generates Argo templates based on specific tasks and usages (e.g. whether constant or reference was passed as argument), instead of generating templates from components and then passing arguments to those templates. The current approach has many issues. Such approach is especially problematic for recursion, since the compiler cannot analyze the usage sites infinitely and must generate a single template that works for both first and subsequent executions.

There might or might not be an easy way to fix this issue.

Maybe the `graph_component` decorator wrapper code is where this issue can be worked around.
