### ISSUE TITLE
[v2compat] finalize pipeline run MLMD schema

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5669]
TODOs:
* [ ] Design, figure out the exact list of items we need to change (size/M)

Known work items:
  * [x] https://github.com/kubeflow/pipelines/issues/5788 (size/XS)
      * [x] https://github.com/kubeflow/pipelines/pull/5842
  * [x] #5789  (size/S)
  * [ ] [v2compat] remove redundant fields “pipeline_name”, “pipeline_run_id” from execution custom properties
  * [x] https://github.com/kubeflow/pipelines/issues/5978
  * [x] make scalar metrics distinguishable. UPDATE: figured out that we treat all properties of type float as scalar metrics in metadata (custom properties).
  * [x] #5985
  * [x] #5986
  * [x] https://github.com/kubeflow/pipelines/issues/5803 (decided this is not necessary)
  * [ ] P2 pipeline root task execution

**Comment by Bobgy** [comment]
b/187556737

**Comment by Bobgy** [comment]
One problem I found from https://github.com/kubeflow/pipelines/issues/5668, is that

https://github.com/kubeflow/pipelines/blob/89364315e96ca0e14106ef178336f72265a8e91a/samples/test/metrics_visualization_v2.py#L62
For now, we log a custom property called "accuracy" in the artifact, but if we do not know in advance which metric names are logged, we cannot know which custom properties correspond to scalar metrics.

Therefore, it seems we need more structured info for metrics.

**Comment by zijianjoy** [comment]
> For now, we log a custom property called "accuracy" in the artifact, but if we do not know in advance which metric names are logged, we cannot know which custom properties correspond to scalar metrics.
> Therefore, it seems we need more structured info for metrics.

SDK allows user to define any mount of `log_metric` call, therefore scalar metric is a dictionary instead of single value. See this example:
![5i3R2aaD6LSeqer](https://user-images.githubusercontent.com/37026441/119201027-ef47cc80-ba42-11eb-890d-6216874cc9d9.png)


See this SDK implementation: https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/dsl/io_types.py#L112-L119

In order to visualize this scalar metrics, we need to create a table: one column for metric name, another column for metric value.

**Comment by zijianjoy** [comment]
But we also need to distinguish `confidenceMetrics` and `confusionMatrix` from scalar metrics. Otherwise they will appear from the same dictionary which we need to explicitly filter: https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/dsl/test_data/expected_io_types_classification_metrics.json

**Comment by Bobgy** [comment]
Needs further work item breakdown
