### ISSUE TITLE
[frontend] CRON schedule default in UI once per minute - too frequent

### ISSUE THREAD

**Issue by hsezhiyan** [kubeflow/pipelines#5748]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
We deployed by using the Kubeflow manifests, which comes with the default UI provided in this repo.
*  KFP version: `v.1.2.0`

### Issue

When you do onto the Kubeflow UI and try to create a recurring run, the default periodic scheduled/cron schedule is `once per minute`, or `0 * * * *`. 

![image](https://user-images.githubusercontent.com/40924035/119910087-35050900-bf0b-11eb-8963-dc65a2216d87.png)
![image](https://user-images.githubusercontent.com/40924035/119910095-38989000-bf0b-11eb-9c7a-bf458bf13886.png)

Our deployment of Kubeflow is now being used by a large number of customers, so there is a real possibility that a customer will accidentally schedule a large pipeline run every minute. There is also the possibility that someone will experiment with scheduled runs and forget to the off the run after done testing. In both these scenarios, there will be a lot of wasteful use of the K8s clusters (added cost) and possible overloading of the cluster (affecting SLAs, reducing reliability).

Is it possible to remove the "run every minute" dropdown menu bar, or at least make the "run every hour" the default setting?

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Bobgy** [comment]
Hi @hsezhiyan, this sounds reasonable.
Welcome contribution on this

**Comment by Bobgy** [comment]
/cc @zijianjoy 
what do you think?

**Comment by zijianjoy** [comment]
I agree with making `run every hour` as the default setting. To me it usually is too frequent as once per minute, and it actually takes longer than 1 minute to start the recurring run in my case. So I fell into confusion that `why doesn't the recurring run happens within 1 minute since I create this recurring run?` in the past. 

Welcome for contribution! Code location:
https://github.com/kubeflow/pipelines/blob/HEAD/frontend/src/components/Trigger.tsx#L125

**Comment by difince** [comment]
Hi @Bobgy, @zijianjoy Can I work on this issue ?

**Comment by Bobgy** [comment]
@difince Sure, you are welcome to work on this!
