### ISSUE TITLE
[backend] Kale pipeline steps are not getting cached but HP tuning jobs has the cache feature

### ISSUE THREAD

**Issue by cloudbow** [kubeflow/pipelines#5765]
### Feature Area

/area backend
/area sdk
/area samples 

### What feature would you like to see?
Use cache feature to rerun kale generated pipelines which will reduce the total amount of time to re-run the pipelines with code changes

### What is the use case or pain point?

Currently when I installed minkf-1.3 for datascientists the compiled pipelines are taking a long time to execute. The reason is that the steps are not getting cached. There is no way to create a cache from converting jupyter to pipelines because everytime it creates a new rok snashot. Is there anyway to provide a "Compile and Run with Cache" option so that only changed code is converted to kubeflow pipelines.

### Is there a workaround currently?
Not to my knowledge

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by sumeet1989** [comment]
@****

**Comment by Bobgy** [comment]
Hi @cloudbow, this seems like a feature request to Kale, because using a new volume snapshot as pipeline input makes it impossible for KFP to predict whether there were any changes in the pipeline.

To utilize caching, you should better have smaller granularity for your input data, so that the pipeline can easily know which changed and which didn't.
