### ISSUE TITLE
Possible to use ImagePullSecret on a func_to_container_op?

### ISSUE THREAD

**Issue by aronchick** [kubeflow/pipelines#5843]
Is it possible to use an ImagePullSecret on a func_to_container_op?

**Comment by Ark-kun** [comment]
`func_to_container_op` function creates components. This function does not access images, so it does not need secrets.

Components are expected to be portable and self-contained. We do not support adding cluster-specific information like secret names or volumes to the component definitions.

However, after creating an instance of the component, some of these options can be configured on the resulting task. Some pipeline-wide options are configurable using the `PipelineConf` object that can be passed to the compiler or client.

Example with set_image_pull_secrets:
```python
my_op = create_component_from_func(...)

def my_pipeline():
    my_task = my_op()

from kubernetes import client as k8s_client
pipeline_conf = kfp.dsl.PipelineConf()
pipeline_conf.set_image_pull_secrets([k8s_client.V1ObjectReference(name="secretA")])

kfp.Client(host=...).create_run_from_pipeline_func(
    my_pipeline,
    arguments={},
    pipeline_conf=pipeline_conf,
)
```


P.S. Perhaps you can use the canonical function name - `create_component_from_func` instead of the older name `func_to_container_op`.

**Comment by aronchick** [comment]
AH, thank you - changing to the new function and switching to the pipeline_conf did it (I kept trying to hack at it with annotations).

Feel free to close - but, it may be worth allowing setting a specific imagePullSecret by component (in the rare case i need to pull from two separate private repos in a pipeline)

**Comment by aronchick** [comment]
OH, never mind - misread your comment. Yes, setting `pipeline_conf` by component is exactly what i was thinking of. Perfect. Thanks!

**Comment by Ark-kun** [comment]
>setting pipeline_conf by component

pipeline_conf is pipeline-level configuration.

task-level configuration can be set using `ContainerOp` members. All Kubernetes' options are supported, but only few Kubeernetes' Pod-level options are supported.

```
my_task = my_op()
my_task.container.foo = bar
```

>it may be worth allowing setting a specific imagePullSecret by component (in the rare case i need to pull from two separate private repos in a pipeline)

Unfortunately, Argo does not support setting the imagePullSecrets per Argo Template, inly per-Workflow.

However the `set_image_pull_secrets` accepts a list of secrets, so you can specify both.

**Comment by Ark-kun** [comment]
> changing to the new function

These functions have the same code and behavior. Just different names. We've deprecated the direct construction of COntainerOp and added support for components in TFX SDK where the ContainerOp does not exist. So the `create_component_from_func` is just a more fitting name compared to `func_to_container_op`.
