### ISSUE TITLE
[backend] visualization server image size increased from 1.3G to 6.4G

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#6053]
Look at existing visualization server image sizes: gcr.io/ml-pipeline/visualization-server
Compare that with newly built size: gcr.io/ml-pipeline-test/visualization-server@sha256:fb3768db11f2a0bc6f3a94e7191d32eaa2bdaf53a6ca38d2d03de0f6f47c5ede

I think the change is caused by using tfx image as base: https://github.com/kubeflow/pipelines/commit/290d201cdf0baae27f3e79ad6add7d81af2249c8. Maybe we should not do that.

## Side effect

Release cloud build task is now timing out on pulling the visualization server image, just because it's too large https://console.cloud.google.com/cloud-build/builds;region=global/f92a0259-dd8c-4cd4-a7d9-43c6569f06b5;step=30?project=ml-pipeline-test

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by vaskozl** [comment]
@zijianjoy Why did you downgrade to TFX 0.26?

**Comment by zijianjoy** [comment]
@vaskozl Sorry for missing to include the context in PR description, I tried to upgrade TFX to the latest. However, the dependency graph doesn't resolve because of the requirement conflict on `grpcio`. We will have to wait for https://github.com/tensorflow/tensorflow/issues/50045 so I can upgrade tensorflow image as well as TFX related libraries.
