### ISSUE TITLE
[sdk: google vertex AI] Is it okay to keep making changes to google AIPlatformClient SDK that will be deprecated?

### ISSUE THREAD

**Issue by toshitanian** [kubeflow/pipelines#6146]
### Feature Area

/area sdk 

### What feature would you like to see?

I'm using kfp SDK to use Vertex pipeline of GCP by `AIPlatformClient`. So I want to propose several pull requests to the functions like `create_run_from_job_spec` and `create_schedule_from_job_spec` for fixing bugs and adjust specifications.  But I found that `AIPlatformClient` will be deprecated in v1.9 and will be moved to `google-cloud-aiplatform` package.
I looked into the document and was not able to find the features that is compatible with `AIPlatformClient.create_schedule_from_job_spec`.

So I want to ask that is it okay to keep making changes to the AIPlatformClient SDK. If it's okay and will the pull requests will be merged, I will try to make pull requests for the feature request.
But if it's better to move to `google-cloud-aiplatform`, I want a guide to move current workflow to the new SDK.
I understand that it's still work in progress and difficult to handle, but I appreciate if someone could tell me the direction.

@ji-yaqi I'm not sure you're the right person but seems that you're contributing to the google SDK, so let me mention you here for notice.

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by ji-yaqi** [comment]
The AIPlatformClient in KFP SDK will be deprecated and we would recommend starting to use `google-cloud-aiplatform`. 

Currently, the `create_run_from_job_spec` is completed moved over and `create_schedule_from_job_spec` is in-progress. We are working on a code sample of usage in `google-cloud-aiplatform` (Vertex SDK) and will add to the deprecation warning when it's ready. 

If it's blocking you, you can continue submit PR to KFP client to unblock, until the Vertex SDK client is ready. Otherwise, please file a feature request and assign to me. I will be reviewing them and consider adding them to Vertex SDK. 

Thank you for your contributions!

**Comment by toshitanian** [comment]
@ji-yaqi Thank you for your reply! Then we will keep using the KFP SDK for a while and prepare migration to the Vertex SDK.

**Comment by nicokuzak** [comment]
@ji-yaqi what is the Google Cloud SDK equivalent of `create_schedule_from_job_spec`?
