### ISSUE TITLE
v2 control flow - fan in

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#6161]
[aggregate outputs as iterator DAG output](https://github.com/kubeflow/pipelines/blob/fef8c03e401a15a9f92c1839fe0f9a5c22f709e1/api/v2alpha1/pipeline_spec.proto#L466-L470)

**Comment by papagala** [comment]
Sorry again for the spam but its a bit confusing since this is still not fixed nor supported as far as I could see by running the `after` (https://github.com/kubeflow/pipelines/issues/10050) method or the `dsl.Collected` (https://github.com/kubeflow/pipelines/issues/8830). 

It seems there is no workaround for fan in at the moment @chensun (sorry for the second mention in a day, just trying to understand this issue)

**Comment by JohanRuiz9801** [comment]
hello @papagala Im searching for a way to gather the results of the tasks inside a ParallelFor loop and my investigation drive me here, but I saw that dsl.Collected still seems to be unsupported. What other alternative do I have? Thank you
