### ISSUE TITLE
Remember the page I was on

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#62]
In the All runs list, I click on a run, then use the browser's back button. This does not return me to the same page.

**Comment by Ark-kun** [comment]
@rileyjbauer Yes

As a side note: In the system I've used, the run list was a panel, so selecting a run did not remove the list from the screen.

**Comment by yebrahim** [comment]
I'm afraid there's no good way of doing this if we can't get the page index from the backend. If we can, then we can add it to query parameters so that it's saved in the browser history stack.

**Comment by yebrahim** [comment]
@IronPan if he thinks this is planned, otherwise let's close this issue.

**Comment by vicaire** [comment]
Closing as suggested by Yasser.

**Comment by Ark-kun** [comment]
I think this UX issue is still valid regardless of the implementation details.

**Comment by Bobgy** [comment]
I think this is a valid ask.

Temporary workaround: @Ark-kun do you think always opening a new page when clicking on runs would be better. User context in all runs page will be kept for them to come back.
The user experience isn't as smooth as always using the same tab, but system complexity for our UI code is a lot simpler.

To properly design front-end to remember last state is a complex problem that requires more thorough design (I've done it once in my previous job, but I don't fully like the approach I took now because of extra code coupling it involved).
It easily adds a lot of complexity to the project, so I don't think I want to do this soon.

**Comment by Ark-kun** [comment]
AFAIK, usually the websites send the page and count as query parameters. This way each page has a distinct URL.

**Comment by Bobgy** [comment]
It doesn't work with our backend, because we cannot query lists by page and count. We can only query by pageToken and count. Therefore, the state of a table is a list of pageToken that corresponding to each page user has already seen: [code](https://github.com/kubeflow/pipelines/blob/af090bffa2b8773162898c97648c1c0b38dd85fe/frontend/src/components/CustomTable.tsx#L206).

That's not sth suitable for persisting in the URL.

Unless we decide to let backend support that, frontend can only cache these info in memory to allow users later come back to a previous state in a table.

**Comment by Ark-kun** [comment]
I see. Thanks for the explanation.

**Comment by Bobgy** [comment]
I want to think over a solution carefully.

**Comment by chensun** [comment]
Closing due to lack of interaction/follow up in more than 2 years.
