### ISSUE TITLE
[sdk] Dict/List json deserialization does not work in Python 3.8

### ISSUE THREAD

**Issue by alanhdu** [kubeflow/pipelines#6341]
### Environment
I am using Python 3.8.6 with:
```
kfp==1.6.2
kfp-pipeline-spec==0.1.9
kfp-server-api==1.6.0
```

### Steps to reproduce

If you run:
```python
from typing import Dict
from kfp.components import create_component_from_func

def add(xs: Dict) -> float:
    """Calculates sum of two arguments"""
    return xs["a"] + xs["b"]
create_component_from_func(add, output_component_file="add_component.yaml")
```
and look at the output component, you will see that this dictionary is actually being inteprreted as a string:
```python
      _parser.add_argument("--xs", dest="xs", type=str, required=True, default=argparse.SUPPRESS)
```

### Expected result

The parse argument should look like:
```python
      _parser.add_argument("--xs", dest="xs", type=json.loads, required=True, default=argparse.SUPPRESS)
```

### Materials and Reference

I think there are actually two things wrong here. One of them is that the type name normalization in

https://github.com/kubeflow/pipelines/blob/ee8cbfa31cbf1164ed78b6f1adacc4c31c5c00d9/sdk/python/kfp/components/_data_passing.py#L128-L132

and

https://github.com/kubeflow/pipelines/blob/ee8cbfa31cbf1164ed78b6f1adacc4c31c5c00d9/sdk/python/kfp/components/_data_passing.py#L115

is super naive -- there are a lot of variations types that should arguably be mapped to the JsonObject (e.g. `Dict[str, float]`, `Dict[str, int]`, `Dict[str, str]`, etc). In particular, even a function with `def f(x: Dict)` will have the name `typing.Dict` instead of `Dict`, so this remapping list doesn't actually do much. Only doing `def f(x: dict)` seems to work reliably.

Second, it's weird that "unrecognized types" get automatically mapped to strings -- from a user's perspective, I would *much* rather throw an error when we can't recognize the type name than to have it automagically be mapped to a string and fail at runtime.

**Comment by chensun** [comment]
Hi @alanhdu, 

I think it's a known limitation that v1 components (resulted from `create_component_from_func` doesn't really support `Dict` and `List` typed inputs but expect user code to handle the serialization and deserialization. 

With v2 components (resulted from `create_component_from_func_v2` or `@kfp.v2.dsl.component` decorator), we do support automatic json serialization and deserialization. Here's a [sample](https://github.com/kubeflow/pipelines/blob/50f7dcd5d0ef87a35eba12000b4c3b44f8fe275e/samples/v2/lightweight_python_functions_v2_pipeline/lightweight_python_functions_v2_pipeline.py) showing the case. Note that v2 components runs on KFP v2 compatible mode and on Vertex Pipelines but not on KFP v1 (the current default) mode.

> there are a lot of variations types that should arguably be mapped to the JsonObject (e.g. Dict[str, float], Dict[str, int], Dict[str, str], etc). In particular, even a function with def f(x: Dict) will have the name typing.Dict instead of Dict, so this remapping list doesn't actually do much.

I believe this was fixed by https://github.com/kubeflow/pipelines/pull/5153. 

> Second, it's weird that "unrecognized types" get automatically mapped to strings -- from a user's perspective, I would much rather throw an error when we can't recognize the type name than to have it automagically be mapped to a string and fail at runtime.

I totally agree with you on this. If we were starting from scratch again, I'd vote for enforcing types and no implicit type guessing/converting. In v2 design, we're putting more strict rules on types. But unfortunately we can't just error out on any "unrecognized types", that would make quite a number of existing pipelines stop working. 
In v2, "unrecognized types" would be viewed as generic artifact type instead of string parameter type. And we do not allow passing artifacts to parameters or vice versa. In general, we're trying to require more explicitness from the user. You may find more context from a related issue: https://github.com/kubeflow/pipelines/issues/5801.
