### ISSUE TITLE
[backend] Unsupported resource type: PIPELINE

### ISSUE THREAD

**Issue by rubenaranamorera** [kubeflow/pipelines#6486]
When calling the api with an APIResourceReference:

```
apiResourceReference := &job_model.APIResourceReference{
    Key: &job_model.APIResourceKey{
	    ID:   pipelineOk.Payload.ID,
	    Type: job_model.APIResourceTypePIPELINE,
    },
    Name:         pipelineOk.Payload.Name,
    Relationship: job_model.APIRelationshipCREATOR,
}
```

I'm getting an error:

`"error": "[POST /apis/v1beta1/jobs][400] CreateJob default  &{Code:3 Details:[0xc0035a7920] Error:Create job failed: Error to convert resource references.: Failed to convert reference type: Invalid input error: Unsupported resource type: PIPELINE}"}`

I think it is because "PIPELINE" is missing in https://github.com/kubeflow/pipelines/blob/cc83e1089b573256e781ed2e4ac90f604129e769/backend/src/apiserver/common/const.go#L73-L86

**Comment by zijianjoy** [comment]
Hello @rubenaranamorera , would you like to try using ResourceType_PIPELINE_VERSION? You can use this or get the `PipelineID` from `PipelineSpec` as specified in https://www.kubeflow.org/docs/components/pipelines/reference/api/kubeflow-pipeline-api-spec/#/definitions/apiPipelineSpec for the same goal.

**Comment by rubenaranamorera** [comment]
Using "PIPELINE_VERSION" leads me to another issue:

`"error": "[GET /apis/v1beta1/pipelines][400] ListPipelines default  &{Code:3 Details:[0xc0033f85d0] Error:Invalid input error: Invalid resource references for pipelines. ListPipelines requires filtering by namespace.}"}`

It seems that the only accepted resource type here is the namespace:

https://github.com/kubeflow/pipelines/blob/cc83e1089b573256e781ed2e4ac90f604129e769/backend/src/apiserver/server/pipeline_server.go#L209

**Comment by zijianjoy** [comment]
@rubenaranamorera In the original issue description, you are calling `POST /apis/v1beta1/jobs` , but in the new issue, you are calling `GET /apis/v1beta1/pipelines`. I think specifying `PIPELINE_VERSION` doesn't make sense in ListPipelines API, because if you know the pipeline version ID, you can get the exact pipeline entry directly by using `GetPipeline` API, you don't need to list pipelines. Is this understanding correct?

cc @capri-xiyue for the backend related question on accepting namespace resource type only.
