### ISSUE TITLE
[frontend] Pipeline logs persistence 

### ISSUE THREAD

**Issue by rohitgujral** [kubeflow/pipelines#6704]
I'm trying to persist the pipeline pod logs so that if pod gets deleted then logs should be available for the pipeline runs.
I added `archiveLogs: true` to the argo/base config-map and restarted pipelines deployment but still after deleting the pod, im not seeing logs.

![image](https://user-images.githubusercontent.com/8684157/136513357-93106f67-6bf8-48b7-afa1-31bcaae00407.png)

Is there any other step which needs to be done ?
kubeflow version - 1.0.2 and argo version - 2.3.0

**Comment by zijianjoy** [comment]
Possible related issue: https://github.com/kubeflow/pipelines/issues/6428

One thing we can do is to capture the `main.log` from output Artifact, and visualize it in Logs tab. Welcome contribution for making this change for KFPv1.

**Comment by AndersBennedsgaard** [comment]
This should probably be closed in favor of https://github.com/kubeflow/pipelines/issues/6428

**Comment by thesuperzapper** [comment]
@AndersBennedsgaard I don't think https://github.com/kubeflow/pipelines/issues/6428 is related to this issue. 

The issue raised here was that in KFP v1, the "logs" tab did not fall back to the `main.log` artifact (even though we were exposing it in the other UI tab). 

However, the same issue is present in the KFP v2 UI (and it's actually worse), because we dont even capture the `main.log` as an output artifact. Let's continue the discussion about fixing it in KFP V2 on: 
- https://github.com/kubeflow/pipelines/issues/10036

/close
