### ISSUE TITLE
[backend] severe perf problem in archive experiment API

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#6845]
### Environment

*  KFP version: master

### Steps to reproduce

1. On a KFP cluster with many runs/experiments.
2. Use archive experiment API on any experiment, observe that the API takes >1 minute to process and may timeout + cause other queries to fail. Observed failure look like https://github.com/kubeflow/pipelines/issues/6815#issue-1037408014

The issue caused severe flakiness in test infra: https://github.com/kubeflow/pipelines/issues/6815, and was mitigated by skipping the archive experiment step in test script: https://github.com/kubeflow/pipelines/pull/6843 (We should revert the https://github.com/kubeflow/pipelines/pull/6843 after fixing the perf problem)

### Expected result

There's no perf problem with experiment archive API.

### Materials and Reference

This is caused by a known TODO item to improve SQL perf: https://github.com/kubeflow/pipelines/blob/74c7773ca40decfd0d4ed40dc93a6af591bbc190/backend/src/apiserver/storage/experiment_store.go#L266

I experimented with a SQL query improvement in https://github.com/kubeflow/pipelines/issues/6815#issuecomment-955935043, we still need to investigate how to turn that into our golang backend.

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by lfloeer** [comment]
We just today got hit by this issue (Kubeflow 1.3 deployment). Would really appreciate if this could get addressed in a future version. Right now, we have to tell our users to not archive experiments. An unfortunate side effect of the performance issue is, that since this results in an `UPDATE` statement, the `run_details` and `resource_references` table are locked during this operation, leading to other failed API requests, e.g. updating a single run, etc.

**Comment by gkcalat** [comment]
Fixed by @difince.

/close
