### ISSUE TITLE
[backend] Create Run in KFPv2 failing because of invalid name in argo workflow

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/pipelines#6972]
During KFPv2, I tried to create KFPv2 run using existing pipeline template. The following is the request payload for create run:

```
{
   "description":"",
   "name":"Run of v2upload (6792a)",
   "pipeline_spec":{
      "parameters":[
         
      ]
   },
   "resource_references":[
      {
         "key":{
            "id":"ba85c817-a301-4f9c-920d-b654c4a03c81",
            "type":"EXPERIMENT"
         },
         "relationship":"OWNER"
      },
      {
         "key":{
            "id":"3943f4b9-2d33-487c-8a6e-0a17fbeff62c",
            "type":"PIPELINE_VERSION"
         },
         "relationship":"CREATOR"
      }
   ],
   "service_account":""
}
```

The error is:

![runcreationfailed](https://user-images.githubusercontent.com/37026441/143730996-93da1a44-5948-4685-bb46-3470c6228556.png)

Looks like the run name pattern `pipeline/v2upload-8d5ks` didn't pass the argo workflow validation because it shouldn't contain `/` symbol.

cc @Bobgy @capri-xiyue

**Comment by capri-xiyue** [comment]
I did some investigation, the root cause is because when creating pipeline, the pipeline api will override the name to pipeline/xxx format, FYI https://github.com/kubeflow/pipelines/blob/cfdfe71a7e4944a3d79f0731ea8d7170738d40e5/backend/src/apiserver/resource/resource_manager.go#L263https://github.com/kubeflow/pipelines/blob/cfdfe71a7e4944a3d79f0731ea8d7170738d40e5/backend/src/apiserver/resource/resource_manager.go#L263
and https://github.com/kubeflow/pipelines/blob/cfdfe71a7e4944a3d79f0731ea8d7170738d40e5/backend/src/apiserver/template/v2_template.go#L105

And the backend compiler generated name based on the pipeline name https://github.com/kubeflow/pipelines/blob/cfdfe71a7e4944a3d79f0731ea8d7170738d40e5/v2/compiler/argo.go#L61

I found the backend db still store the pipeline name like `v2upload` instead of `namespace/xxx` or `pipeline/xxx`
The backend compiler currently does not work with such override logic https://github.com/kubeflow/pipelines/blob/cfdfe71a7e4944a3d79f0731ea8d7170738d40e5/backend/src/apiserver/template/v2_template.go#L105

I think we need to revisit the backend compiler logic to make sure it works with the pipeline v2 api.

cc@Bobgy
