### ISSUE TITLE
[sdk] v2 Components not supported by LocalClient

### ISSUE THREAD

**Issue by gpoulin-hopper** [kubeflow/pipelines#6986]
### Environment

*  KFP version:
 N/A
*  KFP SDK version: 
1.8.9
*  All dependencies version:
```
kfp                      1.8.9
kfp-pipeline-spec        0.1.13
kfp-server-api           1.7.1
```

### Steps to reproduce

Running this python script 
```python3
import kfp
import kfp.v2.dsl as dsl

@dsl.component()
def simple():
    print("allo")

@dsl.pipeline(name="test", description="test")
def pipeline():
    simple()

kfp.run_pipeline_func_locally(pipeline, {})
```

 produce:
```
ERROR:root:WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/kfp/v2/components/executor_main.py", line 104, in <module>
    executor_main()
  File "/usr/local/lib/python3.7/site-packages/kfp/v2/components/executor_main.py", line 94, in executor_main
    executor_input = json.loads(args.executor_input)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

ERROR:root:['docker', 'run', '-v', '/var/folders/99/4l_08z0d4yvfc3ywqvh42pr00000gq/T:/var/folders/99/4l_08z0d4yvfc3ywqvh42pr00000gq/T', 'python:3.7', 'sh', '-c', '\n\nif ! [ -x "$(command -v pip)" ]; then\n    python3 -m ensurepip || python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1 python3 -m pip install --quiet     --no-warn-script-location \'kfp==1.8.9\' && "$0" "$@"\n', 'sh', '-ec', 'program_path=$(mktemp -d)\nprintf "%s" "$0" > "$program_path/ephemeral_component.py"\npython3 -m kfp.v2.components.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"\n', '\nimport kfp\nfrom kfp.v2 import dsl\nfrom kfp.v2.dsl import *\nfrom typing import *\n\ndef simple():\n    print("allo")\n\n', '--executor_input', '{{$}}', '--function_to_execute', 'simple']
```

### Expected result

To have the same result as if `simple` was a v1 component

```python3
import kfp
from kfp.components import create_component_from_func
import kfp.dsl as dsl

@create_component_from_func
def simple():
    print("allo")

@dsl.pipeline(name="test", description="test")
def pipeline():
    simple()
```

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by chensun** [comment]
This is known and expected. `run_pipeline_func_locally` was added as an alpha feature by a community contributor. It targets v1 only and has many limitations. 
There's currently no plan to make it work for v2 components and pipelines.

**Comment by lynnmatrix** [comment]
@chensun @gpoulin-hopper  Actually I have implemented the local client for v2 which is only used internally for now.  If needed I will be happy to pull a PR.

**Comment by frederikfab** [comment]
@lynnmatrix yes please!

**Comment by lynnmatrix** [comment]
@frederikfab  I created a new project [kfp-local](https://github.com/lynnmatrix/kfp-local) for the local client v2.
@chensun Is it necessary to merge it into kfp sdk?

**Comment by chensun** [comment]
@gpoulin-hopper @frederikfab @lynnmatrix 
This topic has been brought up from time to time, so I'd like to add some more contexts and thoughts here:
- We view ML pipelines more than just executing code to completion. One critical area we build around is the ML Metadata. This is even more emphasized in the Kubeflow Pipelines v2 design [[doc](https://docs.google.com/document/d/1fHU29oScMEKPttDA1Th1ibImAKsFVVt2Ynr4ZME05i0/)]. 
- Kubeflow Pipelines supports [local deployment](https://www.kubeflow.org/docs/components/pipelines/installation/localcluster-deployment/) which would give you the full set of features. That would probably be a better choice if the goal is to test the end to end experience of running a pipeline in a local environment. 
- For quick "unit tests"-like testing/debugging, it is on our roadmap to support local execution of a component. But we currently don't plan the same for pipeline due to the aforementioned reasons and the complexity possibly involved in a pipeline: loops, conditions, exit handlers, importer, etc.

@lynnmatrix Appreciate your effort to make local client work for v2. Going forward, we're proposing to require design docs for changes that affect UX in a nontrivial way. This would give us a more formal process of evaluating and discussing design choices. So if you'd like to merge [kfp-local](https://github.com/lynnmatrix/kfp-local) into KFP repo, could you please start with a design doc? (Consider what I mentioned above would probably be the comments you would receive in your design doc, you may want to address them in your design doc to justify adding the feature). Thanks!

**Comment by lynnmatrix** [comment]
@chensun LocalClient is mostly for testing/debugging. I'll keep LocalClient in [kfp-local ](https://github.com/lynnmatrix/kfp-local) before figuring out how to write the design doc.
