### ISSUE TITLE
set component ram request using pipeline parameter value

### ISSUE THREAD

**Issue by ypitrey** [kubeflow/pipelines#7015]
I have a pipeline in which some components require an amount of RAM that is dependent on the run duration. Our runs can take anything from 10 minutes to 12 hours and we run mostly short runs (less than 30 minutes). I'm looking into adapting the memory request to have enough RAM for long runs while saving costs on short runs.

The run duration in hours is specified as a pipeline parameter. Basically, I'd like to do something like this: 

```
@dsl.pipeline(name='example_pipeline', description='foo')
def pipeline(run_duration: float):
    ...
    comp = my_component(run_duration)
    comp.set_memory_request(f'{300 * run_duration}Mi')  # 30 is an arbitrary value for this example
    comp.set_memory_limit('4Gi')  # '4Gi' is an arbitrary value for this example
    ...
```

But I can't do that because the value of `run_duration` isn't available from the `pipeline` function.

Is there a workaround for this? Or am I looking at the issue from the wrong perspective?

Thanks!

**Comment by zijianjoy** [comment]
cc @chensun

**Comment by chensun** [comment]
@ypitrey The fundamental issue is that `300 * run_duration` is a piece of code not captured in any container. Generally speaking, a pipeline may only use components as building blocks, where each component is a containerized app. There can't be code hanging outside a component. Does that make sense?
I assume you're running on Kubeflow Pipelines rather than Vertex Pipelines, am I right? If so, I would suggest you have an additional pipeline input for memory request:
```python
@dsl.pipeline(name='example_pipeline', description='foo')
def pipeline(run_duration: float, memory_request: str):
    ...
    comp = my_component(run_duration)
    comp.set_memory_request(memory_request) 
    ...
```
