### ISSUE TITLE
parse pipeline argument string 'None' to None

### ISSUE THREAD

**Issue by iuiu34** [kubeflow/pipelines#7064]
When definining a kfp pipeline, with an str argument, if the value is 'None', then the component recieve 'None'. 
Wouldn't be better, to parse str 'None' to None (NoneType)?

Now:
```py
@component
def task1(arg1: str = None):
  if arg1 is None or arg1 == 'None':
    print('arg1 is None')
@pipeline
  pipeline(arg1: str = 'None'):
  task1(arg1)
```
expected:
```py
@component
def task1(arg1: str = None):
  if arg1 is None:
    print('arg1 is None')
@pipeline
  pipeline(arg1: str = 'None'):
  task1(arg1)
```

**Comment by Ark-kun** [comment]
Thank you for raising the issue.

KFP is language-agnostic pipeline system. `None` is a python-specific object that is not present in other languages. Im'm not sure it's a good idea to tie KFP to a specific language.

>the component recieve 'None'.

KFP orchestrates containerized command-line programs. Command-line programs, as defined by their POSIX standard, receive command-line arguments as an array of null-terminated strings. Command-line programs cannot receive "None" objects.

There is a way for a command-line program to distinguish between an empty string argument and a missing argument. Conditional placeholders in the component definitions help with that (`{if: {cond: {isPresent: Input1}, then: ["--input-1", {inputValue: Input1}}]}`).

SDK automatically handles cases where an optional input argument was not specified when instantiating a component.

However, as you've discovered, this might not work as well for pipeline arguments. The reason is that currently the conditional placeholders are evaluated at compile time, but the pipeline arguments can be specified after the compilation.

The specification of the compiled pipeline does not allow passing NoneType objects - only strings. So, if you want to be able to pass some value from pipeline parameter to a component and have the component interpret is as `None`, you have to do that on the component side.

**Comment by Iuiu1234** [comment]
understood,
in that case the parsing should be done
a) inside the component; in the container:command of the json. Which for py func would be something like adding a line inside the body as `locals() = {k:None if v == 'None' else v for v in locals()} , but for components from yaml i don't know
b) inside the inputs:parameters. Like the parsing that you do from str to bool (which i don't understand how it works). ``  
```
"input1": { # string
                  "runtimeValue": {
                    "constantValue": {
                      "intValue": "1"
                    }
                  }
                },```

**Comment by chensun** [comment]
Alexey is correct that `None` is not something you can pass via command-line arguments.
That said, what you get is expected because you are passing string literal `"None"` which overrides the default value `None`. The way to receive a Python `None` object is to not pass anything at all, then the default value will be used.

Try the following:
```python
@component
def task1(arg1: str = None):
  if arg1 is None:
    print('arg1 is None')
@pipeline
def pipeline():
  task1()
```

**Comment by iuiu34** [comment]
But that's precisely the problem. The "not passing anything at all" is not an option in a function, it's only in the entrypoint.

What I want is setting args with default None (not 'None') in the pipeline (not the component)

Basically
```py
@component
def task1(arg1: str = None):
  if arg1 is None:
    print('arg1 is None')
   else:
    print(f"arg1 value = '{arg1}'")
@pipeline
  pipeline(arg1: str = None):
  task1(arg1)
```
pipeline() prints "arg1 value = 'None'" instead of the desired "arg1 is None"

**Comment by chensun** [comment]
> What I want is setting args with default None (not 'None') in the pipeline (not the component)

That's not a supported scenario. As Alexey mentioned above, `None` is a Python-specific object, whereas KFP is language-agnostic. 

In your code sample, by passing object` None` to `task1` component, you're assuming that `task1` is a Python program. But that's not necessarily true. Albeit you write `task1` implementation using Python above, that doesn't mean all components are Python-based. In fact, we see quite a lot component written as bash commands for instance.

**Comment by iuiu34** [comment]
Yep, so agreed that in the pipeline arg1='None'.

But again; then, the parsing from 'None' to None, should be done (only) inside the py component? With something like `locals() = {k:None if v == 'None' else v for v in locals()} ` (option b)

Or not parsing at all, and that py component should recieve 'None' and be treated by the user inside the function? (option a)

**Comment by chensun** [comment]
> the parsing from 'None' to None, should be done (only) inside the py component?

No, I don't think we should ever convert `'None'` to `None`. It could be a legit user intention that they may want to pass `'None'` and consume it as string. We don't want to be "oversmart".

> Or not parsing at all, and that py component should recieve 'None' and be treated by the user inside the function? (option a)

Yes, users can choose whatever they want, `'None'`, `'null'`, `'NoValue'`, etc. The system doesn't need to be aware of the user-chosen contract.
