### ISSUE TITLE
[frontend] Missing the left-side menu bar in KFP UI v1.7.1

### ISSUE THREAD

**Issue by daikeshi** [kubeflow/pipelines#7110]
After we upgraded KFP and its UI image version from 1.3 to 1.7.1, we noticed that the left-side menu bar is missing in KFP UI v1.71. Is there any way we can bring it back? Thanks

### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? It's deployed via OSS Kubeflow stack

*  KFP version:  1.7.1

### Steps to reproduce

**KFP UI v1.3**
![image](https://user-images.githubusercontent.com/475945/147268334-6083caf8-d11b-4faa-8acd-5dfa77d540a8.png)

**KFP UI v1.7.1**
![image](https://user-images.githubusercontent.com/475945/147268459-c59058fe-5167-4af0-9101-cbb12de821f9.png)

### Expected result

The UI should be consistent and offer a way for users to navigate different features easily 

### Materials and Reference

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
Hello @daikeshi , I am wondering how do you install the Kubeflow OSS? The KFP UI is hidden because it detects the existence of Central dashboard, if Central dashboard exists, Pipelines related left nav items are merged to Central dashboard. But I don't see the central dashboard from your screenshot, maybe you can click the `three lines` icon on top left?

Reference: https://github.com/kubeflow/pipelines/blob/master/frontend/src/components/SideNav.tsx#L264-L266

https://github.com/kubeflow/pipelines/issues/5199

**Comment by daikeshi** [comment]
@zijianjoy ok I see. We deployed KFP along with OSS central dashboard component with our customized Kubeflow setup. 

Yeah, clicking the three `lines icon` on the top will bring the central dashboard menu selection back, but our users typically don't use it and we are on an older version of the central dashboard. Would it be possible to override [`HIDE_SIDENAV` flag](https://github.com/kubeflow/pipelines/blob/master/frontend/server/configs.ts#L102) on my end via the deployment?

**Comment by zijianjoy** [comment]
You can configure in here https://github.com/kubeflow/pipelines/blob/master/manifests/kustomize/base/installs/multi-user/pipelines-ui/deployment-patch.yaml
