### ISSUE TITLE
[bug] pipeline_manifest not returned by the api

### ISSUE THREAD

**Issue by jynx10** [kubeflow/pipelines#7135]
### What steps did you take
Sent a request to find a specific run by id (to the /apis/v1beta1/runs/{run_id} endpoint).

### What happened:
In the response I received only the workflow_manifest property.

### What did you expect to happen:
I expected both the pipeline_manifest and workflow_manifest properties to be returned as part of the apiPipelineRuntime Object.

### Environment:

*  How do you deploy Kubeflow Pipelines (KFP)? 
* I started a minikube cluster and applied the kubeflow pipelines to it.

*  KFP version: 
Version 1.7.0

*  KFP SDK version: 
kfp                               1.8.10
kfp-pipeline-spec                 0.1.13
kfp-server-api                    1.7.1

### Labels

/area backend
/area sdk

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by chensun** [comment]
> I expected both the pipeline_manifest and workflow_manifest properties to be returned as part of the apiPipelineRuntime Object.

@jynx10 why would you expect this, is this the behavior in some old version?

Just by looking at the code, it seems to be by design that only one of them is returned, and `workflow_manifest` is looked first: https://github.com/kubeflow/pipelines/blob/2e945750cb1758eea6db8453b437e57e68152b4a/backend/src/apiserver/resource/resource_manager.go#L995-L999
