### ISSUE TITLE
[feature] to_csv in google_cloud_pipeline_components's bigquery operators

### ISSUE THREAD

**Issue by ckchow** [kubeflow/pipelines#7160]
### What feature would you like to see?
Google cloud pipeline components (https://github.com/kubeflow/pipelines/tree/master/components/google-cloud/google_cloud_pipeline_components) is missing an operator to export a bigquery query result to CSV. This is currently provided by https://github.com/kubeflow/pipelines/tree/master/components/gcp/bigquery/query strictly speaking, but that component has issues with the GCPProjectID type not being well supported.

### What is the use case or pain point?
We export some data to CSV for XGBoost training.

### Is there a workaround currently?
We use a version of the component linked in part 2 above, but with some of the types lowered to String from GCPProjectId.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by sfujiwara** [comment]
I think a good way to solve the problem is modifying the component to receive `JobConfigurationExtract`. Current component can receive only `JobConfigurationQuery` here:

https://github.com/kubeflow/pipelines/blob/c8a18bde299f2fdf5f72144f15887915b8d11520/components/google-cloud/google_cloud_pipeline_components/experimental/bigquery/query_job/component.yaml#L84-L91

We are happy if we can pass the other configurations such as `JobConfigurationTableCopy`, `JobConfigurationExtract` and `JobConfigurationLoad`:
https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#jobconfiguration

**Comment by sfujiwara** [comment]
I need the feature, but this issue was pending for months. If the maintainers are busy, I want to contribute. So I'm curious about
- How do you think about the above idea?
- The maintainers have a plan to add some features to solve this issue?

**Comment by gveltri** [comment]
Bumping this. It looks like the component for exporting bigquery to csv was altogether removed from the library. Would there be any chance of adding this back?
