### ISSUE TITLE
[bug] Unable to obtain the output of a graph component for downstream components

### ISSUE THREAD

**Issue by akshayc11** [kubeflow/pipelines#7224]
### What steps did you take
In a folder, created the following:
c1.yaml
```yaml
name: Dummy Component A
description: Manually Created Component Spec
inputs:
  - name: Arg Input
    type: String
outputs:
  -  name: Arg Output
     type: String
implementation:
  container:
    image: dummy-image:1.0
    command: [
        "dummy", "command", "A"
    ]
    args: [
        "--arg-input", {inputValue: Arg Input},
        "--arg-output", {outputPath: Arg Output}
    ]
```

c2.yaml
```yaml
name: Dummy Component B
description: Manually Created Component Spec
inputs:
  - name: Arg Input
    type: String
outputs:
  -  name: Arg Output
     type: String
implementation:
  container:
    image: dummy-image:1.0
    command: [
        "dummy", "command", "B"
    ]
    args: [
        "--arg-input", {inputValue: Arg Input},
        "--arg-output", {outputPath: Arg Output}
    ]
```

build_dummy_pipeline.py
```python
import kfp.components
import kfp
import kfp.compiler

c1_func = kfp.components.load_component("c1.yaml")
c2_func = kfp.components.load_component("c2.yaml")


def generate_graph_component_func():
    @kfp.dsl.graph_component
    def c1_graph_component(input_arg):
        c1_op_a = c1_func(arg_input=input_arg)
        c1_op_b = c1_func(arg_input=c1_op_a.output)
        return {"Graph Output": c1_op_b.output}
    return c1_graph_component

c1_graph_comp_func = generate_graph_component_func()

@kfp.dsl.pipeline(
    name="Dummy Pipeline",
    description="Dummy Pipeline"
)
def dummy_pipeline(input_arg: str):
    graph_comp_op = c1_graph_comp_func(input_arg)
    c2_op_a = c2_func(arg_input=graph_comp_op.outputs["Graph Output"])
    return c2_op_a.output

kfp.compiler.Compiler().compile(dummy_pipeline, "dummy_pipeline.yaml")
```

```Command run:
python3 build_dummy_pipeline.py
```

### What happened:
```bash
Traceback (most recent call last):
  File "build_dummy_pipeline.py", line 28, in <module>
    kfp.compiler.Compiler().compile(dummy_pipeline, "dummy_pipeline.yaml")
  File "/Users/achandrashekaran/PycharmProjects/kf-model-trainer/.venv/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 1064, in compile
    package_path=package_path)
  File "/Users/achandrashekaran/PycharmProjects/kf-model-trainer/.venv/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 1119, in _create_and_write_workflow
    pipeline_conf)
  File "/Users/achandrashekaran/PycharmProjects/kf-model-trainer/.venv/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 900, in _create_workflow
    pipeline_func(*args_list, **kwargs_dict)
  File "build_dummy_pipeline.py", line 25, in dummy_pipeline
    c2_op_a = c2_func(arg_input=graph_comp_op.outputs["Graph Output"])
KeyError: 'Graph Output'

```
### What did you expect to happen:
On running the above python script, I expected the output of the graph component to be passed to c2_op_a and the pipeline to compile successfully.

### Environment:

*  How do you deploy Kubeflow Pipelines (KFP)? 

*  KFP version: 1.7.1

*  KFP SDK version: -NA- 

### Labels

/area sdk

/area components

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by ckchow** [comment]
It looks like maybe https://github.com/kubeflow/pipelines/blob/6965dbac2faee0411fc0ca9565fd9a9d7ef8e2bf/sdk/python/kfp/dsl/_component.py#L148 is missing assigning graph_ops_group.outputs when it assigns inputs and arguments. I would love to contribute a fix but it's not clear to me where to add a unit test for this.

**Comment by ckchow** [comment]
One could write to an external system (e.g. GCS, S3) and have downstream components read from an agreed-upon path. Feels pretty side-effecty though.

**Comment by grbaiges** [comment]
Not sure why this thread is open but inactive, I believe this is still a problem. The [documentation](https://kf-pipelines.readthedocs.io/en/latest/source/kfp.dsl.html?highlight=graph#kfp.dsl.graph_component) for this feature is quite brief, there is no mention for instance to the fact that you can only pass PipelineParams to these Graph Components.

Also, if I'm not mistaken this feature is not a new feature, rather it is an iteration of this [old feature](https://kubeflow-pipelines.readthedocs.io/en/1.8.13/source/kfp.components.html#kfp.components.create_graph_component_from_pipeline_func), which at the time was experimental. And I'm pretty sure also that I saw in some release notes (v1.7 I think, although I couldn't find it now) that indeed this `GraphComponent` was the stable version of that old experimental feature.

I'm a bit surprised cause the experimental feature allowed for returning outputs from a graph component using an `OrderedDict`. I tried the old implementation and it worked, and now this feature is not available for the `Graph Component` even though the documentation suggests it is (using plain dictionaries instead of `OrderedDict`). Also, with the old feature it was possible to pass various types of parameters (mainly raw data structures) to what is now the `Graph Component`, not only `PipelineParams`.

Are there any plans to keep working on this feature? Is it stable? Glad to help on it if there is interest on maintaining & improving this feature.

**Comment by rimolive** [comment]
I need the author and commenters in this issue to help me validate some things, but this seems an issue in Kubeflow Pipelines 1.7.1 but now we're in 2.2.0 release and much of these features were deprecated or completely removed/redesigned.

That said, I'd like to ask some questions:
* How would this be applicable in the latest release? Is it something we want to implement in v2?
* How this method is different from the [ones](https://www.kubeflow.org/docs/components/pipelines/v2/components/) already added to KFPv2?

**Comment by akshayc11** [comment]
Unfortunately I've moved on ahead from the project that was trying to using this feature. So I don't know if this has been addressed by changes in KFPv2.

**Comment by guillemrbaiges** [comment]
@rimolive Do you mean there's an equivalent feature in 2.2.0 for this use case? I saw the feature become this `GraphComponent` after a big refactor and I assumed it was quite up-to-date.  I don't see anything in your link that resembles this functionality, at the end of the day the `GraphComponent` was turning a pipeline into a component, which was a pretty neat feature that allowed for more modular and reusable pipelines. I'd really appreciate it if you could share how this could be done in KFP v2
