### ISSUE TITLE
[feature] Remove custom hash suffix to end of KFP pipeline name in executions

### ISSUE THREAD

**Issue by calvinleungyk** [kubeflow/pipelines#7327]
### Feature Area
/area backend

### What feature would you like to see?

Remove custom hash suffix to end of KFP pipeline name in executions

### What is the use case or pain point?

KFP adds a custom hash to the end of the pipeline name similar to how kubernetes adds a unique suffix to pod names. This makes it hard to query runs and metadata of pipelines after the execution. 

### Is there a workaround currently?

Users have to query for the correct execution or context and get the relevant id then get the desired pipeline which is counter intuitive and troublesome.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by chensun** [comment]
There needs to be some unique name, otherwise, if you run a pipeline multiple time, how would we differentiate them?

> Users have to query for the correct execution or context and get the relevant id then get the desired pipeline which is counter intuitive and troublesome.

This feels a reasonable pattern to me. Otherwise, I guess you're looking for a filtering by partial match query? You would still need to have a way to pick one from the filtered list in case there are multiple matches.
