### ISSUE TITLE
[feature][question]When output artifacts, is there a way to disable compression?

### ISSUE THREAD

**Issue by yangyang919** [kubeflow/pipelines#7343]
We have one kubeflow pipeline to train a model and then output a model to Minio storage. Then we are using KServe to fetch the model from Minio and deploy it. But by default, the model is compressed as tgz file in Mino, which makes KServe couldn't load the model.
Any guidance on how to solve this? Thanks!!!

**Comment by ammubharatram** [comment]
@yangyang919 hi, any help you can provide on solving the same? Thanks in advance.

**Comment by khituras** [comment]
I have limited experience with this topic. However, I successfully used SeldonIO/MLServer to load a SKLearn model that I previously trained using Kubeflow Pipelines. This worked fine in the end (I actually had to adapt the model path in the MLServer container to get it to work). The compression issue was actually not a problem because the `storage initializer` container, that runs before the KServe runtime is being executed, handles the decompression of the `tgz` archive. This worked fine with Kubeflow 1.7, installed via manifests.
Best to check the logs of the containers to find the actual issue.

HTH
