### ISSUE TITLE
[feature] Add a param in create_recurring_run to support override the exists job with the same name in the same experiment

### ISSUE THREAD

**Issue by haoxins** [kubeflow/pipelines#7435]
### Feature Area

/area sdk

### What feature would you like to see?

Add a param in `create_recurring_run` func to support override exists recurring job with the same name.

### What is the use case or pain point?

In my use case, when I changed the logic of my job, I will remove the jobs with the same name first,
and create a new one with the same name again.
I do this because I don't want to create duplicated jobs.

The code will looks like

```python
recurring_run_name = "..."
recurring_run_description = "..."

jobs = kfp_client.list_recurring_runs(
    experiment_id=experiment_id,
    filter=filter_by_job_name,
    ...
).jobs

if jobs != None:
    # Delete the jobs

kfp_client.create_recurring_run(
    experiment_id=experiment_id,
    job_name=recurring_run_name,
    description=recurring_run_description,
    ...
)
```

So, would it accepted for you guys to add a param such as `replace_exists` to implement these logic.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by connor-mccarthy** [comment]
Currently we don't have a plan for implementing this feature in `kfp`. If you are interested in contributing this feature, could you please compose a design doc for discussion in the Kubeflow Pipelines Community meeting?

**Comment by haoxins** [comment]
Yeah, I can contribute to this.

And this should be a small change so that is it really need a design doc?

I think there are only two things need to be agreed?

1. What is the param name should be?
2. Is the flow I provided fine to be accepted?
2.1 `list_recurring_runs()`: List the runs by `experiment_id` and `job name`
2.2 `Delete the jobs`

**Comment by connor-mccarthy** [comment]
Thanks for your response, @haoxins, and for your interest in contributing! And thanks also for contributing a comment fix the other day -- that's very helpful.

**Why a design doc**
I do think a design doc is warranted to explore two aspects of this contribution:

1) **Costs and benefits of including this feature.** User-facing features in particular require maintenance and possibly slow down future feature development in an effort to maintain complete functionality and backward-compatibility. Those are some of the costs, so it's helpful to explicitly lay out the benefits.

2) **Different approaches for implementation and their associated costs and benefits.** I think there are a few complexities that may be introduced at implementation time. The current suggested implementation probably would get us most of the way there, but may have some unintended side-effects that are worth exploring in a design doc.

**Some considerations**
For number 2 of "Why a design doc", I think it may make more sense to implement the CRUD logic in the backend instead of doing so in the SDK. Put differently: we probably would want an SDK PUT rather than an SDK DELETE + POST. This is both a) consistent with the current paradigm of the SDK as a client of the backed and b) allows the backend to do additional cleanup and reference updating associated with deleting a job. @zijianjoy can speak more to the backend responsibilities for an operation like this. This is just one example of some of the considerations that should be explored in a design doc.

**Design doc structure**
A basic design doc structure is:
1) What is the user story? In other words: what is the objective of the feature contribution? What are users **current** options for achieving this objective?
2) What are some reasonable ways of implementing this objective as a feature? Include pros/cons. (This addresses number 1 of "Why a design doc".)
3) Pick a preferred solution from "Design doc structure" part 2. What options are there for implementing this solution? Include an explanation, API/code snippets (if relevant), and pros/cons for each. (This addresses number 2 of "Why a design doc".)
4) Are there any additional considerations not already discussed?

Please don't be discouraged by the enumeration of parts 1-4 here. My intention by being explicit is actually to make the design doc _easier_ to put together. Each section can be somewhat brief so long as it captures the key points.

Thanks again and please follow up with any questions.

cc/ @ji-yaqi @chensun
