### ISSUE TITLE
[feature] Option to disable downloading of artifacts through UI

### ISSUE THREAD

**Issue by bodak** [kubeflow/pipelines#7445]
### Feature Area

/area frontend
/area backend

### What feature would you like to see?

- Option to disable the ability to download artifacts from the front-end UI. Some form of this would limit accidentally clicking the download link.
- Option to restrict access to the back-end artifact storage. Some form of this would limit "guessing" the download link (unsure if that is even possible).

### What is the use case or pain point?

We work with sensitive data. It is very simple to download artifacts produced from the front-end UI and save locally.

### Is there a workaround currently?

1. I have not found any option in https://github.com/kubeflow/pipelines/blob/master/frontend/server/app.ts#L119-L150, but I might have been looking in the wrong places.
2. We are looking into blocking access between the minio server and the UI server through kubernetes.

**Comment by zijianjoy** [comment]
Hello @bodak , are you using full fledged Kubeflow deployment? That is the only way we can use multi-user mode, where artifact access control is possible.

Also, data access restriction should be enforced on the storage side, by allowing only the selected personnel to download them. If such access control is in-place, UI doesn't need to do anything to disable download. It is because UI only open a URL link for download, which is coming from storage solution (based on which storage you are using). So if you are managing sensitive data, that restriction should happen on the storage IAM side. 

If using minio, I am not sure whether whether minio has such access control, if not, it is the limitation on minio side.

**Comment by bodak** [comment]
Thanks for the explanation! This was for Kubeflow Pipelines only.
Your suggestion makes sense and restriction on the storage side were already implemented.
I'll close this issue.
