### ISSUE TITLE
[question] who create the pipeline pods 

### ISSUE THREAD

**Issue by zhuyaguang** [kubeflow/pipelines#7485]
when we run the pipeline, in the   namespace "kubeflow-user-example-com" will create pods to exec the pipeline.

my question is ,who create it ?   There is no deploy corresponding to it.

**Comment by nicolaiskogheim** [comment]
I read somewhere that it is a pod that creates your pods, but for all I know it could be Custom Resource Definition stuff. But Kubeflow Pipelines runs on Argo Workflows as the workflow engine, so you might want to Google in that direction.
Otherwise I recommend you hop onto the [Kubeflow slack](https://www.kubeflow.org/docs/about/community/). I've had a positive experience there.

**Comment by jszendre** [comment]
When using Argo, it is the Argo controller that spins up pods and monitors them while executing the DAG.

**Comment by zijianjoy** [comment]
Hello @zhuyaguang , please confirm if the answers from @jszendre sound good to you. Feel free to reopen this issue if not.
