### ISSUE TITLE
Support cloning run started from notebook

### ISSUE THREAD

**Issue by yebrahim** [kubeflow/pipelines#75]
Currently, runs have two ways of telling which pipeline was used to start them:
- Either a pipeline was uploaded to the system first, in which case  the run will include its id.
- Or the run was started from a notebook (or CLI), in which case it will (can) embed the entire pipeline spec.

The UI should be passing that spec when cloning a run that does not have a pipeline id. We need to also figure out the UX, since a user might still be able to change their mind after starting a clone from a run, then want to switch to another pipeline.

@ajayalfred any thoughts here?

**Comment by ajayalfred** [comment]
Spec for handling pipeline column in runs generated from Notebook.

In the pipeline column, replace name with a link 'View pipeline' when a pipeline ID is not available.

![image](https://user-images.githubusercontent.com/2425179/48799982-5000bd80-ecbd-11e8-9462-1a23129a9b49.png)

Selecting the link, takes the user to the pipeline details page with the app bar as show below.

![image](https://user-images.githubusercontent.com/2425179/48800011-67d84180-ecbd-11e8-85f3-4b1ce145ceda.png)

No actions to be displayed. We will reassess if actions are needed at a later point. Use 'Experiments > [run name]' breadcrumb to navigate back to the runs list.

**Comment by yebrahim** [comment]
The breadcrumbs should show the run name too, not just the experiment name. This is very important I think, since it's the only usable identifier for this pipeline.

**Comment by ajayalfred** [comment]
You're correct, I mixed up the breadcrumbs.

With the correct path displayed in breadcrumbs, it's confusing though what the back button will do... since the user arrives on the pipeline page directly from the experiment details page.
![image](https://user-images.githubusercontent.com/2425179/48804916-c6f08300-ecca-11e8-9ded-1e30edb018d6.png)

Alternative is to show the run name in brackets in page title
![image](https://user-images.githubusercontent.com/2425179/48804990-f7d0b800-ecca-11e8-8545-c78c05ecd982.png)

**Comment by yebrahim** [comment]
If the user observed that the back button just does browser back, it won't be confusing at all. It'll take the user back to the previous page (list page), and the breadcrumbs are there in case the user wants to navigate to that run from the pipeline details page.

**Comment by ajayalfred** [comment]
Ok opt 1 sounds good.
