### ISSUE TITLE
[grpc-gateway] upgrade grpc-gateway to v2

### ISSUE THREAD

**Issue by hsinhoyeh** [kubeflow/pipelines#7730]
### Feature Area

[grpc gateway](https://github.com/grpc-ecosystem/grpc-gateway) provides an HTTP way to communicate the underlying GRPC services (defined in the same proto file), and since version v1.14, the community suggests that the v1 is under maintenance mode and suggest to upgrade to v2. https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v1.14.7
However, the current Kubeflow pipeline is still using v1 (as you can see here https://github.com/kubeflow/pipelines/blob/master/backend/api/hack/generator.sh#L33)

It is well understood that upgrading from v1 to v2 of grpc-gateway might not be straightforward. just wondering that is this need imporoving? or you would need some hands?

/area backend

### What feature would you like to see?
use grpc-gateway v2 

### What is the use case or pain point?
some binaries are gone since v2, it's hard to track them.

### Is there a workaround currently?
currently, the upstream of kf pipeine use v1 which is under maintaince mode of grpc-gateway.

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by connor-mccarthy** [comment]
cc/ @zijianjoy

**Comment by zijianjoy** [comment]
Thank you @hsinhoyeh ! Indeed we are still using grpc-gateway v1 and I hope we can upgrade to v2. However, there are breaking changes that I don't have enough bandwidth to look into yet. I am hoping that we can introduce a new API package which can keep this upgrade contained. If you have tried to upgrade, do you know the breaking changes which are caused by upgrading from v1 to v2?

cc @Linchin @annajung @difince
