### ISSUE TITLE
Please support the traffic_percentage argument in the deploy_endpoint Google Cloud Pipeline Component

### ISSUE THREAD

**Issue by jasonbrancazio** [kubeflow/pipelines#7836]
The [aiplatform.Model.deploy](https://github.com/googleapis/python-aiplatform/blob/main/google/cloud/aiplatform/models.py#L629
) method allows users to specify either a traffic percentage or a traffic split parameter. Either, but not both, can be used to specify the amount of traffic to route to a newly deployed model.

The Google Cloud Pipeline Components [ModelDeployOp](https://github.com/kubeflow/pipelines/blob/master/components/google-cloud/google_cloud_pipeline_components/aiplatform/endpoint/deploy_model/component.yaml#L14), however, does not support the traffic percentage parameter.

Please support the traffic percentage parameter in a future version of ModelDeployOp. The traffic percentage parameter makes it much easier to create canary deployments of new models. This is because the traffic split parameter requires advance knowledge of the ids of all other models deployed to the Endpoint when splits other than {'0': 100} are specified.

**Comment by jasonbrancazio** [comment]
Note that the traffic_percentage argument is not supported in the V1 [ModelDeployOp](https://github.com/kubeflow/pipelines/blob/master/components/google-cloud/google_cloud_pipeline_components/v1/endpoint/deploy_model/component.yaml) either.

**Comment by IronPan** [comment]
The ModelDeployOp interface aligns with the [API definition](https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.endpoints/deployModel) instead of the Vertex SDK which is another wrapper around it. It doesn't align with the [Vertex SDK](https://github.com/googleapis/python-aiplatform/blob/main/google/cloud/aiplatform/models.py#L629) interface unfortunately. This is by design.
