### ISSUE TITLE
[feature] Add primary key to DB tables

### ISSUE THREAD

**Issue by ca-scribner** [kubeflow/pipelines#8014]
### Feature Area

/area backend

### What feature would you like to see?

That kfp create [its database](https://github.com/kubeflow/pipelines/tree/5a56a9399908033ce97573abf85098fd77f649ae/backend/src/apiserver/model) with a primary key (probably [here](https://github.com/kubeflow/pipelines/blob/5a56a9399908033ce97573abf85098fd77f649ae/backend/src/apiserver/model/default_experiment.go#L18) and [here](https://github.com/kubeflow/pipelines/tree/5a56a9399908033ce97573abf85098fd77f649ae/backend/src/apiserver/model), with something like:
```
DefaultExperimentId string `gorm:"column:DefaultExperimentId; not null; primary key"`
```

### What is the use case or pain point?

Primary keys are required for group replication (high availability) of tables in mysql.  Enabling this would enable using more resilient data storage.

### Is there a workaround currently?

I don't know if this is safe, but perhaps I can separately create the database following kfp's schema (but with a primary key) and then have kfp connect to that existing DB?  I'm not sure what the consequences of this would be. 

**update:** This appears to work (application starts without errors, etc).  Haven't stress tested it yet

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by Linchin** [comment]
@ca-scribner Hi, we do create each DB with a column as primary key, see examples [here](https://github.com/kubeflow/pipelines/blob/061905b6df397c40fbcc4ffafa24d7b3b9daf439/backend/src/apiserver/model/run.go#L26) and [here](https://github.com/kubeflow/pipelines/blob/061905b6df397c40fbcc4ffafa24d7b3b9daf439/backend/src/apiserver/model/experiment.go#L4). But indeed, in the example DB you gave (DefaultExperiment) we didn't set a column to primary key. Did you mean you want to set a primary key for this specific table?

**Comment by ca-scribner** [comment]
Sorry, I'm working as a bit of a proxy here.  @shayancanonical or @paulomach can you comment?

**Comment by paulomach** [comment]
Hi @Linchin,

> Did you mean you want to set a primary key for this specific table?

Yes, and for any other table without a PK. 

> Also, I'm not sure if a primary key is necessary for DefaultExperiment table. Looks like the table has only one entry, which is the default experiment.

Even though we understand that the application does not need a PK to this table, in order to use MySQL with high availability (i.e. group replication plugin), it's required that *every* table have a PK.

This won't hurt the application, and will enable it to have a fault tolerant database, hence the proposal.

**Comment by Linchin** [comment]
I see. I will go ahead and create a PR for this.

**Comment by shayancanonical** [comment]
@Linchin we already opened a [PR](https://github.com/kubeflow/pipelines/pull/8023) with the requested changes (adding primary keys to `default_experiments` and `db_statuses` table). please feel free to close it or add to it if we missed anything!

**Comment by Linchin** [comment]
Thanks! I created another PR so I will close this one.

**Comment by chensun** [comment]
@Linchin given the two PRs are identical, I'd suggest we give credit to @shayancanonical and merge the PR that was created first. It's also our responsibility to actively monitor and review PRs from community contributors.

@shayancanonical a small tip to do avoid duplicate effort in the future: while you have "Fixes issue#" in the PR title which can close the issue upon PR merged, only when you have the same text in the PR description or comment section, the open PR will then be linked to the issue, so that those who look at the issue can easily see there's a proposed fix already.
