### ISSUE TITLE
[feature] Nested component

### ISSUE THREAD

**Issue by lightingghost** [kubeflow/pipelines#8094]
### Feature Area

/area components

### What feature would you like to see?

I would like to be able to do nested call to components, for example

```python
@component
def foo():
  pass

@component
def bar():
  foo()
```

### What is the use case or pain point?
* It helps reuse the code.

### Is there a workaround currently?
No.

---

Love this idea? Give it a 👍.

**Comment by connor-mccarthy** [comment]
Hi @lightingghost. Thanks for your feature request. This is concept of using a pipeline as a task is actually currently in development. You can look forward to this in an upcoming release.

**Comment by micmarty-deepsense** [comment]
heyyyy @connor-mccarthy, are there any updates or planned release date for that particular feature?
How could we help to move it forward?

You mentioned that it's in development, if there are any unofficial ways to test it, please let me know 😄

**Comment by connor-mccarthy** [comment]
This was released in [`2.0.0-beta.4`](https://github.com/kubeflow/pipelines/blob/39e4c3686acb75d2137cc1e17e19837fd85c3632/sdk/RELEASE.md#200-beta4). I suggest using [`2.0.0-beta.12`](https://github.com/kubeflow/pipelines/blob/39e4c3686acb75d2137cc1e17e19837fd85c3632/sdk/RELEASE.md#200-beta12), which includes other fixes/features since.

You can use pipelines in pipelines exactly as if they are components.

Here's an example of the usage: https://github.com/kubeflow/pipelines/blob/39e4c3686acb75d2137cc1e17e19837fd85c3632/sdk/python/test_data/pipelines/pipeline_in_pipeline.py

**Comment by hugzee3** [comment]
Hi there, is there a way to gather outputs of these nested pipelines as in component.outputs?

**Comment by hugzee3** [comment]
@connor-mccarthy , thank you!

**Comment by OmriLevyTau** [comment]
Hi! can I nest pipelines/components in V1 as well? or any work around you know?
I've seen there is a native way to do so in V2 but unfortunately need to use the older version.

Currently was not able to do such thing. Thanks!

**Comment by OmriLevyTau** [comment]
thank you!
