### ISSUE TITLE
Notebook option disappears from UI

### ISSUE THREAD

**Issue by krishnakarra** [kubeflow/pipelines#819]
<img width="1665" alt="screen shot 2019-02-12 at 4 35 15 pm" src="https://user-images.githubusercontent.com/43756117/52677833-4a91c880-2ee4-11e9-8914-3b0a4faf8418.png">

**Comment by vicaire** [comment]
@yebrahim @rileyjbauer, could you please have a look?

**Comment by yebrahim** [comment]
This will happen if you don't have access to /hub/ for whatever reason. Can you try to manually navigate to yourhost/hub/?
One way I've seen this fail is if you've deployed Kubeflow on a GKE cluster using IAP, then tried to access the cluster using port forwarding from your machine, in which case Jupyterhub block you because of auth method conflict.

**Comment by rileyjbauer** [comment]
Closing as this UX is now handled by Kubeflow core, not KFP
