### ISSUE TITLE
[bug] Disabling caching for a step by set_caching_options lead to disabling caching for subsequent steps

### ISSUE THREAD

**Issue by ysk24ok** [kubeflow/pipelines#8236]
I'm not sure if it's a bug or an expected behavior, but let me mark as a bug for now.

### Environment

*  How do you deploy Kubeflow Pipelines (KFP)? full Kubeflow deployment

*  KFP version: 1.8.1

*  KFP SDK version: 1.8.13

### Steps to reproduce

```py
from kfp import components, dsl
from kfp.v2.dsl import Dataset, Input, component

download_op = components.load_component_from_url(
    "https://raw.githubusercontent.com/kubeflow/pipelines/master/components/contrib/google-cloud/storage/download_blob/component.yaml"
)

@component
def print_file_content_op(file: Input[Dataset]) -> None:
    with open(file.path) as f:
        print(f.read())

@dsl.pipeline(name="caching-test")
def pipeline(path: str) -> None:
    download_task = download_op(path)
    download_task.set_caching_options(False)
    print_file_content_task = print_file_content_op(download_task.outputs["data"])
```

Submit the pipeline using `create_run_from_pipeline_func` with `V2_COMPATIBLE` mode two times.

We'll see `print_file_content_task` is not cached and executed on the second run.
The behavior is counterintuitive as I don't call `set_caching_options(False)` for `print_file_content_task`.

Why I call `download_task.set_caching_options(False)` because the file at the GCS path might be replaced at some point.
I know it would be better to upload a file to a different path instead of replacing the current file and make the step deterministic, but to do so we need to put some efforts to update our existing system.

### Expected result

`print_file_content_task` is cached and skipped if the file content is the same as before.

### Labels

---

Impacted by this bug? Give it a 👍.

**Comment by zijianjoy** [comment]
Hello @ysk24ok 

1. It is likely that `download_task` generates new output every time, even if the content is the same. As a result, if the upstream is not cached, then the downstream task will not be able to use cache.
2. We have deprecated V2_COMPATIBLE mode, please use 2.0.0-XXX and remove the use of `V2_COMPATIBLE`.

For now, the workaround is to pass the string value instead of Artifact to `print_file_content_op` to bypass the caching. We will think more about how to properly design the cache system. 

cc @chensun
