### ISSUE TITLE
[sdk] Containerized Python Component module not found error 

### ISSUE THREAD

**Issue by connor-mccarthy** [kubeflow/pipelines#8385]
There is a bug when building a containerized Python component that happens (at least) in the case when the longest path of the import graph ending at the component involves >2 modules. 

### Environment
KFP SDK 2.0.0-beta.6

### Steps to reproduce
For example:

```python
# component.py
from module_one import one
from kfp import dsl

@dsl.component
def comp(): ...
```

```python
# module_one.py
from module_two import two
one = 1
```

```python
# module_two.py
two = 2
```

Then: `kfp component build .`

You get a `No module named` error.

### Expected result

Should build without an error.

### Materials and Reference
Related: https://github.com/kubeflow/pipelines/issues/8353

**Comment by Davidnet** [comment]
Hi @connor-mccarthy I am trying to follow the docs and I ended up with the same error as #8353 how can I help to close this issue?

**Comment by Davidnet** [comment]
I can reproduce it with even one just module:

working directory:

```bash
├── main.py
├── poetry.lock
├── poetry.toml
├── pyproject.toml
└── utils.py
```

Where:

## main.py

```
from kfp import dsl
from .utils import return_date

@dsl.component(
    base_image='python:3.7',
    target_image='gcr.io/my-project/my-component:v1',
)
def main():
    x = return_date()
```

## utils.py

```
from datetime import datetime

def return_date():
    return datetime.now().strftime('%Y-%m-%d')
```


## Results:

```bash
╰─>$ kfp component build .
Building component using KFP package path: kfp==2.0.0-beta.11
attempted relative import with no known parent package
```

Alternatively: 

```bash
─>$ kfp component build bug/
Building component using KFP package path: kfp==2.0.0-beta.11
attempted relative import with no known parent package
```

Adding a `__init__.py` which is not in the docs:

 have the same results

**Comment by connor-mccarthy** [comment]
@Davidnet, thank you for the detailed reproduction notes. This is on our backlog.

> how can I help to close this issue?

If you're interested, you're welcome to address this bug and submit a PR!

**Comment by Davidnet** [comment]
@connor-mccarthy Awesome, thanks for the response any ideas on where could I start looking?

**Comment by connor-mccarthy** [comment]
Thanks, @Davidnet. Some links:

* [CLI entrypoint](https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/cli/cli.py#L96)
* [`kfp component build` command](https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/cli/component.py)
* [test code](https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/cli/component_test.py)
* [docs source](https://github.com/kubeflow/website/blob/master/content/en/docs/components/pipelines/v2/author-a-pipeline/components.md)

**Comment by b4sus** [comment]
Hey @connor-mccarthy,
some more considerations could be necessary, including having some recommended structure for the project. Additionally, I am no expert on python import system, so that's something as well :)

Let's assume standard (I think) python project (let's call it `myproject`) layout:
```
project_dir/
    myproject/
        __init__.py
        components/
            __init__py.py
            my_comp.py
        pipelines/
            __init__py.py
            my_pipelines.py
    pyproject.toml
    .gitignore
```
Now (considering my fix) you have to run `kfp` from `project_dir` like
```
kfp component build myproject/components
```
This will work, but there are caveats:
1. you have to use absolute imports (generally recommended afaik)
2. you have to use relative path for components (myproject/components) - you cannot build components somewhere else (because only current directory was added to `sys.path`)
3. if somewhere in `myproject/components` you have also lightweight components it will fail (because of missing base_image) - so you either need to separate those to different package - eg `myproject/components/lightweight` and `myproject/components/cont` - and then use `myproject/components/cont` as `kfp` input. Or you need to use `--component-filepattern`
4. complete content of `project_dir` will end up in docker image
5. possibly something else

All this is fine for me, but needs to be considered.

**Comment by connor-mccarthy** [comment]
> including having some recommended structure for the project

I agree with this. I'm working on a v2 docs refresh currently and will keep this in mind.

> but there are caveats

Thank you for laying out these considerations. In general, as long as there are no regressions (all existing user code that uses Containerized Python Components will still work), I'm happy to eagerly merge a better but not perfect fix. It sounds like some of these constraints may be been introduced by the proposed fix, however (such as the requirement to use the cwd `.` as the path). If that's the case, perhaps we ought to wait.

If we do wait, I'll take a stab at this soon and certainly leverage your investigation. Thank you again for the thorough writeup -- this helps a lot.

**Comment by Mithil467** [comment]
Thanks for the issue breakdown @b4sus and @connor-mccarthy.

I have created a PR https://github.com/kubeflow/pipelines/pull/9157 to essentially add the module directory to the sys.path within the `load_module` function.

**Comment by b4sus** [comment]
Just tested the fix with b15, nice to see progress in the topic :+1:
However :), it is not working for me - I have similar setup as mentioned above:
```
project_dir/
    myproject/
        __init__.py
        components/
            __init__py.py
            my_comp.py
        pipelines/
            __init__py.py
            my_pipelines.py
        utils.py
    pyproject.toml
    .gitignore
```
and using the absolute imports. From component module I import some util function from other module (via absolute import, eg in file `myproject/components/my_comp.py` using import `from myproject.utils import xyz`) -> the root package is not visible - `No module named 'myproject'` - what makes sense as it was never added to sys.path.
I guess with relative imports only it's working, but it would be great to also support absolute.

**Comment by pbalm** [comment]
This bug seems to have been introduced in `kfp==1.8.12`

**Comment by connor-mccarthy** [comment]
@b4sus, I've been looking into a fix for this and my sense is that we may not want to support absolute imports at this time, since it requires that the KFP component executor `pip install` the the user's package (in your example, the `myproject` package), which requires that KFP know something about the user's directory structure.

In a bit more detail, the `No module named 'myproject'` can be resolved at component build/compile time by running `pip install .` from `project_dir/` to install `myproject`. However, there will still be a `No module named 'myproject'` exception at component runtime, since KFP doesn't install the package in the component build (see the [Dockerfile](https://github.com/kubeflow/pipelines/blob/f9409a42d664cfbd2d6cb3f36997c14206a6586b/sdk/python/kfp/cli/component.py#L44) template) or runtime commands/args that execute the component.

This is of course something that we could change by adding additional parameters to the component build process or doing something "smart" under the hood in the component build logic, but I'm not sure the cost of either (a) exposing those parameters to users or (b) maintaining that smart logic is worth the benefit. It seems reasonable that the module that contains the component definition(s) should be runnable as a script (with relative imports), rather than something that requires pip installation (with absolute imports).

Let me know if you have other thoughts or if my understanding needs refinement.

Thank you, by the way, for the very helpful minimal reproducible example.

**Comment by b4sus** [comment]
Hey @connor-mccarthy ,
I understand the script nature - I also tend to run component as script to try (and I need to run it from `project_dir` for it to work).
However, as the project grows and let's say you want to have proper tests (under `project_dir/test`) and run them simply by `pytest tests` from `project_dir`, you will run into problem (using relative imports).

I might have another idea for a fix though :). What about adding `components_directory` (cli) argument from [build function](https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/cli/component.py#L393) to the path? Like this:
```python
def build(components_directory: str, component_filepattern: str, engine: str,
          kfp_package_path: Optional[str], overwrite_dockerfile: bool,
          build_image: bool, platform: str, push_image: bool):
    """Builds containers for KFP v2 Python-based components."""

    sys.path.append(components_directory)

    if build_image and engine != 'docker':
```
Then I can run `kfp build` wherever with argument pointing to `project_dir` and the absolute import should (tested locally) work. This would solve absolute imports, relative should not be affected. I cannot think of case when this would cause an issue, also shouldn't be maintenance heavy.
What do you think?

**Comment by Maxl94** [comment]
Hey @b4sus,

I have a similar project structure as you mentioned above. I wonder how you handle the component within the pipelines and how you separate the components. If the pipeline consist of more than one component, lets say `preprocessing` and `training`. 

```
project_dir/
    myproject/
        __init__.py
        components/
            preprocssing/
                __init__.py
                component.py
            training/
                __init__.py
                component.py
            __init__.py
        pipelines/
            __init__.py
            my_pipelines.py
        utils.py
    pyproject.toml
    .gitignore
```

For now I use a CI/CI pipeline to build and push the components and finally compile and submit the pipeline job (using Google Vertex AI).  The components build command looks like the following. This might be unorthodox, but this was the only way I could find, which works with absolute imports. 

```sh
kfp component build . --component-filepattern ${{ matrix.component }}/component.py --push-image
#  The matrix.component variable looks for example like thath "myproject/components/preprocessing"
```

Now the problem is, that the generate Dockerfile always has a `COPY . . ` command, which leads to a rebuild of the component everytime  I change anything in my project. This also mean I cant changes component without rerunning the whole pipline. That can be costly. 

Bevor the containerized python components I used the docker components and only copied the parts of the project relevant to the component. But that required a  lot of manual work and lead to errors because of files missing.
