### ISSUE TITLE
[sdk] latest releases of sdk are marked as "pre-release" on PyPI

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/pipelines#8450]
Currently, the latest version of the KFP SDK (`2.0.0b6`) is [marked as a "pre-release" on PyPI](https://pypi.org/project/kfp/#history).

This is problematic for 2 main reasons:

1. If a user runs `pip install kfp` they will get `1.8.14`, which will not include 2.0.0 features
1. Kubeflow 1.6 [includes Kubeflow Pipelines `v2.0.0-alpha5`](https://www.kubeflow.org/docs/releases/kubeflow-1.6/#component-versions)

**Comment by chensun** [comment]
This is by design. KFP v2 is currently in progress, and we're not ready to claim GA yet. 
The 2.0 alpha version of KFP included in Kubeflow 1.6 fully supports KFP v1 feature with the addition of v2 feature in alpha phase. Users can continue using KFP SDK 1.8.* with Kubeflow 1.6 for v1 features. Alternatively, they may choose to try out v2 features by explicitly upgrading to KFP SDK 2.0-beta.
