### ISSUE TITLE
[feature] Export VertexModels in python function based components in Vertex Pipelines.

### ISSUE THREAD

**Issue by wardVD** [kubeflow/pipelines#8513]
### Feature Area

I wanted to create a custom component from a python function that creates a VertexModel artifact when running with Vertex Pipelines.

I thought it could be as simple as something like this (dummy code):

```
from google_cloud_pipeline_components.types.artifact_types import VertexModel

@component(
    base_image="python:3.9-slim",
)
def ModelUploadCustomOp(
    model_name: str,
    model: Output[VertexModel],
):

model.uri = <MODEL_URI_STRING>
```

The compilation step works, but running gives me the following error:

```
model: Output[VertexModel],

NameError: name 'VertexModel' is not defined
```

Is there a way on how to create a python function based component that creates a VertexModel artifact in Vertex Pipelines?

---

Love this idea? Give it a 👍.

**Comment by connor-mccarthy** [comment]
@wardVD, thanks for your question. Can you let me know which version of the KFP SDK you're using? If it's `kfp==1.x.x` or `kfp<2.0.0b5` this is expected.

For `kfp>=2.0.0b5`, the `VertexModel` symbol will be defined, but the GCPC library is not yet compatible with KFP v2 (this is a work in progress) so this will still not work yet.

**Comment by morningcloud** [comment]
Hi @connor-mccarthy, Are there any updates regarding this? I wanted to use ModelUploadOp component and pass the parent_model argument in order to upload a new version to an existing model. Based on the documentation this expects a VertexModel so wanted to create a custom python component that a model name and returns the existing VertexModel, but faced this error.
What other ways can this be done as of now?

**Comment by connor-mccarthy** [comment]
Hi, @morningcloud. There is no elegant solution for this currently that allows you to use a `VertexModel` directly, but since the `dsl.Artifact` type is compatible with all other artifact types, returning a `dsl.Artifact` may be a useful workaround for the time being [[docs](https://github.com/kubeflow/pipelines/issues/8513)].
