### ISSUE TITLE
feat(backend): Support loop parallelism

### ISSUE THREAD

**Issue by chensun** [kubeflow/pipelines#8718]

**Comment by abln-synth** [comment]
Is there a timeline for truly  supporting `ParallelFor` parallelism in Kubeflow v2? We're in the process of adopting Kubeflow and this is a major deal-breaker for us

**Comment by jbottum** [comment]
Can someone from the KFP team please comment on this issue?   Can users please identify your use case and the priority of this request i.e. is this must have for your use case ?

**Comment by abln-synth** [comment]
@jbottum 

We use Kubeflow to run massivelly parallel inference pipelines, where we potentially have hundreds / thousands of inputs but we can't feasibly run them all in parallel (due to resource limitations), hence why controlling the parallelism is a must-have for us.

We are successfully doing that with Kubeflow v1, but we feel like we're missing out on more and more on the new functionalities that are offered in v2.

**Comment by rdowdVivante** [comment]
I would like to double down on this feature being important in workflows for my organization as well. We have shared utils-type components that need to be looped over multiple times due to time shifts that need to be accounted for. Running the util component in parallel would be way better time wise than just running the loop in a standard sequential way. Please provide updates on potential support!

**Comment by rimolive** [comment]
Some users reached out to me about this missing feature in v2 saying this is a blocker to upgrade to that version. I kindly ask for anyone who will comment in this issue to request priority to :+1: the issue description as this is how we rank the most demanding requests from community.

As for the prioritization itself, I'll come up with a plan to the Pipelines WG to speed up the development of this feature. If anyone wants to discuss, join the next Pipelines WG meeting.

**Comment by HumairAK** [comment]
I can take this on 

/assign @HumairAK

**Comment by chanansh** [comment]
any news about this? it stops be from using Elyra https://elyra.readthedocs.io/en/latest/
I want component A to generate a list of tasks and then parallel execute them with component B

**Comment by rimolive** [comment]
@chanansh Still WIP, but we'll keep updating this issue when we have more information to share.

**Comment by sylphsang** [comment]
> [@jbottum](https://github.com/jbottum)
> 
> We use Kubeflow to run massivelly parallel inference pipelines, where we potentially have hundreds / thousands of inputs but we can't feasibly run them all in parallel (due to resource limitations), hence why controlling the parallelism is a must-have for us.
> 
> We are successfully doing that with Kubeflow v1, but we feel like we're missing out on more and more on the new functionalities that are offered in v2.

I am also looking for this feature; please let us know when it will be available.
