### ISSUE TITLE
fix(backend/frontend): Run status inconsistency between pipeline and its component

### ISSUE THREAD

**Issue by chensun** [kubeflow/pipelines#8725]

**Comment by gkcalat** [comment]
I was able to reproduce it. A possible root cause for this behavior is a failed MLMD update at runtime. As UI calls MLMD to get states of individual node (tasks) in a DAG, we can observe inconsistent states between run' state and its underlying tasks' states. This is already implemented in the backend in #8850.

To fix, UI needs to switch to reading states of the nodes from the v2 API's [run details](https://github.com/kubeflow/pipelines/blob/2.0.0-beta.1/backend/api/v2beta1/run.proto#L200), which carries states for each task coming from the KFP DB.

KFP DB (correct state):![mysql_updated](https://user-images.githubusercontent.com/35157096/236270780-ce61947f-09f0-4ad8-b98e-6d17456b1ec0.png)

MLMD (stale):
![MLMD_stale](https://user-images.githubusercontent.com/35157096/236270835-c01b472c-59c2-486d-be64-41f18120a563.png)

UI integration is a post-GA work item: #8966 

/cc @jlyaoyuli
