### ISSUE TITLE
Cannot Import functions written in the same file 

### ISSUE THREAD

**Issue by vikashg** [kubeflow/pipelines#8792]
Hello all, 
I am trying to build a pipeline, the structure of which is like the following 

`some_function.py`: This file contains 2 functions `func1` and `func2`. `func2` uses `func1` and gives an output

in my pipeline I will import the func2 as 
`from some_function import func2`

due to this I get the following error
`NameError: name `func1` is not defined`

But if I copy the contents of `func1` inside `func2`, this works. Can someone shed some light on this? I am not able to figure this out. 
Thanks in advance

![image](https://user-images.githubusercontent.com/3863212/216661909-b47211b1-0e10-48e1-b2fd-3ceb642924b3.png)

**Comment by connor-mccarthy** [comment]
@vikashg, I suspect you are describing a component runtime error for a [Lightweight Python Component](https://www.kubeflow.org/docs/components/pipelines/v2/author-a-pipeline/components/#1-lighweight-python-function-based-components).

This is expected behavior; the Lightweight Python Component function only has access to the code/symbols defined within its scope [[ref](https://www.kubeflow.org/docs/components/pipelines/v2/author-a-pipeline/components/#1-lighweight-python-function-based-components:~:text=A%20standalone%20Python%20function%20is%20a%20function%20that%20does%20not%20reference%20any%20symbols%20defined%20outside%20of%20its%20scope.)].

**Comment by vikashg** [comment]
Thanks @connor-mccarthy
