### ISSUE TITLE
[sdk] KFP CLI has dependencies on vendor specific tooling (Google Cloud Tooling)

### ISSUE THREAD

**Issue by ReggieCarey** [kubeflow/pipelines#8843]
### Environment

*  KFP version:
KFP as installed by Kubeflow Manifests 1.6.0 onto private k8s.

*  KFP SDK version: 
Local install (MacOS) as installed via pip install kfp (as of Feb 13, 2023)

*  All dependencies version:
kfp                      1.8.18
kfp-pipeline-spec        0.1.16
kfp-server-api           1.8.5

### Steps to reproduce

Attempt to execute 'kfp diagnose me' on MacOS.

```
$ pip install kfp --upgrade
$ kfp diagnose_me
Google Cloud SDK is not installed, gcloud, gsutil and kubectl are required for this app to run. Please follow instructions at https://cloud.google.com/sdk/install to install the SDK.
```

### Expected result

I expected that an open source tool would not have a dependency on a commercial implementation of Kubernetes or be tied to Kubeflow Pipelines deployed to Googles infrastructure.

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by gkcalat** [comment]
Hi @ReggieCarey!
Thank you for reporting it. This component is not actively developed. If you wish, please create a PR adding the support for non-GCP distributions of kubernetes.

**Comment by ReggieCarey** [comment]
Thanks for the feedback! Great community. What was diagnose me supposed to do? I'll try to find the code and answer that myself. If it's not actively maintained, should it be removed for marked in some way?

**Comment by connor-mccarthy** [comment]
Thanks, @ReggieCarey. `diagnose_me` was created to programmatically capture a variety of information about a K8s deployment on GCP to help expedite debugging.

This tool is best thought of as a helper script for a particular form of deployment. Kubeflow Pipelines has no dependency on GCP.

Since your inquiry we've been discussing how to handle the `diagnose_me` command for KFP v2.
No update yet, but you raise good considerations that we're taking into account.
