### ISSUE TITLE
[sdk] PipelineJob.from_pipeline_func() fails when the pipeline function is imported in current file

### ISSUE THREAD

**Issue by anifort** [kubeflow/pipelines#8913]
** There is no issue when the pipeline function is in the same file as the file that runs PipelineJob.from_pipeline_func(). The issue appears when the pipeline function is imported from another file. In that case the pipeline funciton has no attribute .__name__ .

### Environment

*  KFP version:
Vertex Pipelines
*  KFP SDK version: 2.0.0b12

*  All dependencies version:
kfp                              2.0.0b12 \
kfp-pipeline-spec                0.2.0 \
kfp-server-api                   2.0.0a6 \

### Steps to reproduce
Create a pipeline function in its own file., for example pipeline.py
```
@pipeline()
def my_pipeline():
  ...
  ...
```

In a seperate python file, lets call it pipeline_runner.py do:
```
from pipeline import my_pipeline
PipelineJob.from_pipeline_func(pipeline_func=my_pipeline) 
```
### Expected result
Instead of running successfully, I get the error:
```
        automatic_display_name = " ".join(
            [
>               pipeline_func.__name__.replace("_", " "),
                datetime.datetime.now().isoformat(sep=" "),
            ]
        )
E       AttributeError: 'GraphComponent' object has no attribute '__name__'

.venv/lib/python3.10/site-packages/google/cloud/aiplatform/pipeline_jobs.py:973: AttributeError
```

Run successfully the pipeline. 

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by chensun** [comment]
@anifort `PipelineJob` is code from Vertex SDK, specifically the error stack you got is from
https://github.com/googleapis/python-aiplatform/blob/c515510a2c474772d2ae0fc1e715f6c919d5aebb/google/cloud/aiplatform/pipeline_jobs.py#L973

This happens when Vertex SDK wraps on top of KFP SDK and makes assumptions of KFP implementation details. 
Can you please open an issue in https://github.com/googleapis/python-aiplatform instead?
