### ISSUE TITLE
kubernetes_resource_delete_op  - Remove hardcoded dependency on gcr.io 

### ISSUE THREAD

**Issue by tClelford** [kubeflow/pipelines#9172]
### Feature Area

/area sdk

### What feature would you like to see?
Allow SDK users to override the default image used in `VolumeOp.delete()`. 
### What is the use case or pain point?
Hardcoded dependency on gcr.io makes it impossible to use this feature in an enterprise setting where access to public image repos are usually locked down. Related issue: https://github.com/kubeflow/pipelines/issues/9032

### Is there a workaround currently?
No. A cleanup job outside KFP is probably the best we could do.

---

Love this idea? Give it a 👍.

**Comment by chensun** [comment]
`kubernetes_resource_delete_op` along with `VolumeOp` are deprecated in v2, and replaced by `kubernetes.DeletePVC`. 
Please checkout out the v2 doc on how to use it: https://www.kubeflow.org/docs/components/pipelines/v2/platform-specific-features/#example-readwrite-to-a-kubernetes-pvc-using-kfp-kubernetes

**Comment by chensun** [comment]
Since this specific issue (hard coded image in volume deletion)  is a problem with both v1 and v2, it's not a regression in v2 that blocks moving to v2. 

That being said, I admit we do have more hard-cored images in v2 than in v1. And these two being the unavoidable images:
https://github.com/kubeflow/pipelines/blob/dbebbde2001f7d2a7372a8abfd9c5c5a0eaea2b8/backend/src/v2/compiler/argocompiler/argo.go#L119-L120

I wonder if we were to make these configurable, what would be your allowed registry? dockerhub or something else?
