### ISSUE TITLE
[backend] update cron version to 3.0.1

### ISSUE THREAD

**Issue by Linchin** [kubeflow/pipelines#9547]
Currently KFP uses the package "[github.com/robfig/cron](https://pkg.go.dev/github.com/robfig/cron)" at version 1.2.0 and has been replaced by the [v3 version](https://pkg.go.dev/github.com/robfig/cron/v3). The major difference is version 1.2.0 uses a 6-digit cron string including the seconds, while v3 uses the standard 5-digit string. Upgrading the package will reduce confusion for the users due to most of the documentation on the internet uses the [standard cron](https://en.wikipedia.org/wiki/Cron). Downside is the users can no longer schedule jobs with the granularity of seconds.

Impacted by this bug? Give it a 👍.

**Comment by robbellMF** [comment]
We were recently surprised by this, and it took a while to track down the issue because the documentation doesn't mention about the required format. It's especially confusing because a 5-digit string is happily accepted but interpreted as a 6-digit string.

Could we consider making a breaking change for this? It appears an equivalent breaking change to go from 6-digit to 5-digit cron was made in kfp v1 #4979 - we could make the same change again. Alternatively, we could update the backend apiserver contract to reject 5-digit cron strings when creating recurring runs, to avoid surprise. This would still be a breaking change, but wouldn't break existing recurring runs/require a migration.

At the very least it'd be good to update the v2 documentation to clarify what the format needs to be- I'd be happy to contribute once I know what the contract should be.

**Comment by diegolovison** [comment]
Hello, please do the breaking change in v2. No one understands the 6-digit cron string. It generates a lot of confusion for customers.
