### ISSUE TITLE
How to import containerized Python component after building it?

### ISSUE THREAD

**Issue by parthmishra** [kubeflow/pipelines#9568]
This might be a really dumb question, but given a file layout of something similar to the docs example:
```
pipeline.py
components/
  component.py
  util.py
```

And then running the build command:

```
kfp component build src/ --component-filepattern component.py 
```

How would I import the component in `pipeline.py`? Do I import the generated YAML in `component_metadta/` or do I import the function from the module? It's not clear to me from the docs what is expected for referencing the component.

**Comment by connor-mccarthy** [comment]
I recommend importing the Python component from the module in which it is defined. Loading the YAML also works, however.

**Comment by parthmishra** [comment]
@connor-mccarthy Forgive me for being dense, but by "importing the Python component from the module in which it is defined" do you mean in the `component.py` file? (referencing the example layout above)

For the `pipeline.py` file, what does the import look like? The docs example make it seem like the pipeline function is being defined in a completely flat file structure (i.e. same or sibling module as component) is that correct? 

A folder structure I encounter for python-based components looks like this:

```
my-repo/
├── components
│   ├── bar
│   │   └── component.py
│   └── foo
│       └── component.py
└── pipeline.py
```

What does the import look now if I were to to convert `foo` and `bar` into containerized Python components? Do I build two separate containerized components? could I build a single one containing both?

**Comment by connor-mccarthy** [comment]
Certainly not dense! These are good question and the docs should clarify this more. I will work on an update to the docs. In the meantime, the following take your questions one-by-one and summarizes how to think about Containerized Python Components beneath:

> by "importing the Python component from the module in which it is defined" do you mean in the component.py file?

For this, I mean to import from `bar/component.py` and `foo/component.py` into `pipeline.py`.

> For the pipeline.py file, what does the import look like?

For your specific project layout, the import would be `from components.foo.component import my_component` (replacing `my_component` with whatever the symbol is for your component object`).

> The docs example make it seem like the pipeline function is being defined in a completely flat file structure (i.e. same or sibling module as component) is that correct?

Either works! You'll just need to update the path of the imports to align with how your source code is laid out. This is consistent with normal Python module/object discovery; nothing special is required for KFP.

> Do we need the component_metadata folder? Does importing from the YAML contained their work?

You do not strictly need the `component_metadata` for importing your components into a pipeline. You can load the [IR YAML](https://www.kubeflow.org/docs/components/pipelines/v2/compile-a-pipeline/#ir-yaml) instead of importing the Python object if you'd like, but I recommend importing the Python object to maintain a Pythonic experience end-to-end.

> Should that be what is committed to source control?

While this is up to you and your organization, I recommend committing at least the Python component/pipeline definitions to source control and somehow pinning the version of the KFP SDK used to compile your components/pipelines. This enables you to reliably reproduce compilation, so there is no need to version the YAML directly.

---

In general, it is best to think of [Containerized Python Components](https://www.kubeflow.org/docs/components/pipelines/v2/components/containerized-python-components/) as a convenience mechanism for building images usable in [Lightweight Python Components](https://www.kubeflow.org/docs/components/pipelines/v2/components/lightweight-python-components/). Usage has two parts: (1) you [build the component image](https://www.kubeflow.org/docs/components/pipelines/v2/components/containerized-python-components/#3-build-the-component) and push the image then (2) you use the component, which is essentially now a Lightweight Python Component that references the image you just built/pushed. That's all a Containerized Python Component is.

As for imports and project layout, this is up to you! You'll be subject to all the normal Python rules when importing objects across modules.

Please feel free to re-open if this answer is insufficient.
