### ISSUE TITLE
[backend] input parameter with default value not resolved at runtime.

### ISSUE THREAD

**Issue by chensun** [kubeflow/pipelines#9572]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
KFP standalone
*  KFP version: 
2.0.0rc.1
*  KFP SDK version: 
2.0.0rc.1

### Steps to reproduce

Run the following pipeline: 
https://github.com/kubeflow/pipelines/blob/63936c07735521b1244e1e528a9baf80d40b296d/sdk/python/test_data/pipelines/xgboost_sample_pipeline.py
https://github.com/kubeflow/pipelines/blob/63936c07735521b1244e1e528a9baf80d40b296d/sdk/python/test_data/pipelines/xgboost_sample_pipeline.yaml

### Expected result

Expect pipeline to run successfully.

### Actual result

Pipeline failed due to input parameter with default value not resolved at runtime:
![image](https://github.com/kubeflow/pipelines/assets/2043310/4ba89960-73b1-4e45-8fda-f48f857c12ff)

Impacted by this bug? Give it a 👍.

**Comment by Linchin** [comment]
Hi @chensun, thank you so much for catching this! I think this was caused due to a [decision we made earlier about resolving default parameters](https://github.com/kubeflow/pipelines/blob/c0640d7a033b6fa2133b92c2a459d9eb3dabee32/backend/src/v2/driver/driver.go#L824). In the past, we would add the default parameter values into the `executorInput` when there is no user input, but this will cause the default value to show up at UI as an input, which is somewhat inaccurate. So we decided to not add default values to `executorInput` and let components resolve themselves. I can add some logic to add the default values in the launcher, if they are not already present. This should resolve the bug without undoing the previous decision.
