### ISSUE TITLE
[backend] Pipeline contains failed task shown as succeeded

### ISSUE THREAD

**Issue by chensun** [kubeflow/pipelines#9577]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
KFP standalone
*  KFP version: 
2.0.0-rc.1
*  KFP SDK version: 
2.0.0-rc.1

### Steps to reproduce

Run this pipeline:
https://github.com/kubeflow/pipelines/blob/27d8f7a651631df1afc59b18cb387b7d7dd87636/sdk/python/test_data/pipelines/pipeline_with_exit_handler.py
https://github.com/kubeflow/pipelines/blob/27d8f7a651631df1afc59b18cb387b7d7dd87636/sdk/python/test_data/pipelines/pipeline_with_exit_handler.yaml

### Expected result

Expect pipeline to show failed status. 

### Actual result

Pipeline shown as succeeded even the inner task failed.
![image](https://github.com/kubeflow/pipelines/assets/2043310/7ef8e749-9332-460a-a899-64c6eac588d7)

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by Linchin** [comment]
After some investigation, it turns out that the status of the run comes from the report from argo that is then [relayed by the persistence agent to the backend](https://github.com/kubeflow/pipelines/blob/db1e0e213c83780619dea3eabbc5231450ba62c5/backend/src/agent/persistence/client/pipeline_client.go#L79). Since this is an argo behavior, we will keep it like this.
