### ISSUE TITLE
[feature] filter.proto support for json or nested comparaison

### ISSUE THREAD

**Issue by axel7083** [kubeflow/pipelines#9673]
### Feature Area

/area backend
/area sdk

### What feature would you like to see?

For example when listing runs, I would like to be able to filter based on the pipeline_id, or pipeline_version_id. Those field are nested inside the pipeline_version_reference property. And the following synthax is not supported:

```python
filter = json.dumps({"predicates": [{"operation": "EQUALS", "key": "pipeline_version_reference.pipeline_id","stringValue": "<pipeline-id>",}]})
kubeflow_client.list_runs(filter=filter)
```

### Is there a workaround currently?

Listing all the runs, and filtering manually on the client-side.

---

Love this idea? Give it a 👍.

**Comment by pyxelr** [comment]
@axel7083: Have you had a chance to find out if the feature has been implemented? If not, would you mind providing insight into how you are applying the workaround?

On my side, after the upgrade to Kubeflow 1.8 ([kubeflow/pipelines 2.0.5](https://github.com/kubeflow/pipelines/blob/2.0.5/backend/src/apiserver/model/job.go#L238-L246)) there doesn't seem to be an easy way to filter by `PipelineId` since the `jobAPIToModelFieldMap` has [changed](https://github.com/kubeflow/pipelines/pull/8662).

In [kubeflow/pipelines 2.0.0-alpha.7](https://github.com/kubeflow/pipelines/blob/2.0.0-alpha.7/backend/src/apiserver/model/job.go#L91-L96) this option worked for me:

```python
        filter_spec = json.dumps(
            {
                "predicates": [
                    {
                        "op": 1,
                        "key": "package_id",
                        "stringValue": pipeline.id,
                    }
                ]
            }
        )
```

**Comment by pyxelr** [comment]
Ok, I managed to overcome it with a couple of custom functions and this manual filtering:

```python
return (
    run for run in all_runs if getattr(run.pipeline_spec, "pipeline_id", "") == pipeline_id
)
```
