### ISSUE TITLE
[e2e test] Docker daemon connection is failed

### ISSUE THREAD

**Issue by jlyaoyuli** [kubeflow/pipelines#9704]
Error log:
https://oss.gprow.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/9694/kubeflow-pipeline-e2e-test/1674873953513902080

**Comment by chensun** [comment]
Suspect it's caused by GKE upgrade. 

The last succeeded test run was on June 29, [with GKE version 1.25.8-gke.1000](https://oss.gprow.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/9693/kubeflow-pipeline-e2e-test/1674513454611828736#)
Then it starts to fail since June 30, [with GKE version 1.26.5-gke.1200](https://oss.gprow.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/9694/kubeflow-pipeline-e2e-test/1674873953513902080#)

Looking through the K8s 1.26 release note, I couldn't identify a specific deprecation that could affect us. However, [this Argo doc](https://argoproj.github.io/argo-workflows/walk-through/docker-in-docker-using-sidecars/) warned us that docker-in-docker (dind) using sidecar--that [we're currently using for building test images](https://github.com/kubeflow/pipelines/blob/4a57ab69ddc0abf08daa73473646492bad7ab38d/test/e2e_test_gke_v2.yaml#L271-L278)--are likely to break with future upgrades. It's advised to seek alternatives to building image via dind.
