### ISSUE TITLE
Provide sample pipeline for using GPU/TPU. 

### ISSUE THREAD

**Issue by FaustineLi** [kubeflow/pipelines#980]
As we are developing pipelines,  we have been running into issues with correctly configuring the Kubernetes cluster with the correct permissions, node pools, etc. It would be great if some simple pipelines are made available to test using GPUs/TPUs for example or a simple pipeline that tests read/write access to various resources.

**Comment by vicaire** [comment]
This issue is a bit broad. Let's focus this issue on providing samples for TPU and GPU. Please file additional bugs for other samples that are missing. If you would like to see a sample to access various resources, please file a bug specific to the resource for which you would like to see a sample. Thanks!

**Comment by numerology** [comment]
Add a toy sample demo PR #1749
