### ISSUE TITLE
Upgrade GORM to v2

### ISSUE THREAD

**Issue by chensun** [kubeflow/pipelines#9859]

**Comment by Linchin** [comment]
After some investigation, it feels like this is a colossal change that's impossible to break down. It also involves lots of trivial changes, such as change of function signatures, variable fields, and some functionalities no longer supported. There's a really good summary by another googler on the work items: https://github.com/google/exposure-notifications-verification-server/issues/857
Since this upgrade does not block PostgreSQL support, after some discussion we decided to stay with GORM v1.
