### ISSUE TITLE
[bug] Always 404 on kfp sdk

### ISSUE THREAD

**Issue by d0m3n1cc** [kubeflow/pipelines#9940]
I was using kfp==2.0.0b12 and everything was working great. But as soon as i got into 2.0.1 I am always getting 404 when trying to use methods from client, like this:

`kfp_server_api.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'x-powered-by': 'Express', 'content-security-policy': "default-src 'none'", 'x-content-type-options': 'nosniff', 'content-type': 'text/html; charset=utf-8', 'content-length': '170', 'date': 'Mon, 28 Aug 2023 23:52:33 GMT', 'x-envoy-upstream-service-time': '2', 'server': 'istio-envoy'})
HTTP response body: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /pipeline/apis/v2beta1/pipelines</pre>
</body>
</html>`

I am now using kfp==2.0.1 kfp-pipeline-spec==0.2.2 kfp-server-api==2.0.1 and I am creating the client this way:

`session = requests.Session()
    response = session.get(HOST)

    headers = {
        "Content-Type": "application/x-www-form-urlencoded",
    }

    data = {"login": USERNAME, "password": PASSWORD}
    session.post(response.url, headers=headers, data=data)
    return session.cookies.get_dict()["authservice_session"]
client = Client(host=f"{HOST}/pipeline",
                    cookies=f"authservice_session={session_cookie}",
                    namespace=NAMESPACE)
return client
`

It used to work great, but now using kfp sdk 2.0.1 if I try something like list_pipelines() I am always getting the error.

What am I doing wrong here?

Impacted by this bug? Give it a 👍.

**Comment by connor-mccarthy** [comment]
Which version of the KFP BE do you have deployed?

cc @chensun

**Comment by d0m3n1cc** [comment]
Hey @connor-mccarthy thanks for your reply. The version of my kfp backend is 2.0.0-alpha.7. It's weird because in kfp sdv v2.0.0b12 everything is working, but I cannot make it work with any other version.

**Comment by postera-james** [comment]
I also experience this behavior with `kfp==2.3.0` and kf 2.0.0-alpha.7. It doesn't occur if I downgraded to `kfp==2.0.0b12`

**Comment by Fesh1** [comment]
I have the same issue.

**Comment by bernardogza83** [comment]
what was the fix for this ?

    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'x-powered-by': 'Express', 'content-security-policy': "default-src 'none'", 'x-content-type-options': 'nosniff', 'content-type': 'text/html; charset=utf-8', 'content-length': '170', 'date': 'Mon, 01 Jul 2024 01:06:05 GMT', 'x-envoy-upstream-service-time': '2', 'server': 'istio-envoy'})
HTTP response body: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /pipeline/apis/v2beta1/pipelines</pre>
</body>
</html>
